### PR TITLE
Flux calibration for exposures with very low transmission

### PR DESCRIPTION
**Pull request by julienguy**
If the median S/N in the standard stars is <2 , use a scaled version of the average DESI throughput, fitting a single scalar instead of a calibration coefficient per wavelength bin.

Addresses issue #1100

### CODE REVIEW

**Comment by julienguy** [comment]
Test failing because DESI_SPECTRO_CALIB not set in the tests.

**Comment by sbailey** [comment]
@julienguy for consideration: see test_fibermap.py which has hooks for running some tests only at NERSC where the full environment is available, e.g. in this case a real $DESI_SPECTRO_CALIB.  GitHub would skip the tests, but the nightly update would catch them.

**Comment by sbailey** [comment]
@julienguy the test that you disabled for github is also failing at NERSC, albeit for a different reason.  I suspect that this code works for real data headers but we need to update our simulated test data headers for the tests.  Did you have the tests working on Dirac or your laptop, i.e. is this already fixed somewhere but not committed?
```
$> python py/desispec/test/test_binscripts.py 
...
WARNING:fluxcalibration.py:955:compute_flux_calibration: Very low S/N, use simple scaled version of the average throughput
Traceback (most recent call last):
  File "/global/common/software/desi/users/sjbailey/desispec/bin/desi_compute_fluxcalibration", line 16, in <module>
    fluxcal.main(args)
  File "/global/common/software/desi/users/sjbailey/desispec/py/desispec/scripts/fluxcalibration.py", line 172, in main
    fluxcalib = compute_flux_calibration(frame, model_wave, model_flux, model_fibers%500, highest_throughput_nstars = args.highest_throughput)
  File "/global/common/software/desi/users/sjbailey/desispec/py/desispec/fluxcalibration.py", line 956, in compute_flux_calibration
    fluxcalib_filename = findcalibfile([frame.meta],"FLUXCALIB")
  File "/global/common/software/desi/users/sjbailey/desispec/py/desispec/calibfinder.py", line 105, in findcalibfile
    cfinder = CalibFinder(headers,yaml_file)
  File "/global/common/software/desi/users/sjbailey/desispec/py/desispec/calibfinder.py", line 175, in __init__
    detector=header["DETECTOR"].strip()
KeyError: 'DETECTOR'
```

**Comment by sbailey** [comment]
For the record I fixed this test failure in commit e7d139e direct to master by adding DETECTOR='SIM' to the test frame header.

**Pull request merged**
