### PR TITLE
use extinction_total_to_selective_ratio func to get extinction from EBV

### PR DESCRIPTION
**Pull request by julienguy**
Use extinction_total_to_selective_ratio func to get extinction from EBV for the fit of standard stars.

### CODE REVIEW

**Comment by julienguy** [comment]
(needs first to merge the PR with same name in desiutil)

**Review by akremin — COMMENTED** [review]
It's nice that this has the added bonus of removing some trailing whitespace. 

A few comments below, but none are blocking factors for a PR as the code works based on a test exposure: 67289 from Dec 12th, 2020 done in SPECPROD=daily at NERSC. outputs: `/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201212/00067289/`
log: `/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20201212/science-20201212-00067289-a0123456789-37239928.log`

Comment 1:
You could add comments to describe what the r_band and a_band refer to/mean. 

Comment 2:
Is there ever a chance that these inputs will be lists that don't understand boolean indexing? It currently works, so as long as they are always arrays, the logic will work.

Comment 3:
You could also add a short comment on the dimensions of each. I figured it out but it took a minute to parse together the dimensions of everything.

**Comment by julienguy** [comment]
About your 'Comment 2', the fibermap type is a table, being an attribute of the class Frame. And star_unextincted_mags[band] is a numpy array declared in the function so they always accept boolean indexing.

**Review by akremin — APPROVED** [review]
Looks good, thanks. The added comments are informative. I was more asking about the shapes of the input/output arrays than in physical units when I referred to "dimensions," but it's not an important issue. I'm okay with merging if Stephen gives a thumbs up

**Comment by sbailey** [comment]
Thanks for cross checks and additional comments.  Merging now, not waiting for Travis.

**Pull request merged**
