### PR TITLE
add tilenight support to desi_daily_proc_manager

### PR DESCRIPTION
**Pull request by marcelo-alvarez**
Implements #1908 with modifications of `daily_processing.py` that are nearly identical to those of `submit_tilenight.py` in #1802. 

@sbailey please review, thanks.

### CODE REVIEW

**Comment by marcelo-alvarez** [comment]
@sbailey I have tested against the main branch on Cori and Perlmutter with
```
desi_daily_proc_manager --ignore-cori-node --dry-run-level 1 --override-night 20230210
```
with and without `--use-tilenight` / `--no-use-tilenight` for this branch on Perlmutter (tilenight is not supported on Cori and therefore those flags were left out for testing on Cori). Running `desi_daily_proc_manager` on Perlmutter results in tilenight being used.

The original contents of the SPECPROD directory for each of these runs has been copied to the directories in
```
/global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2028
```
and more information about each of the runs is listed in
```
/global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2028/README
```

The results appear correct to me. Most notably, running
```
desi_daily_proc_manager --ignore-cori-node --dry-run-level 1 --override-night 20230210
```
on this branch and the main branch produces identical batch scripts, e.g.:
```
cd /global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2028/
nightdir=run/scripts/night/20230210/
tiledir=run/scripts/tiles/cumulative/5627/20230210/
for dir in $(echo $nightdir $tiledir); do
  for f in $(ls main_cori/$dir/*.slurm)
    do slurmfile=$(basename $f)
    diff $f tilenight-dailyproc_cori/$dir/$slurmfile
  done
done
```
produces no output from each of the diff commands.

Please do your own testing before merging since this touches dailyops. Thanks.

**Comment by marcelo-alvarez** [comment]
@sbailey thanks for catching this. I copied and pasted the `create_and_submit` call from `submit_night.py` instead of from above, not realizing that the variable `cur_z_submit_types` is used in `submit_night.py` but not `daily_processing.py`. There was also an error in the block
``` 
           if (not use_tilenight) or erow['OBSTYPE'] != 'science':
```
where I only changed that line to match `submit_night.py` but didn't indent the line below that creates the processing table row. 

These changes fix the crashing for 20230318 and (1) the spurious prestdstar processing table entries. I also verified that the exposure table created is identical to that in daily:
```
diff /global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2028/tilenight-dailyproc_perlmutter_use-tilenight-20230318/exposure_tables/202303/exposure_table_20230318.csv /global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202303/exposure_table_20230318.csv
```
and
```
/global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2028/tilenight-dailyproc_perlmutter_use-tilenight-20230318/run/scripts/night/20230318/tilenight-20230318-8805.slurm
```
looks good to me, so hopefully (2) is also fixed. Please have a look.

**Comment by marcelo-alvarez** [comment]
@sbailey (2) above should be fixed. Please have a look and run independent tests. Thanks.

**Comment by sbailey** [comment]
Retesting on a new production with `desi_daily_proc_manager --ignore-cori-node --override-night 20230318 --dry-run-level 1`:

  0. previous crash - fixed
  1. previous spurious prestdstar entries in the processing table - fixed
  2. previous crashes of tile/exp 8805/172284 and 23616/172291 - not quite fixed

for (2), previously it submitted jobs that would crash due to missing `--expid` args.  Now it doesn't create jobs for those two tiles at all.  Both of those exposures are auto-flagged for `LASTSTEP='skysub'` due to low survey speed.  To match current non-tilenight behavior, it should generate jobs that process through sframes and then stop.

**Comment by marcelo-alvarez** [comment]
@sbailey thanks. I thought `LASTSTEP='skysub'` exposures were not processed for daily processing. I will make the change to match non-tilenight behavior and process them.

**Comment by marcelo-alvarez** [comment]
@sbailey I have updated so that LASTSTEP=skysub exposures are processed and verified that for 20230318 the processing for LASTSTEP=skysub exposures in tiles 8805 and 23616 (172284 and 172291, respectively), result in sframe, but not cframe, files, as a result of running
```
desi_daily_proc_manager --ignore-cori-node --override-night 20230318
```
with this branch on Perlmutter. Please have a look, thanks.

**Pull request merged**
