### PR TITLE
Update QL SNR fit

### PR DESCRIPTION
**Pull request by rstaten**
This PR:
- Updates the SNR fit to include exposure time.
- Updates the conversion of imaging magnitude to flux.
- Includes minor updates for SNR plots.
- Adds imaging magnitudes to SNR output.
- Returns the median of sky fibers over sky peaks for QA Sky_Peaks.

### CODE REVIEW

**Comment by rkehoe** [comment]
@rstaten, @Srheft This branch looks good to me.  I can't run a test right now, but aside from doing that it looks like it is ready to merge.  Please go ahead with that as appropriate.

**Comment by Srheft** [comment]
@rstaten: thank you for this. SNR evaluation is starting to come together nicely.  Could you:

in line 586 of qalib.py, use the json file as opposed to yaml. We no longer produce yamls in the next release but now that we have both in current master, let's see the migration in full effect.

**Comment by Srheft** [comment]
@rstaten:  please also make this change->  in line 587 of qalib.py  NOISE_OVER -> NOISE

**Comment by rstaten** [comment]
@Srheft I fixed/added points 2 and 3. As 1 will involve more changes than the line you mention, I will do this in a subsequent branch. Regarding 4, currently SNR fits each object type, so choosing a single magnitude range won't work for all objects (specifically STD). This can be reconciled if we decide to only fit certain object types, but for now it seems to make sense to fit the whole magnitude range.

**Comment by rkehoe** [comment]
@rstaten  About the item 4, I would suggest to consider a third option, for a future branch though since we want this PR merged soon.  This third option might be to have the algorithm auto determine the magnitude range per object, based on some general principles (eg. # of objects in 0.25 mag bins, no less than 2 mag range).  I don't think we want to add configuration parameters for each target type, but it seems likely we will want to know the results for all target types during data taking.   Perhaps you can include this with the branch where you take care of the JSON migration point from @Srheft ?

**Comment by Srheft** [comment]
Merged.

**Pull request merged**
