### PR TITLE
Tsnr missing

### PR DESCRIPTION
**Pull request by araichoor**
This PR modifies bin/desi_tsnr_afterburner to populate exposures with missing values ("unknown"): SURVEY, GOALTYPE, FAPRGRM, FAFLAVOR, MINTFRAC, GOALTIME, and EFFTIME_ETC and EBV.
It grabs information from the exposure_table and, if missing, from the fiberassign.
Additionally, there is a minor modification on EBV (taking the median of EBV>0 values only).
The above was done by @araichoor.

Lastly, there are various fixes (GPA, GPB, others), done by @akremin.

### CODE REVIEW

**Comment by akremin** [comment]
Bringing a private message from Anand into the record. He found differences between this branch and daily (not surprising because other things have changed since that was run on historical nights). But also found differences between this branch and master (less ideal most columns shouldn't change with the changes made here to only a few columns).

---- Begin Anand's message ----
I've generate the tsnr for:
all nights since 20210401 with the branch code: /global/homes/r/raichoor/Scripts/my-tsnr-branch-20210401-20210630.fits
all nights since 20210604 with the master code: /global/homes/r/raichoor/Scripts/my-tsnr-master-20210601-20210630.fits (nights before that crash)
and I've compared branch vs. master vs. daily.
I report below the number of differences per column (with my python lines, if it helps).
I comment on a few differences, but not all, as I'm not sure which ones are expected and which ones deserve a closer look.

#### Code
```
from desitarget.geomask import match
fns = {
    "branch" : "/global/homes/r/raichoor/Scripts/my-tsnr-branch-20210401-20210630.fits",
    "master" : "/global/homes/r/raichoor/Scripts/my-tsnr-master-20210601-20210630.fits",
    "daily" : "/global/cfs/cdirs/desi/spectro/redux/daily/tsnr-exposures.fits"
}
for case0, case1 in zip(["branch", "branch", "master"], ["master", "daily", "daily"]):
    d0 = fits.open(fns[case0])[1].data
    d1 = fits.open(fns[case1])[1].data
    ii0, ii1 = match(d0["EXPID"], d1["EXPID"])
    d0, d1 = d0[ii0], d1[ii1]
    keys = np.array(d0.dtype.names)
    ns = np.zeros(len(keys), dtype=int)
    for i in range(len(keys)):
        ns[i] = (d0[keys[i]] != d1[keys[i]]).sum()
    print("# {} vs. {} : {} exposures".format(case0, case1, d0.size))
    for n in np.unique(ns):
        if n != 0:
            print("\t{} : {} differences".format(",".join(keys[ns==n]), n))
```


#### branch vs. master : 447 exposures
```
	EFFTIME_ETC : 17 differences # those have EFFTIME_ETC=0 in master, so good.
	SURVEY,FAPRGRM,FAFLAVOR,GOALTIME,GOALTYPE,MINTFRAC : 25 differences # those have like SURVEY=“unknown” in master, so good.
	EFFTIME_GFA,EFFTIME_DARK_GFA,EFFTIME_BRIGHT_GFA,EFFTIME_BACKUP_GFA : 422 differences # here, I don t know…
	EBV : 439 differences # expected as we now exclude ebv=0 fibers from the computation
```

#### branch vs. daily : 1835 exposures
```
	SEEING_GFA,FIBER_FRACFLUX_GFA,FIBER_FRACFLUX_ELG_GFA,FIBER_FRACFLUX_BGS_GFA : 1 differences
	EXPTIME,AIRMASS,TRANSPARENCY_GFA : 2 differences
	TSNR2_ELG,TSNR2_QSO,TSNR2_LRG,TSNR2_LYA,TSNR2_BGS,LYA_EFFTIME_DARK : 14 differences
	TSNR2_GPBDARK,TSNR2_GPBBRIGHT,TSNR2_GPBBACKUP,GPB_EFFTIME_DARK,GPB_EFFTIME_BRIGHT,GPB_EFFTIME_BACKUP : 36 differences
	MINTFRAC : 43 differences # daily has only default values, good
	GOALTIME : 65 differences# daily has only default values, good
	GOALTYPE : 73 differences# daily has only default values, good
	SURVEY : 88 differences# daily has only default values, good
	FAPRGRM,FAFLAVOR : 161 differences# daily has only default values, good
	EFFTIME_ETC : 930 differences # lots of zeros in daily, but also some real values changed
	SEEING_ETC : 1044 differences
	SKY_MAG_G_SPEC,SKY_MAG_R_SPEC,SKY_MAG_Z_SPEC : 1300 differences
	EFFTIME_SPEC : 1619 differences
	BGS_EFFTIME_BRIGHT : 1660 differences
	EFFTIME_GFA,EFFTIME_DARK_GFA,EFFTIME_BRIGHT_GFA,EFFTIME_BACKUP_GFA : 1670 differences
	ELG_EFFTIME_DARK : 1674 differences
	EBV : 1691 differences
```

#### master vs. daily : 447 exposures
```
	SKY_MAG_G_SPEC,SKY_MAG_R_SPEC,SKY_MAG_Z_SPEC : 2 differences
	BGS_EFFTIME_BRIGHT : 416 differences
	EFFTIME_SPEC : 419 differences
	ELG_EFFTIME_DARK,EFFTIME_GFA,EFFTIME_DARK_GFA,EFFTIME_BRIGHT_GFA,EFFTIME_BACKUP_GFA : 422 differences
```

**Comment by akremin** [comment]
I was able to reproduce Anand's numbers and dug in further. The following are more detailed outputs comparing the master and branch values (which should agree except for "fixes").

For columns with many differences, I report summary statistics. For those with less than 40 differences, I print the values themselves. We see the majority of the changes are intended. The problematic columns, as flagged by Anand as well, are the EFFTIME's associated with the GFA along with the EBV column. 

Since I don't see any changes to the GFA columns in this branch, my working hypothesis is that the EBV difference is leading to differences in derived GFA quantities.

### branch vs. master : 447 exposures
```
	For SURVEY, the 25 differences are: 
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
	For FAPRGRM, the 25 differences are: 
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
	For FAFLAVOR, the 25 differences are: 
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
	For GOALTIME, the 25 differences are: 
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
	For GOALTYPE, the 25 differences are: 
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
	For MINTFRAC, the 25 differences are: 
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
	For EBV, among 439 differences: 
						 meanabs = 0.0033833698835223913
						 medianabs = 0.0007991194725036621
						 std = 0.01184732373803854
						 minabs = 0.00018486566841602325
						 maxabs = 0.09298509359359741
						 min = 0.00018486566841602325
						 max = 0.09298509359359741
	For EFFTIME_ETC, the 17 differences are: 
						 branch=58.69040298461914  vs master=0.0
						 branch=74.8637466430664  vs master=0.0
						 branch=6.956409931182861  vs master=0.0
						 branch=65.94044494628906  vs master=0.0
						 branch=29.657896041870117  vs master=0.0
						 branch=31.63385581970215  vs master=0.0
						 branch=44.03044128417969  vs master=0.0
						 branch=92.56800842285156  vs master=0.0
						 branch=56.59944534301758  vs master=0.0
						 branch=30.08487319946289  vs master=0.0
						 branch=34.86797332763672  vs master=0.0
						 branch=85.64836120605469  vs master=0.0
						 branch=16.396894454956055  vs master=0.0
						 branch=0.25492599606513977  vs master=0.0
						 branch=6.000000212225132e-06  vs master=0.0
						 branch=59.7931022644043  vs master=0.0
						 branch=54.38188552856445  vs master=0.0
	For EFFTIME_GFA, among 422 differences: 
						 meanabs = 2.821154957761953
						 medianabs = 1.281807044156821
						 std = 3.767118376735675
						 minabs = 0.1288128220851945
						 maxabs = 31.310426935158716
						 min = -31.310426935158716
						 max = -0.1288128220851945
	For EFFTIME_DARK_GFA, among 422 differences: 
						 meanabs = 2.7529677816377225
						 medianabs = 1.1651457417606252
						 std = 3.78091514177944
						 minabs = 0.09259290837968592
						 maxabs = 31.310426935158716
						 min = -31.310426935158716
						 max = -0.09259290837968592
	For EFFTIME_BRIGHT_GFA, among 422 differences: 
						 meanabs = 2.537712351759514
						 medianabs = 1.279642851780423
						 std = 3.2846920131008663
						 minabs = 0.1288128220851945
						 maxabs = 26.81029212899523
						 min = -26.81029212899523
						 max = -0.1288128220851945
	For EFFTIME_BACKUP_GFA, among 422 differences: 
						 meanabs = 2.4853339325437034
						 medianabs = 1.3741670204647676
						 std = 3.0324382291011864
						 minabs = 0.07630972368585986
						 maxabs = 25.769768351808352
						 min = -25.769768351808352
						 max = -0.07630972368585986
```

**Comment by sbailey** [comment]
Are all of the EFFTIME differences before a certain date, and then the same after that?

I see in desispec.efftime.compute_efftime a comment
```
# AR https://desi.lbl.gov/trac/wiki/SurveyOps/SurveySpeed
# AR 2021-03-05: GFA values are now computed for a fiber diameter of 1.52"
```
and there was also a reorganization of that code in early April for PR #1232, but that might have been when those columns appeared, not when they changed.

We also rely upon an external GFA processing from /global/cfs/cdirs/desi/survey/GFA/ ; is it possible that those got updated after daily was run?

**Comment by dkirkby** [comment]
Can you provide a NIGHT/EXPID for one of the EFFTIME_ETC discrepancies and I will check if the `branch` value matches the ETC json file (in which case it should probably be in the TSNR file and not set to zero).

**Comment by akremin** [comment]
Thank you both but my working hypothesis seems to be correct. I commented out the new EBV logic that only takes the median of the non-zero EBV values and replaced it with a median of all fibers (like it is in master). All the GFA EFFTIME issues disappeared.

All remaining differences with master are filling in "missing" columns that have 0's or "unknown"'s in master. 

There are many more differences with daily, but those are also present in master, so while it might be worth investigating those changes as well, this PR doesn't impact it as the current master code produces the same deviations.

To be clear I am not removing or changing the new EBV logic. That was intentionally changed to the more correct value. Stuck positioners had EBV=0 and were skewing the median, which we don't want.  I only commented those few lines out temporarily to verify that the changes were coming from that code change.

David -- I did verify that the first few EFFTIME_ETC's here correspond to the values in the json file. For completeness all 17 of the exposure id's are: 93584, 93585, 93601, 94677, 94989, 95318, 95406, 95409, 95411, 95412, 95413, 95496, 95507, 95517, 96371, 96468, 96689.

#### branch with new EBV logic commented out vs. master : 447 exposures
```
	For SURVEY, the 25 differences are: 
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
						 branch=main  vs master=unknown
	For FAPRGRM, the 25 differences are: 
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
	For FAFLAVOR, the 25 differences are: 
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=maindark  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
						 branch=mainbright  vs master=unknown
	For GOALTIME, the 25 differences are: 
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=1000.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
						 branch=180.0  vs master=0.0
	For GOALTYPE, the 25 differences are: 
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=dark  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
						 branch=bright  vs master=unknown
	For MINTFRAC, the 25 differences are: 
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
						 branch=0.85  vs master=0.9
	For EBV, the 17 differences are: 
						 branch=0.02390635758638382  vs master=0.0
						 branch=0.09298509359359741  vs master=0.0
						 branch=0.07484586536884308  vs master=0.0
						 branch=0.048329077661037445  vs master=0.0
						 branch=0.05140154808759689  vs master=0.0
						 branch=0.06173881143331528  vs master=0.0
						 branch=0.038866207003593445  vs master=0.0
						 branch=0.06162199750542641  vs master=0.0
						 branch=0.08237429708242416  vs master=0.0
						 branch=0.08237429708242416  vs master=0.0
						 branch=0.08237429708242416  vs master=0.0
						 branch=0.009764271788299084  vs master=0.0
						 branch=0.03486481308937073  vs master=0.0
						 branch=0.06173881143331528  vs master=0.0
						 branch=0.04587302356958389  vs master=0.0
						 branch=0.06161540001630783  vs master=0.0
						 branch=0.07032466679811478  vs master=0.0
	For EFFTIME_ETC, the 17 differences are: 
						 branch=58.69040298461914  vs master=0.0
						 branch=74.8637466430664  vs master=0.0
						 branch=6.956409931182861  vs master=0.0
						 branch=65.94044494628906  vs master=0.0
						 branch=29.657896041870117  vs master=0.0
						 branch=31.63385581970215  vs master=0.0
						 branch=44.03044128417969  vs master=0.0
						 branch=92.56800842285156  vs master=0.0
						 branch=56.59944534301758  vs master=0.0
						 branch=30.08487319946289  vs master=0.0
						 branch=34.86797332763672  vs master=0.0
						 branch=85.64836120605469  vs master=0.0
						 branch=16.396894454956055  vs master=0.0
						 branch=0.25492599606513977  vs master=0.0
						 branch=6.000000212225132e-06  vs master=0.0
						 branch=59.7931022644043  vs master=0.0
						 branch=54.38188552856445  vs master=0.0


	EBV,EFFTIME_ETC : 17 differences
	SURVEY,FAPRGRM,FAFLAVOR,GOALTIME,GOALTYPE,MINTFRAC : 25 differences 
```

**Review by akremin — APPROVED** [review]
This does impact the values of the EBV column for most exposures and therefore the GFA EFFTIMES which use that EBV. The change is correct and the numeric discrepancies were verified to be caused by that change (removing the change made the numeric differences go away).

This also corrects bugs and makes the afterburner more robust.

Finally, for exposures with no cframes it is able to fill in some useful information about the exposure rather than leaving it with all 0's and "unknown"'s for its columns.

The code works in testing and it gives the expected outputs.

**Pull request merged**
