### PR TITLE
update of QA dictionaries: PARAMS and METRICS in online and offline QAs

### PR DESCRIPTION
**Pull request by rkehoe**
Update of QAs to bring 'offline' and 'online' into closer agreement.

- for 'online' QAs (those written originally for quicklook):  Add 'PARAMS' subdictionary to include configurable thresholds and reference values to 3 QAs (sky residual, countbins, countpix).  Adopt data subdirectory label 'METRICS'  (i.e. 'VALUES' --> 'METRICS')

- for 'offline' QAs (those written initially for offline pipeline): relabel data and parameter subdictionaries as 'METRICS' and 'PARAMS', respectively.

### CODE REVIEW

**Comment by rkehoe** [comment]
@gdhungana: Could you look at the conflict -- seems to arise late last week.

**Comment by sbailey** [comment]
Looks fine to me, but assigning to @profxj to make sure that the standardizing offline/online went in a direction that he agrees with too.  I see that this has some conflicts in qa/qa_plots_ql.py and qa/qa_quicklook.py that will have to be resolved by hand for the merge.  After @profxj signs off, perhaps @rkehoe and @samikama could do that merge and resolve the conflicts.

**Comment by profxj** [comment]
I've reviewed all the non-QL code and that all looks quite fine to me.
Would be good to do an offline prodrun test to insure things are fine but I'm rather
confident they will be.

**Comment by gdhungana** [comment]
Recent commits have fixed the conflict, and a QL run, and tests have passed successfully. Now that @profxj has given a pass for non-QL part, I am going to merge this shortly.

**Pull request merged**
