### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by sbailey**
This PR scratches an itch by improving the desispec test coverage (though it is still at a sad 51%).

* `bootcalib.bootcalib()` is broken; see issue #174.  This PR adds an "expectedFailure" test that will start passing once bootcalib.bootcalib() is fixed again.  Note: the command line script and the pipeline don't use this function, but quicklook does.  #174 describes some desired re-organization to remove this redundancy.
* updated `runcmd()` to accept either a function to run or a command line string to run, and use that to test that the bin scripts and the `scripts.*.main()` functions actually do the same thing.
* re-enabled coverage tests of `main()` functions -- we still have algorithms in some of them and we shouldn't get a free pass on lack of coverage there.
* Added keywords to bootcalib output files to be more like other PSF files (NPIX_X, NPIX_Y, PSFTYPE) and updated the PSF class to use header keywords instead of hardcoded npix_x/y and parsing camera name from the filename.
* improved coverage of `pipeline.plan` and `bootcalib.qa*`

Other big items missing unittest coverage:
* io.database (Ben is working on that, perhaps via a separate PR)
* quicklook
* several of the pipeline scripts, especially those that call external packages to work (specex, specter, redmonster); these are tested via the integration test but not the unit tests
* pipeline.run -- lots of MPI stuff in there

### CODE REVIEW

**Comment by weaverba137** [comment]
Not sure why you commented out the ignore script hooks.  That will decrease coverage with no obvious benefit.

**Comment by sbailey** [comment]
Ironically, this PR to improve test coverage is failing tests on Travis...  :)  However, this is due to a failure to download the bootcalib test files from NERSC, which is having big /project disk problems today.  After NERSC has recovered, I'll reset these tests to run again.

**Comment by sbailey** [comment]
> Not sure why you commented out the ignore script hooks. That will decrease coverage with no obvious benefit.

I re-enabled coverage tests of main() functions because some of them still have substantial amounts of code and we shouldn't get a free pass on coverage just because they are in a function called main().  e.g. `scripts.bootcalib.main()`, `scripts.makebricks.main()`, `scripts.extract.main()`.  It would be preferable to further clean those up, but in the meantime we should know that we're not getting good coverage on them.

And on some of them, test.test_binscripts does cover them, which is good!

**Comment by weaverba137** [comment]
I am working on a fix to these bootcalib errors on a separate branch.

There are a number of serious problems with test_bootcalib.py:

1. Uses urllib2 instead of requests.
2. Doesn't even try to catch http errors.
3. Runs setUp instead of setUpClass which means the download is retried for every method in class TestBoot.
4. Even if the download does succeed, it does not define a particular directory to write the files.
5. Doesn't clean up after itself properly.

**Comment by sbailey** [comment]
> Uses urllib2 instead of requests.

This seems ok to me; urllib2 is built into python while requests is an external dependency, and the usage of urllib2 here is simple and already written.

> Doesn't even try to catch http errors.

That is a problem

> Runs setUp instead of setUpClass which means the download is retried for every method in class TestBoot.

setUpClass would be better, though at least the current code does check for the existence of the file so it doesn't actually redo the download every time.  `os.path.isfile()` would be a clearer check.

> Even if the download does succeed, it does not define a particular directory to write the files.
> Doesn't clean up after itself properly.

Leaving them in the top-level directory is a bit irritating, but the lack of cleanup is sort of a feature since it means that it doesn't have to redownload them the next time that the test is run.  It would be nice if they would be downloaded to some other more hidden directory (under etc? data? test? temp?) but still leave them behind for the next time that the test is run (e.g. on an airplane, or when NERSC is down...)

**Comment by weaverba137** [comment]
Thanx for the comments, but I'm already way past that point, see #244.

**Comment by sbailey** [comment]
#244 made good improvements but might have generated a merge conflict on the bootcalib tests.  I will rebase this branch off of master and re-push to integrate those changes.

**Pull request merged**
