### PR TITLE
Coadd fix compatibility

### PR DESCRIPTION
**Pull request by alxogm**
coadd_cameras.py is not working for mocks previous to this recent PR https://github.com/desihub/desispec/pull/1079, since the 'EXPTIME' column is not present in the fibermap.  Is it ok to fix it here, for back compatibility? or should I try to solve it in the code where we use it. It is one line.

### CODE REVIEW

**Comment by julienguy** [comment]
I think it is now fixed in master, can you please verify?

**Comment by julienguy** [comment]
I checked it is fixed in master, so I am closing this PR.

**Comment by alxogm** [comment]
Thanks @julienguy, yes it is working.

**Comment by alxogm** [comment]
No, I've deleted it. thanks

**Pull request closed without merging**
