### PR TITLE
Save night_info to json files for each night

### PR DESCRIPTION
**Pull request by zkdtc**
Save night_info to json files for each night. If the exposure is GOOD, use the archive result instead of scanning again.

### CODE REVIEW

**Comment by zkdtc** [comment]
For 20201214 to 20201216, the processing time is reduced from 38s(no previous stored result) to 18s (with previous stored result) with consistent result.

**Comment by akremin** [comment]
I verified that this does work for the nights you provide in the intro to this PR. I then tried other nights. Nights that use the brute force search and don't load in an exposure table work, but nights that load the exposure table fail. So nights prior to mid-february 2021 succeed and afterward fail with the following error:

`desi@cori21 [dashboard]$ desi_proc_dashboard --output-dir=$DESI_SPECTRO_REDUX/$SPECPROD/dashboard --output-name=dashboard2.html --start-night=20210214 --end-night=20210216`

```
Searching /global/cfs/cdirs/desi/spectro/redux/daily for  ['20210216' '20210215' '20210214']
Month: 202102, nights: ['20210216', '20210215', '20210214']
mkdir: cannot create directory ‘/global/cfs/cdirs/desi/spectro/redux/daily/dashboard/files/’: File exists
INFO:tableio.py:281:load_table: Found table: /global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202102/exposure_table_20210216.csv
INFO:tableio.py:281:load_table: Found table: /global/cfs/cdirs/desi/spectro/redux/daily/processing_tables/processing_table_daily-20210216.csv
Traceback (most recent call last):
  File "/global/homes/k/kremin/workspace/testdesispec/desispec//bin/desi_proc_dashboard", line 17, in <module>
    main(args)
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 261, in main
    nightly_tables.append(nightly_table(night,skipd_expids,show_null=args.show_null,use_short_sci=args.include_short_scis,args=args))
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 313, in nightly_table
    json.dump(night_info,json_file)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```


And please change the `try`/`except` statement using os.system to the following: `os.makedirs(os.path.join(args.output_dir,'files'),  exist_ok=True)`

**Comment by sbailey** [comment]
Regarding "TypeError: Object of type int64 is not JSON serializable": unfortunately the python json library doesn't automatically interpret/convert numpy ints and floats as core python types for serialization, so you have to explicitly cast them, e.g.
```
x = np.arange(10)
json.dumps(dict(a=x[1]))        # FAILS
json.dumps(dict(a=int(x[1])))   # WORKS
```

**Comment by zkdtc** [comment]
Got it~

**Comment by zkdtc** [comment]
New version tested fine.

**Comment by akremin** [comment]
Thanks, the code now works on data with and without load-able exposure tables.

I do see an improvement in speed between having the files and not having the files. It isn't as dramatic as I expected, but I now realize that very few nights actually have a significant number of fully completed rows (due to immobile petals, etc.), and this just archives rows it knows won't change. I think it's a nice first step and we get modest improvements. 

Dec 14th to Dec 16th (many fully complete exposures):
No cache:    0m40.528s
With cache: 0m26.532s

Jan 14th to March 24th (few fully complete exposures, some loadable exposure tables and some not):
No cache:    1m46.747s
With cache: 1m16.901s

All of SV1:
No cache:    6m45.163s
With cache: 5m34.832s

**Review by akremin — APPROVED** [review]
This provides a first step toward caching rows that are known to be completed. It provides some speed gains and puts the framework in place for future development. I tested it on all of SV1 and it works.

**Pull request merged**
