### PR TITLE
QL Cosmics

### PR DESCRIPTION
**Pull request by rkehoe**
This PR will attempt to improve on cosmic ray removal when running qproc reductions.  It will also upgrade the XWSigma QA to more carefully handle poorly fit lines, including those impacted by cosmics.  A more specific feature list will be itemized as it is pushed here.

### CODE REVIEW

**Comment by rkehoe** [comment]
I’ve changed this PR’s course to focus on addressing the identified issue of QuickLook use of speclite, which occurs in order to calculate a spectral magnitude using broadband filter response.  This PR addresses a problem by which prior attempts to access the input response file would crash, as identified in PR #725.  This has now been fixed using the first approach suggested by @sbailey.  Specifically, this PR contains the following updates:

- use of resource_file to access the speclite response file.  An error is reported if the file is not found.  
- an update to the XWSigma QA to cap the width of line fits.

This PR was tested with QuickLook standalone running, and running via QLF.  In both cases, running with master produced the error, and running with this PR avoided it.  Thanks @rstaten for testing this!

@felipelm. This PR should produce no difference in output relative to what was observed in PR #725.  Please have a look at it also.  If you confirm all is in order, I will merge this PR.  (We will punt the cosmics update to a later update.)

**Comment by rkehoe** [comment]
@felipelm.  I forgot to mention the tag versions that this PR QuickLook was tested with.  Since different code versions did show up recently, maybe this will be useful:

desiutil 1.9.14
desitarget 025.0
desisim 0.31.0
desimodel 0.9.9
specter 0.9.1
speclite v0.8
qlf master

@rstaten sent a version of the mergedQA on the ql-qlf-int mailing list in case you want to make a comparison.

**Comment by felipelm** [comment]
Thanks for the dependencies list @rkehoe was really helpful.

Science, arc and flats ran fine but I miss the OBJTYPE in the mergedQA. Was it moved somewhere else?

`TASKS -> CHECK_SPECTRA -> METRICS -> OBJLIST`

This breaks the science SNR plot.

**Comment by rkehoe** [comment]
@felipelm Sure, no problem. 

I think your comment on the 'OBJTYPE' is that the OBJLIST is missing from recent QL's, correct?  The change happened already in master, and shouldn't have.  We're improving our tests with QLF to check more thoroughly so we catch this right away.  We should have some more flexible tools/scripts by which we can easily compare a current JSON with a reference one for the sake of debugging.  I think this will help with anybody's use/testing of this system.  @rstaten and I will take a start, but I'll draft a ticket on this once we get past the current items to field comments.

In the meantime, @rstaten will update the PR for the missing list soon.

**Comment by rkehoe** [comment]
Thanks @felipelm.  I will merge this.

@sbailey, @srheft, @julienguy This PR is the last loose end from the integration of qframe and the new fibermap file.  As such, Issue #685 and Issue #698 can now be closed.

**Pull request merged**
