### PR TITLE
Update Exposure Tables

### PR DESCRIPTION
**Pull request by akremin**
### Overview
This pull request adds a new script to `desispec`: `desi_update_exposure_tables`. It nominally takes a night or list of nights and creates an updated version of the pipeline exposure tables in the current pipeline format, while preserving any user defined values in the original table. You can specify a custom location for the files, specify obstypes, or define a new file extension to save in a different format (so long as `astropy.table.Table.write` can autodetect it). 

I also renamed the `create_exposure_tables` script to `desi_create_exposure_tables` to make it consistent with other scripts.

### Implementation Details:
* An old table must exist to run on a given night, since `desi_create_exposure_tables` is the proper script for creating a table.
* The function `create_exposure_table` is used to create a new table in the current datamodel, then that is updated with user-defined values from the old table.
* The original table is archived with a timestamp appended to its name before the new table is written to the original location. Syntax: `exposure_table_<NIGHT>.replaced-<TIMESTAMP>.csv`
* The code logs every change made, which makes it verbose but felt useful so that the log could be used for reference if needed.

### Tests
This was tested on all exposure tables to date -- ranging from Feb. 2020 through Dec. 14th, 2021. All nights ran without issue and spot checks of the tables look good.

The outputs are here: `/global/cfs/cdirs/desi/users/kremin/spectro/redux/updateexptables`

### Notes
* There are three special-case `if` statements to clean up unhelpful/wrong comments from early exposure tables. These relate to ETC exposures being called "aborted" and missing "PURPOSE" being needlessly flagged when not present in minisv2 days.
* When running on many nights this can take a while given that `create_exposure_table` opens ~four files per exposure and there can be 100 exposures in a night.
* I can't find any useful error message in the doc test failure, and seems to pass when I run on cori.

### CODE REVIEW

**Comment by sbailey** [comment]
One hiccup:  there are multiple cases where the new exposure tables have FA_SURV=unknown but the reference fiberassign files in svn (/global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/) have FA_SURV=cmx.  Curiously, in some of these cases the exposure table is correct on some nights but not others, e.g.

Tile 70003 is listed as FA_SURV=cmx on night 20200219, but FA_SURV=unknown on 20200227.

I haven't checked if the old files have the same mis-match, but let's get these updated too.

Other examples (trimmed to just the first exposure of a mismatching tile per night):
```
Tile 70003 20200227 52335 FA_SURV mismatch unknown vs. cmx
Tile 70514 20200227 52388 FA_SURV mismatch unknown vs. cmx
Tile 70513 20200227 52421 FA_SURV mismatch unknown vs. cmx
Tile 70510 20200229 52798 FA_SURV mismatch unknown vs. cmx
Tile 63075 20200229 52814 FA_SURV mismatch unknown vs. cmx
Tile 70511 20200303 52926 FA_SURV mismatch unknown vs. cmx
Tile 70500 20200303 52933 FA_SURV mismatch unknown vs. cmx
Tile 70002 20200303 52962 FA_SURV mismatch unknown vs. cmx
Tile 70005 20200303 52979 FA_SURV mismatch unknown vs. cmx
Tile 70006 20200303 52994 FA_SURV mismatch unknown vs. cmx
Tile 70511 20200304 53072 FA_SURV mismatch unknown vs. cmx
Tile 63307 20200306 53741 FA_SURV mismatch unknown vs. cmx
Tile 80769 20210220 77103 FA_SURV mismatch unknown vs. cmx
```

**Comment by sbailey** [comment]
Another one: some nights have exposures with OBSTYPE=science LASTSTEP!=ignore but TILEID<0, which I think should not happen (i.e. are probably just test exposures that haven't yet been flagged as ignore).  Cases to check:
```
exposure_table_20201214.csv has negative TILEID science exposures: [67797, 67798, 67799]
exposure_table_20210113.csv has negative TILEID science exposures: [72206, 72207, 72208, 72209, 72210, 72211, 72212, 72213, 72214, 72215, 72216, 72217, 72218, 72219, 72220, 72221, 72222, 72223, 72224, 72226, 72228, 72229, 72230, 72231, 72235, 72236, 72239, 72242, 72243]
exposure_table_20210114.csv has negative TILEID science exposures: [72382, 72383, 72384, 72385, 72386, 72387, 72388, 72391, 72392, 72393, 72394, 72395, 72396, 72397, 72398, 72399, 72400, 72401, 72402, 72403, 72404, 72405, 72406]
exposure_table_20210211.csv has negative TILEID science exposures: [75279, 75280, 75282, 75284, 75285, 75286, 75288, 75290, 75291, 75293, 75301, 75303, 75304]
exposure_table_20210218.csv has negative TILEID science exposures: [76786, 76788, 76794]
exposure_table_20210219.csv has negative TILEID science exposures: [76926, 76941, 76945, 76949, 76952, 76956, 76960, 76964, 76968, 76972, 76976, 76980, 76984, 76988, 76992, 76996, 77000, 77004, 77008, 77012, 77016, 77020, 77024, 77028, 77032, 77036, 77040, 77044, 77048, 77052]
exposure_table_20210223.csv has negative TILEID science exposures: [77639, 77640, 77641, 77661, 77662, 77663, 77687, 77688, 77689]
exposure_table_20210331.csv has negative TILEID science exposures: [82808]
```

**Comment by akremin** [comment]
A quick look at the logs point to missing fiberassign files in the raw data directories explaining the first issue. The second seems to stem from no TILEID being defined in the raw data header for those exposures. I hope your assumption is correct and these are test images. I'll look in more depth tomorrow.

If you send me complete lists I can verify that every case can be explained by these two scenarios, rather than spot checks I did just now.

For the fiberassign issue -- is the official stance to use the svn as the primary and raw data directory as secondary, or vice-versa?

**Comment by djschlegel** [comment]
Those data from Feb/March 2020 might not be worth the trouble trying to support for re-reductions and release.  The state of the instrument was really variable, and we don't have the same metadata as when we returned to sky after the covid shutdown.  A description of what's supposed to be on those tiles is here: https://desi.lbl.gov/trac/wiki/SurveyValidation/miniSV2

As for which fiberassign files to use, the svn versions should take precedence.

**Comment by sbailey** [comment]
As David noted, the svn fiberassign files take precedence over the raw data ones.  During processing, assemble_fibermap does a cross check that the svn files do *not* change quantities that would have impacted observing (e.g. TARGET_RA, TARGET_DEC), but for things like SURVEY, FA_SURV, FAPRGRM the svn files are more authoritative (though I also agree with David that patching Spring 2020 data is low priority)

> A quick look at the logs point to missing fiberassign files in the raw data directories explaining the first issue. The second seems to stem from no TILEID being defined in the raw data header for those exposures. I hope your assumption is correct and these are test images. I'll look in more depth tomorrow.

> If you send me complete lists I can verify that every case can be explained by these two scenarios, rather than spot checks I did just now.

The list above is a complete list of TILEID, NIGHT; the only cases I didn't include were other exposures on the same night of the same TILEID.

**Comment by sbailey** [comment]
Looks good.  Things I independently checked:
  * all old files have a matching new file
  * all new files have the same columns in the same order
  * there can be new expids listed, but no old expids have gone missing
  * non-fatal mystery: old exposure_table_20210615.csv and exposure_table_20211206.csv were not sorted by EXPID, but now they are
  * negative TILEID for OBSTYPE=science: these appear to be missing info in the inputs, not a problem with this code per-se; issue punted to #1545 
  * These columns have not changed from old -> new: NIGHT EXPID TILEID LASTSTEP CAMWORD BADCAMWORD BADAMPS EXPTIME SEQNUM SEQTOT FA_SURV, with understood exceptions:
     * night 20201206 expid 66285 test cmx tile 80011 has new LASTSTEP=skysub instead of all
     * night 20210220 tile 80769 expids 77103 and 77106 have new FA_SURV=cmx instead of unknown
   * all entries match the reference fiberassign files in SVN for SURVEY, FA_SURV, and FAPRGRM

**Review by sbailey — APPROVED** [review]

**Pull request merged**
