### PR TITLE
QA Refactoring

### PR DESCRIPTION
**Pull request by profxj**
Lots of changes to QA_Frame and QA_Exposure
Mainly to prepare for YAML slurping at the exposure level

Example of a slurp in integration_test.
Need guidance on how to incorporate within pipeline

Passing tests on laptop (integration test too)
Failing on Travis as it requires desutils v1.4.1  (I think)

### CODE REVIEW

**Comment by tskisner** [comment]
Ok, I was just working on fixing the matplotlib backend problem and re-enabling the "qa file" options for the tools that have them.  It looks like these changes are big enough that maybe I should wait for this?  Or are these only for QA of steps that currently don't have anything?

**Comment by profxj** [comment]
I barely touched any of the figure-generating QA code
and most of the changes are pretty far below the pipeline.
So, I think you can go forth.


> On Jun 7, 2016, at 10:21 PM, Theodore Kisner <notifications@github.com> wrote:
> 
> Ok, I was just working on fixing the matplotlib backend problem and re-enabling the "qa file" options for the tools that have them. It looks like these changes are big enough that maybe I should wait for this? Or are these only for QA of steps that currently don't have anything?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/desihub/desispec/pull/210#issuecomment-224490625>, or mute the thread <https://github.com/notifications/unsubscribe/AD0BjfG2Fx4Ftauoi8ktg1vM9YDqvM25ks5qJlFygaJpZM4IwmnM>.
> 
> !DSPAM:826,5757ab7a192362393115195!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by tskisner** [comment]
Ok, sounds good.

**Comment by sbailey** [comment]
I have latest desiutil and am getting test failures like
```
======================================================================
FAIL: test_compute_sky (desispec.test.test_binscripts.TestBinScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desispec/py/desispec/test/test_binscripts.py", line 161, in test_compute_sky
    self.assertEqual(err, 0)
AssertionError: 256 != 0

======================================================================
FAIL: test_qa_exposure_load_write_data (desispec.test.test_qa.TestQA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desispec/py/desispec/test/test_qa.py", line 148, in test_qa_exposure_load_write_data
    qaexp = QA_Exposure(self.expid, self.night, 'dark', specprod_dir=self.testDir)
  File "/Users/sbailey/desi/git/desispec/py/desispec/qa/qa_exposure.py", line 51, in __init__
    self.load_qa_data()
  File "/Users/sbailey/desi/git/desispec/py/desispec/qa/qa_exposure.py", line 102, in load_qa_data
    assert getattr(qa_frame,key) == getattr(self, key)
AssertionError

======================================================================
FAIL: test_qa_frame_write_load_data (desispec.test.test_qa.TestQA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desispec/py/desispec/test/test_qa.py", line 134, in test_qa_frame_write_load_data
    qafrm2 = load_qa_frame(self.qafile_b0, frm0)
  File "/Users/sbailey/desi/git/desispec/py/desispec/io/qa.py", line 84, in load_qa_frame
    assert getattr(qaframe, key) == frame.meta[key.upper()]
AssertionError
```
Please double check that you've pushed all your changes to desiutil and desispec.  If you have, please confirm which version of python, numpy, and astropy you are using.

**Comment by sbailey** [comment]
Oddly, rerunning without any code changes worked.  re-rerunning multiple times has failed to reproduce that.  I'm not sure what went wrong.

**Pull request merged**
