### PR TITLE
Quicklook update

### PR DESCRIPTION
**Pull request by gdhungana**
This PR

- Adds sky residual from offline QA, but added median residual  per fiber
- updates the relevant PA and QL pipeline 
- cleans up some plots for clarity etc.
- replaces confusing index in sky peaks QA

Note: This version is successfully run in python 2 for full 500 spectra, but has not in python 3 yet.  Version includes python 3 fixes, and this update includes no python version specific modifications.

### CODE REVIEW

**Comment by sbailey** [comment]
These changes look fine to me, but I'd like to wait until after we merge the py3 update #266 so that we don't cause inadvertent merge conflicts that muddle the situation on that PR.  If you are making other QL changes in the meantime, please go ahead and add them to this PR.  Thanks.

**Comment by gdhungana** [comment]
@sbailey Sounds good. I don't think there will be any significant change very soon, but if we see minor changes, we will push until it is merged. Thanks.

**Comment by rkehoe** [comment]
@sbailey Slight correction.  We may have a non-negligible change soon, and 
will add to outstanding PR if it's not merged yet.

--------------------------------------------------------------------------
Robert Kehoe					      (214)768-1793 (off.)
Professor of Physics
Department of Physics				       (214)768-4095 (fax)
Southern Methodist University			     kehoe@physics.smu.edu
Dallas, TX 75275		          http://www.physics.smu.edu/kehoe

**Comment by sbailey** [comment]
Apologies for the long delay on this.  py3 is now merged into master and we could bring this in.  Your last comment was "We may have a non-negligible change soon" — is this ok to merge now, or do you have anything else you want to include first?

**Comment by rkehoe** [comment]
@sbailey   It is better to do the merge now.

**Pull request merged**
