### PR TITLE
normalize fiberflat variation of each fiber

### PR DESCRIPTION
**Pull request by julienguy**
In this PR is modified the script `desi_compute_fiberflat_vs_humidity` that generates the humidity correction templates.
The broadband flat field correction of each fiber is normalized to 1.
New templates have been generated but have not been committed yet in DESI_SPECTRO_CALIB in case we want to run a test production before. In order to test the changes at NERSC, one needs
 `export DESI_SPECTRO_CALIB=/global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib`

Comparison of current and new template for b7 , humidity bin 9 (arbitrary choice),
Screenshot from 2022-01-23 19-01-17

This PR solves issue #1615 .

### CODE REVIEW

**Comment by julienguy** [comment]
This solves an issue in the f5 spectrum of a fiber found by @rongpu  when comparing the coadds of the f5 production with everest ( ```plot_spectra -i /global/cfs/cdirs/desi/spectro/redux/f5/tiles/pernight/2175/20210514/coadd-7-2175-20210514.fits -t 39632960990741214``` )

left: cframes from f5, right: cframes with the changes to the templates from this PR.

Screenshot from 2022-01-23 19-18-30

Figures obtained with:
```
plot_frame -i /global/cfs/cdirs/desi/spectro/redux/f5/exposures/20210514/00088361/cframe-?7-00088361.fits --fiber 3779 --rebin 8
plot_frame -i /global/cfs/cdirs/desi/spectro/redux/jguy/exposures/20210514/00088361/cframe-?7-00088361.fits --fiber 3779 --rebin 8
```

**Comment by sbailey** [comment]
I have launched a miniprod using this branch[*] + Julien's DESI_SPECTRO_CALIB in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/f7 for nights
* 20210408 (a test night with some of Christophe's favorite tiles)
* 20210514 (original night that Rongpu reported problems)
* 20211215 tiles 223682,24661,7697  (night with known variable humidity)
* 20220113 tiles 21703,24233,4403,21749  (very low humidity night)

I'm re-using f5, f6, and daily calibrations and extractions, but redoing all steps after that.  This means that the prestdstar jobs still have to work their way through the queue, but once they run they go quickly because the exactions are already done.

[*] I actually made a branch of this branch and then rebased off of master to also test meta-data propagation, i.e. it is testing what we would get if we merged this branch.

**Comment by julienguy** [comment]
I looked at the tile QA compared to daily  or f5 for *some* of the tiles and always see either no change or percent level improvement in the n(z) and number of QSOs. I think this is driven by the change in the handling of the bad columns (other PR), but it looks all good to me so far.
More precisely I looked at:

comparison with daily (all better)
20211215 24661,7697
20220113 21749,4403

comparison with f5 (3 better, 3 identical n(z))
20210514 1240,1429,1433 (better), 1404,1750,1751 (same)

**Comment by sbailey** [comment]
Thanks for the quick checks.  FYI I have created the nightqa pages at https://data.desi.lbl.gov/desi/users/sjbailey/spectro/redux/f7/nightqa/

**Pull request merged**
