### PR TITLE
Fit CCD residual background between blocks of fiber traces

### PR DESCRIPTION
**Pull request by julienguy**
This PR addresses the variation from exposure to exposure of the bias in the blue cameras.

A CCD background is fit for the science exposures in the blue cameras between the blocks of fiber traces.
 - boxcar averaging in bands of 3 pixels between the 20 blocks of fibers (21 bands) (narrow band to avoid pollution by tails of cross-dispersion from bright fibers).
 - median filtering along Y = wavelength direction with a filter width of ~400 CCD pixels (to remove any residual cosmic ray, and reduce the noise).
 - linear interpolation along X for each row to obtain a background model for the whole CCD.
 - fit performed independently per amplifier

The `desi_preproc` option `--bkgsub-for-science` is set by default in `desi_proc` for blue cameras. It can be disabled with option `desi_proc --no-bkgsub`.

Example of fitted background for 20211215/00114225 b4 camera (amplitude is +-1.5 electron).

Screenshot from 2021-12-22 09-57-05

Image of sky subtracted frame sframe-b4-00114225.fits in daily prod (left) and with this PR (right).
The residual background is clearly visible on the left figure.

Screenshot from 2021-12-22 09-47-14

Same data displayed as spectra.
Daily prod:
sframe-b4-00114225-daily

This PR:
sframe-b4-00114225-jguy

This method should be probably be used only for blue cameras because we do not have bias variations from exposure to exposure in red and nir CCDs. I checked that the results were good for all 10 blue cameras of this exposure, but this method should be tested on a larger set of exposures and down to redshifts.

This PR addresses issue #1518.

### CODE REVIEW

**Comment by julienguy** [comment]
This PR could be tested on the science exposures of nights 20211211 and 20211215. The daily calibnight data could be reused for the test.

**Comment by sbailey** [comment]
I have started a production in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/ampbkg for 20211211 and 1215 for science exposures through pernight redshifts using this branch.

**Comment by julienguy** [comment]
I ran the QA on this prod
```
desi_tile_qa --outdir /global/cfs/cdirs/desi/users/jguy/ampbkg-qa/ --prod /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/ampbkg/ --nproc 16
desi_night_qa --outdir /global/cfs/cdirs/desi/users/jguy/ampbkg-qa/20211215 --prod /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/ampbkg/ --night 20211215
```
(night qa crashed for 20211211)

See
https://data.desi.lbl.gov/desi/users/jguy/ampbkg-qa/20211215/nightqa-20211215.html
to be compared with
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20211215/nightqa-20211215.html

Note that the redshift distribution of sky fibers does not show anymore an excess at z=0.25 for spectrograph 4 (blue spot for fibers ~2100).

New:
skyzfiber-20211215
Daily:
skyzfiber-20211215-daily

**Comment by julienguy** [comment]
The n(z) for 20211215 appears lower with the new run than in daily. This is to be understood.

**Comment by ashleyjross** [comment]
After selecting matching data (via targetid and coadd_numexp), the LRG redshift success on petal 4 is improved by 2%, without significant impact on other petals. See https://github.com/desihub/LSS/blob/master/Sandbox/newredux_LRGsuccess.ipynb

**Comment by sbailey** [comment]
I will take that as algorithmic performance confirmation and merge for tonight's running.  I'll postfacto review for any other code cleanup requests next week (e.g. we probably should store the interpolated locations so that we can easily check if the fit went very bad on a particular frame).

**Pull request merged**
