### PR TITLE
Ql updates

### PR DESCRIPTION
**Pull request by rkehoe**
This PR has two small updates:

- for SNR, when we have 4 targets and one does not fit, we ignore that as not indicative on its own of data quality.  So the STATUS is taken as the worst case of the remaining N-1 target types.
- the specifications on all metrics were also updated by @rstaten after further study of distributions.

### CODE REVIEW

**Comment by rkehoe** [comment]
@felipelm it looks like the specifications update that was supposed to go into this PR didn't make it.  Therefore, I will hold this PR open until @rstaten can make that update.  Once this is made into master, please use this as the basis for KPNO/NERSC setup.  Thanks very much!

**Comment by rkehoe** [comment]
Thanks for those updates @rstaten.  I think BIAS is a lost cause for the moment considering the simulations, but the rest look okay, given the statistics.

Note: one of the issues with this and recent PRs has been the issue of exactly how to set the specifications (the ranges that set the WARN and ALARM ranges) for scalar metrics.  Originally, QL only compared metrics to references taken from mergeQA files from exactly the same camera, evaluated in the same survey time (dark, grey, bright).  This allowed tight tolerances because systematic variations in metrics due to arm, survey time are avoided.  The ability to retain this level of sensitivity was reduced when we went to one science configuration and moved references to one configuration file for all cameras.  I believe this point has been raised by both @srheft and @rstaten in the fall.  So since then the specifications had to be loosed substantially.

@rstaten has done an analysis recently that moves the specifications with more rigor than has been done before and the levels are more defensible and tighter than most of the recent past.  But this study should be expanded.  And I would suggest DESI should consider moving back to the more channel-by-channel, dark-time sensitive approach.  This can be implemented without too much trouble if that judgment is made.  Once I get some of the QL documentation up related to the review, I will try to elaborate more in a ticket.

This PR is ready to merge.  @felipelm. Please use this update as the basis for the version you update to KPNO or NERSC.  @rstaten, please update to this version of master for the NERSC standalone setup and update ‘how to run on NERSC’ page accordingly.

One last note.  @julienguy has some updates that are going to alter desispect and QL data models and interfaces a bit.  In order to retain a stable, update-able version fo QL after tomorrow, I think we need to define a branch right off of master that we can build on based on whatever happens during the review and ongoing testing.  We can merge that back to master later.   I can make that branch tomorrow unless there is some objection.

**Comment by felipelm** [comment]
@rkehoe @rstaten the pipeline ended but there was a problem on arcs (for example 3571 camera r1):

```
Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.

2019-01-23 17:20:17,392 QuickLook INFO : Running ResolutionFit
  category=OptimizeWarning)
/conda/lib/python3.6/site-packages/scipy/optimize/minpack.py:785: OptimizeWarning: Covariance of the parameters could not be estimated
  res = cls._fit(xnew, y, deg, w=w, rcond=rcond, full=full)
/conda/lib/python3.6/site-packages/numpy/polynomial/_polybase.py:798: RankWarning: The fit may be poorly conditioned
  c, resids, rank, s = la.lstsq(lhs.T/scl, rhs.T, rcond)
/conda/lib/python3.6/site-packages/numpy/polynomial/legendre.py:1572: RuntimeWarning: invalid value encountered in true_divide
  rhs = rhs * w
/conda/lib/python3.6/site-packages/numpy/polynomial/legendre.py:1558: RuntimeWarning: invalid value encountered in multiply
  wt=1/ewsigmas**2
/software/qlf/0.7.0/backend/desispec/py/desispec/quicklook/arcprocess.py:56: RuntimeWarning: divide by zero encountered in true_divide
  errors=1./np.sqrt(thisivar)
/software/qlf/0.7.0/backend/desispec/py/desispec/quicklook/arcprocess.py:36: RuntimeWarning: divide by zero encountered in true_divide
  spots=thisflux/thisflux.sum()
/software/qlf/0.7.0/backend/desispec/py/desispec/quicklook/arcprocess.py:35: RuntimeWarning: invalid value encountered in true_divide
  esigmas[jj]=(pcov[1,1]**0.5)
/software/qlf/0.7.0/backend/desispec/py/desispec/quicklook/arcprocess.py:44: RuntimeWarning: invalid value encountered in double_scalars
  emeanwaves[jj]=pcov[0,0]**0.5
/software/qlf/0.7.0/backend/desispec/py/desispec/quicklook/arcprocess.py:42: RuntimeWarning: invalid value encountered in double_scalars
Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.

 7725.887 ]
 7175.9154 7247.1631 7386.014  7440.9469 7490.9335 7537.8488 7637.208
 6031.6666 6097.8506 6404.018  6440.249  6680.1205 6931.3787 7034.352
```

Many cameras actually: 

```
01-23 17:25:29 ERROR: Camera r0:  Parameter 6 was incorrect on entry to DGELSD.
2019-01-23 17:25:28 ERROR: Camera r0:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:25 ERROR: Camera z0:  Parameter 6 was incorrect on entry to DGELSD.
2019-01-23 17:25:25 CHECK ARC EXP ended (0:00:20).
2019-01-23 17:25:24 ERROR: Camera z6:  Parameter 6 was incorrect on entry to DGELSD.
2019-01-23 17:25:23 ERROR: Camera z1:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:23 ERROR: Camera r6:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:23 ERROR: Camera z5:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:22 ERROR: Camera z0:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:21 ERROR: Camera z1:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:21 ERROR: Camera z5:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:21 ERROR: Camera r3:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:20 ERROR: Camera z0:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:20 ERROR: Camera z2:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:19 CHECK FIBERS ended (0:00:34).
2019-01-23 17:25:19 ERROR: Camera z7:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:18 ERROR: Camera z6:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:16 ERROR: Camera z9:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:15 ERROR: Camera z4:  Parameter 4 was incorrect on entry to DGELSD.
2019-01-23 17:25:07 ERROR: Camera b2:  Parameter 4 was incorrect on entry to DGELSD.
```

**Comment by rkehoe** [comment]
@felipelm. Did this just happen with this PR, tests here indicated arcs were fine previously, and this modification does not impact arcs. 

I think we need to focus on the science exposures for the moment.  It is very important to install a working version on KPNO and NERSC if all else is working fine (which I think it is.)  I will need to indicate to Stephen that, at the moment, arc exposure processing isn’t reviewable.  @rstaten, we need to take a look at this asap.  Admittedly, most emphasis of late has been on science, but this processing Is also critical.  

@felipelm, can you proceed with the KPNO/NERSC install with the current version, which we update later  when the arcs are enabled?

**Comment by rkehoe** [comment]
@felipelm, @felipeaoli Just looking at this with @rstaten, this issue is being caused because some fibers do not fit properly for a given camera.  The number of failing fibers is small (eg. 2/500 for z0, or 0/500 for most cameras) and has been seen before.  The code is written such that the scalar metric is still calculated properly and the STATUS is set properly (should be NORMAL in most cases.). I can explain offline more the layout of the # of fibers in a camera to give a sense for this.

This behavior can clearly be improved with better fits, but is not an indication of a fundamental problem.  So please proceed to finalize your integration results and let us know if anything else turns up.  If not, I believe @sbailey will be very glad if KPNO/NERSC will be updated today.

**Pull request merged**
