### PR TITLE
add a new gaia standards

### PR DESCRIPTION
**Pull request by segasai**
Add new Gaia standards for the flux calibration ( see https://github.com/desihub/fiberassign/issues/304 )

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks for jumping in on this, but simply adding the names of these bits to the list to check won't work because the `GAIA_*` standards are in `(SV1_)MWS_TARGETS` column while the normal standards are in the `(sv1_)desi_target` column.  So this needs to be expanded to check both.  See the `main_cmx_or_sv` call a few lines earlier that is grabbing `(SV1_)DESI_TARGET` and `(sv1_)desi_mask` and do the same for MWS (index 2 instead of 0).  As a test of whether you are finding standards on the M31 tile:

```python
import numpy as np
from astropy.table import Table
from desispec.fluxcalibration import isStdStar

fibermap = Table.read('/global/cfs/cdirs/desi/spectro/redux/daily/preproc/20210115/00072498/fibermap-00072498.fits')
nstd = np.count_nonzero(isStdStar(fibermap)) > 0
if nstd > 0:
    print(f'Good, you found {nstd} standard stars')
else:
    print('Oops; no standard stars found')
```

Unrelated, it also looks like our interface to coveralls is broken in the github tests, but don't worry about that.

**Comment by segasai** [comment]
Thank you for the advice Stephen. I updated the branch and the test that you suggested works now. 
I wasn't quite sure whether the GAIA_WD_STD should be in bright/or faint, so I assigned them to both.

**Comment by sbailey** [comment]
Thanks.  For the record I removed GAIA_STD_WD from the list for now because we aren't fitting WD standards yet.  Merging now.  I'll rerun the failed tile 80715 exposures 20210115/72498-72500.

**Comment by segasai** [comment]
Thanks!

**Comment by sbailey** [comment]
Alas, we're not done yet.  I updated ticket #1086 with the next problem for processing these GAIA-only standards (no FLUX_G/R/Z for quality and color cuts and absolute normalization).  In the meantime, no M31 tile 80715 flux calibrations...

**Comment by segasai** [comment]
Yes, thanks. I'll take a look. It may take me a bit longer, as I dont' quite know that area of the code. 
But regarding M31, since my rvspecfit code works fine without flux calibration, we got the measurements from it (although without coadds).

**Comment by geordie666** [comment]
Obviously, the Gaia-only standards don't have fluxes from the Legacy Surveys, by definition. But, we do pass forward:
```
'GAIA_PHOT_G_MEAN_MAG', 'GAIA_PHOT_BP_MEAN_MAG', 'GAIA_PHOT_RP_MEAN_MAG'
```
(at least in the targeting files).

**Pull request merged**
