### PR TITLE
Fix memmap bug on batch nodes

### LINKED ISSUE #668: desispec.io.write_fibermap broken on interactive batch nodes
@weaverba137 can you take a look at this?

The following works on Cori login nodes but not Cori interactive batch nodes (via `salloc -N 1 -C haswell -t 01:00:00 -q interactive`):
```python
import desispec.io
fm = desispec.io.empty_fibermap(500)
desispec.io.write_fibermap('blatfoo.fits', fm)
```
This is the case for both 18.6 and 18.3, so it's not new (and I'm surprised that we haven't caught this earlier; Julien just reported it to me).

On the interactive batch nodes it gives the traceback:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-c9274a36cd80> in <module>()
----> 1 ispec.io.write_fibermap('blatfoo.fits', fm)

NameError: name 'ispec' is not defined

In [4]: desispec.io.write_fibermap('blatfoo.fits', fm)
   ...: 
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py in _free_space_check(hdulist, dirname)
    871     try:
--> 872         yield
    873     except OSError as exc:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writeto(self, fileobj, inplace, copy)
    658         with _free_space_check(self, dirname):
--> 659             self._writeto_internal(fileobj, inplace, copy)
    660 

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writeto_internal(self, fileobj, inplace, copy)
    718         elif copy:
--> 719             datsize = self._writedata_direct_copy(fileobj)
    720 

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writedata_direct_copy(self, fileobj)
    640         """
--> 641         raw = self._get_raw_data(self._data_size, 'ubyte', self._data_offset)
    642         if raw is not None:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    479         elif self._file:
--> 480             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    481         else:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    269                     memmap = Memmap(self._file, mode=MEMMAP_MODES[self.mode],
--> 270                                     dtype=np.uint8)
    271 

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/numpy/core/memmap.py in __new__(subtype, filename, dtype, mode, offset, shape, order)
    263         array_offset = offset - start
--> 264         mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
    265 

OSError: [Errno 38] Function not implemented

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-4-f864956bce5d> in <module>()
----> 1 desispec.io.write_fibermap('blatfoo.fits', fm)

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/0.22.1/lib/python3.6/site-packages/desispec-0.22.1-py3.6.egg/desispec/io/fibermap.py in write_fibermap(outfile, fibermap, header)
    130         warnings.simplefilter("ignore")
    131         write_bintable(outfile, fibermap, hdr, comments=fibermap_comments,
--> 132             extname="FIBERMAP", clobber=True)
    133 
    134     return outfile

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/0.22.1/lib/python3.6/site-packages/desispec-0.22.1-py3.6.egg/desispec/io/util.py in write_bintable(filename, data, header, comments, units, extname, clobber, primary_extname)
    210                 else :
    211                     log.debug("adding HDU {} to {}".format(extname,filename))
--> 212                     fx.append(hdu)
    213     else :
    214         log.debug("writing new file {}".format(filename))

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in __exit__(self, type, value, traceback)
    395 
    396     def __exit__(self, type, value, traceback):
--> 397         self.close()
    398 
    399     @classmethod

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in close(self, output_verify, verbose, closed)
    916             if (self._file and self._file.mode in ('append', 'update')
    917                     and not self._file.closed):
--> 918                 self.flush(output_verify=output_verify, verbose=verbose)
    919         finally:
    920             if self._file and closed and hasattr(self._file, 'close'):

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/utils/decorators.py in flush(self, output_verify, verbose)
    869             name = func.__name__
    870 
--> 871         func = make_function_with_signature(func, name=name, **wrapped_args)
    872         func = functools.update_wrapper(func, wrapped, assigned=assigned,
    873                                         updated=updated)

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py in wrapped(*args, **kwargs)
    254 
    255         try:
--> 256             func(*args, **kwargs)
    257         finally:
    258             if single_thread:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in flush(self, output_verify, verbose)
    795 
    796         elif self._file.mode == 'update':
--> 797             self._flush_update()
    798 
    799     def update_extend(self):

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _flush_update(self)
   1211             # the hdulist to the file.
   1212             if self._resize or self._file.compression:
-> 1213                 self._flush_resize()
   1214             else:
   1215                 # if not resized, update in place

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _flush_resize(self)
   1249 
   1250                 for hdu in self:
-> 1251                     hdu._writeto(hdulist._file, inplace=True, copy=True)
   1252                 if sys.platform.startswith('win'):
   1253                     # Collect a list of open mmaps to the data; this well be

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writeto(self, fileobj, inplace, copy)
    657 
    658         with _free_space_check(self, dirname):
--> 659             self._writeto_internal(fileobj, inplace, copy)
    660 
    661     def _writeto_internal(self, fileobj, inplace, copy):

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py in _free_space_check(hdulist, dirname)
    887             hdu._close()
    888 
--> 889         raise OSError(error_message + str(exc))
    890 
    891 

OSError: [Errno 38] Function not implemented
```

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

* Fixes #668.
* Adds a function to detect whether a filesystem supports memory-mapping (specifically when opening a file for update).
* Adjusts the logic of `write_bintable()` so that there are only two ways to open the output FITS file.
* Bonus: the output FITS file is only ever opened once by `write_bintable()`.
* Bonus: HDUs added by `write_bintable()` are now guaranteed to have checksums.

Note: I'd like to move the test logic in the temporary script `desi_test_bintable` into the main test suite, so don't merge this just yet.

### CODE REVIEW

**Comment by sbailey** [comment]
Do we really need to support memmap at all, or could we just open the files with memmap=False every time and not bother checking?  The current checking code has a race condition if N>1 processes are writing files to the same directory (all of them are creating and deleting the same foo.dat file...)  That could be updated, but also just becomes something to maintain when it isn't clear that we need it.  I suspect that the stochastic variability of $SCRATCH and /project performance greatly exceeds any small benefits from memmapping these particular small HDUs.  Even the check itself might exceed the benefit.

**Comment by weaverba137** [comment]
When it comes to performance issues like this, you have to tell me;  I am not the expert. If the assumption that `write_bintable()` will only ever be writing small files, for all time, is justifiable, then sure, we can skip the check.  But I am not enough of an expert to be able to justify that assumption.

**Comment by weaverba137** [comment]
Any chance of a quick re-review and merge?  Note that I went ahead and forced `memmap=False` rather than do the little check, but I left the check code in because that could be useful.

**Comment by sbailey** [comment]
Good choice.  In cases where performance is an issue, we would be using fitsio instead of write_bintable anyway, so memmap=False is fine here, but good idea to keep the checking code around in case something like this pops up again.

**Pull request merged**
