### PR TITLE
Use the functionality from desiutil in stdstars

### PR DESCRIPTION
**Pull request by segasai**

### CODE REVIEW

**Comment by julienguy** [comment]
I tried running this branch on exposure 20210130/00073720.
I ran.
```
desi_fit_stdstars --frames /global/cfs/cdirs/desi/spectro/redux/denali/exposures/20210130/00073720/frame-b0-00073720.fits /global/cfs/cdirs/desi/spectro/redux/denali/exposures/20210130/00073720/frame-r0-00073720.fits /global/cfs/cdirs/desi/spectro/redux/denali/exposures/20210130/00073720/frame-z0-00073720.fits --skymodels /global/cfs/cdirs/desi/spectro/redux/denali/exposures/20210130/00073720/sky-b0-00073720.fits /global/cfs/cdirs/desi/spectro/redux/denali/exposures/20210130/00073720/sky-r0-00073720.fits /global/cfs/cdirs/desi/spectro/redux/denali/exposures/20210130/00073720/sky-z0-00073720.fits --fiberflats /global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib/spec/sm4/fiberflatnight-b0-20201214.fits /global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib/spec/sm4/fiberflatnight-r0-20201214.fits /global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib/spec/sm4/fiberflatnight-z0-20201214.fits --starmodels /global/cfs/cdirs/desi/spectro/templates/basis_templates/v3.0/stdstar_templates_v2.2.fits --outfile ./stdstars-0-00073720.fits --delta-color 0.1
```

I then display the colors and get the following where I see a large offset we do not have when running calibrations with stars from the main survey. It would be worth checking the extinction has been applied properly to models.

Figure_1

**Comment by julienguy** [comment]
I merged master and fixed a conflict. If we think this difference of color is caused by the uncertainties on the dust transmission for high dust column density (here E(B-V)=0.6 !!) then
we may consider a mechanism to increase the color range by, say 0.2*E(B-V), to accept more stars for the flux calibration despite the mismatch between the data and model colors.

**Comment by julienguy** [comment]
I checked with this version we solve:
 - issue #1151(fit of standard stars and flux calibration)
 - issues raised in https://github.com/desihub/desispec/pull/1109#issuecomment-768823898
   - M31 tile 80715 night 20210115 exposures 72498-72500: fit of models for 27/30 std stars (0.05 mag color offset)
   - SV1 tile 80605 night 20201215 exposure 67972: 10 std stars (0.015 mag color offset)
   - CMX tile 70003 night 20200219 expid 51053: 14 stars (...)
 - also tested on one recent SV3 exposure (20210512/00088171 b0,r0,z0) (fit of standard stars and flux calibration)

**Comment by segasai** [comment]
Thanks Julien for merging and closing all the issues/PRs.

**Pull request merged**
