### PR TITLE
Update to new fibermap format

### PR DESCRIPTION
**Pull request by sbailey**
This PR is the long awaited update to the new fibermap format.  Most changes are harmless renames (`RA_TARGET` -> `TARGET_RA`), but there are two substantive changes that required algorithm updates:
* switching from `MAG[5]` to `FLUX_G`, `FLUX_R`, `FLUX_Z`, `FLUX_W1`, `FLUX_W2`
* `OBJTYPE` values are now just `TGT`, `SKY`, and `BAD`, instead of `ELG`, `LRG`, `QSO`, etc. to avoid ambiguity when a given target passes more than one cut.  Use `DESI_TARGET` and `desitarget.targetmask.desi_mask` instead.

A reference run is available at `/global/cscratch1/sd/sjbailey/desi/dev/end2end/`

Companion PRs for desisim and desitest will be submitted shortly.  I will updated issue #679 will all the fibermap column changes.

@julienguy please evaluate
* the flux calibration updates
* redshift success rates / meeting requirements
* whether you agree with the functionality tradeoffs in the caveats below

Now for the caveats:
* With sincere apologies, this breaks offline QA and quicklook due to the `OBJTYPE` change.  I'm aware that I'm breaking my own rules with this.  I tried to fix this in this branch, but other QL and desisim changes were coming in so fast that I couldn't keep up, and we ended up in a state where desitarget+fiberassign master are out of sync with desisim+desispec master for the core end-to-end integration.  Further postponing this fibermap update was becoming more and more problematic, so I suggest proceeding with this now and then fixing the broken pieces in separate smaller pull requests.
* redshift database loading is broken.  I have some updates from Ben that were working on an earlier version of this, but this branch is still broken.  Again, let's fix that as a separate smaller PR instead of postponing the core of this one.
* I'm sure that more detailed review will reveal other updates that need to be made.

### CODE REVIEW

**Comment by sbailey** [comment]
The minitest run for this branch + desisim/newfibermap-redo + master of everything else is available at: https://github.com/desihub/desitest/blob/newfibermap-redo/mini/minitest.ipynb .  A few things to note there:
* ELG global redshift efficiency has dropped, but I think that is due to the newer mocks having fainter ELGs.  The offline with-truth QA with [OII] flux cuts still reports excellent redshift success.  Other classes still have good redshift success.
* database loading and offline no-truth QA are broken as previously noted.
* there is an odd gap in the QSO tracer redshift distribution; I think that is a separate issue with mocks / target selection and unreleased to these PRs.

**Comment by sbailey** [comment]
Oops: output files have both `LAMBDAREF` and `LAMBDA_REF`

**Comment by julienguy** [comment]
Notes on flux calibration
 - I checked the calibration vectors are similar to those of the redwood prod (so no big issue).
 - I note you do not redden the stellar models prior to the fit, I am not sure why. It seems to me to be less accurate. Given the fact the median filtering continuum subtraction is not perfect, I perform twice the calibration to avoid the median filtering potential bias. Not applying the dust extinction to the model prior to the fit removes some of the benefit of this.
 - We may merge this PR as is for the sake of efficiency, given it addresses so many other issues, but we should then open a ticket to deal with this later.

**Comment by julienguy** [comment]
Will need to update desi_zcatalog --match option to collect the information from the truth present in the various HDUs ...

**Comment by julienguy** [comment]
Commenting on my previous comment. Not applying extinction to the stellar models prior to the fit is probably not an issue at all, because the second fit, which includes a first estimation of the calibration, will absorb this extinction.

**Comment by julienguy** [comment]
The ELG redshift efficiency is similar to redwood.
elg-eff

**Comment by sbailey** [comment]
@weaverba137 can you tell what is wrong with sphinx for this PR?  Thanks.

**Pull request merged**
