### PR TITLE
Ql update QAs

### PR DESCRIPTION
**Pull request by Srheft**
This PR addresses:

1 - Removing Sky_Resid calculation from the algorithm as was agreed upon a long while ago.
2 - The option to get the parameters and ranges from within the code [in case config files did not provide them] is now removed.  QL now crashes with the message: log.critical ("No parameter is found for this QA")
3 - XWSigma to be more robust against fitting failures [reducing the number of lines]
4- QL now gets the reference values from the configuration files 

Some other minor fixes are included as well.

### CODE REVIEW

**Comment by rkehoe** [comment]
@srheft. This PR looks fine to me.  The updates for the references from the configuration file, and to bolster XWSigma stability directly relate to requests from MockObserving.  I have not worked thru all the updates in qas.py, but otherwise the changes are pretty straightforward.  Here are a few comments/observations:

- the XWSigma simplification helps.  From what I’ve seen from results from @rstaten, the blue spectra cannot be counted on to always have a good enough line for this fit.  So there may be a need to just require a certain number of fibers give a fit, rather than all of them.  This can be done in a next iteration if needed.

- for skyresid, I would suggest we not comment out or remove the ability to run this or include it in the testing.  Because QL allows QAs to be turned off and on, it would be best to where this is tested to the configuration if possible.  Although it has been decided to omit this QA for now, I can imagine that this might be revisited in commissioning.  Or we might want to use it in testing the sky subtraction algorithms, even if it is not a default QA run in science running.  I suspect at least 1 or 2 other QAs might be ‘off’ by default in this way, but available for testing later.  Can you include this in. Test_ql_qa.py still?

- thanks for removing the old hardcoded, default PARAMS.  I think you can delete those commented lines, too.  I’m glad this PR now uses general error handling to end execution here.  There still appear to be a few places where ‘qlexception’ is used instead of sys.exit or similar.  We should determine if there is any virtue to retaining qlexception, or just convert these remaining cases to the more general usage (eg. At lines 483, 584 and elsewhere of qa_quicklook.py)

- Good also to see.a more rgularlized usage for metric naming across the board.  I may have misinterpreted, and wasn’t able to determine if it affected execution, but there is at least one place where the older ‘Check_HDUs’ string is used instead of the newer CHECKHDUS.  Does that need to be updated?
 
Aside from the last one, if it matters, I don’t think these should hold up this PR.

**Comment by sbailey** [comment]
The Travis test failures are odd: they are failing to load fitsio, but that is from code that has been in the repo for 7 months and the log indicates that fitsio was installed without error as part of the initial configuration.  I've restarted the test in case the problem was a transient corruption.  If it continues to fail we may need to pull in @weaverba137 to investigate what the problem is.

**Comment by weaverba137** [comment]
See https://github.com/desihub/desitarget/pull/364#issuecomment-418748296 and conda/conda#7734.

**Comment by sbailey** [comment]
It looks like the conda/fitsio bug isn't fixed, but that is completely independent of this PR itself, so don't let that be a blocking factor for merging this as long as tests pass elsewhere with a correct fitsio installation (e.g. laptop, NERSC).

Will this PR require updates on the QLF side?

**Comment by Srheft** [comment]
Yes, I am updating data model and then I will ping the QLF folks to test the PR.

**Comment by Srheft** [comment]
@felipelm please test this PR and address all the executive issues here. The changes to the configuration files are in accord with what was requested during the MockObs week. 
The running command is the same as before:

**desi_quicklook -i config_files/qlconfig_darksurvey.yaml -n 20191001 -c r1 -e 3577 **

if **--plots** is added/removed at the end, all/no static plots get created. 

In inquiries, please include the exposure and camera that is being tested.

Quicklook checks the configuration filename internally and crashes if wrong configuration file is being used. 

This PR won't be merged until it is confirmed that it does not break the interface. Note the above comments about the non-algorithmic Travis build failures.  The local machines via which this PR is created and tested have not have any python package update since the mockobs week. 

@felipeaoli : The data model is updated through the PR#60 [to be merged shortly] in **desihub/desidatamodel**.  Please note that two new QAs for evaluating arc and flat exposures are added each of which have an individual json file called : 
**ql-checkres-{camera}-{expid}.json**
**ql-checkfibflat-{camera}-{expid}.json**

As mentioned in the original PR comment, sky_resid is no longer being calculated thus  **ql-skyresid-{camera}-{expid}.json** won't get created and none of its keys will exist in the merged json file. 

All QAs and their STATUS keys have consistent naming convention of QAname and QAname_STATUS and QAname_REF and  QAname_NORMAL_RANGE and QAname_WARN_RANGE.

**ql-trace-{camera}-{expid}.json** is also being created but its QA is currently empty hence the STATUS for it always comes as 'ALARM' until XYSHIFTS key is  no longer empty. 

If a more interactive and faster Q&A was felt necessary for clarification, please use ql-qlf-chatter channel on Slack.

**Comment by felipelm** [comment]
Hi @Srheft nice to see you back! 

Today is Brazil independence day and I'm also doing nersc spin course so I'll only be able to test the PR changes next week. I'll try to do it as soon as possible.

Thanks

**Comment by Srheft** [comment]
Hi @felipelm: I was around :). Over the past few weeks, QL had to consider some algorithmic tailoring internally with Julien/Stephen's suggestions after the mock obs week; hence the gap in QL-QLF exchanges. I also watched and rated a show.  

Thanks for putting priority on this and I hope there won't be many blocking factors for a smooth run. 

Happy independence day!

**Comment by felipelm** [comment]
Hello @Srheft I got an error starting the pipeline while loading the calibration files:

```shell
2018-09-10 12:15:07 Process 1153 aborted.
2018-09-10 12:15:06 ERROR: Camera r4: File does not exist: /app/spectro/calibration/SIM/fiberflat-r4.fits
2018-09-10 12:15:05 ERROR: Camera r3: File does not exist: /app/spectro/calibration/SIM/fiberflat-r3.fits
2018-09-10 12:15:03 ERROR: Camera r2: File does not exist: /app/spectro/calibration/SIM/fiberflat-r2.fits
2018-09-10 12:15:02 ERROR: Camera r1: File does not exist: /app/spectro/calibration/SIM/fiberflat-r1.fits
2018-09-10 12:15:00 ERROR: Camera r0: File does not exist: /app/spectro/calibration/SIM/fiberflat-r0.fits
2018-09-10 12:14:59 ERROR: Camera b9: File does not exist: /app/spectro/calibration/SIM/fiberflat-b9.fits
2018-09-10 12:14:57 ERROR: Camera b8: File does not exist: /app/spectro/calibration/SIM/fiberflat-b8.fits
2018-09-10 12:14:55 ERROR: Camera b7: File does not exist: /app/spectro/calibration/SIM/fiberflat-b7.fits
2018-09-10 12:14:54 ERROR: Camera b6: File does not exist: /app/spectro/calibration/SIM/fiberflat-b6.fits
2018-09-10 12:14:52 ERROR: Camera b5: File does not exist: /app/spectro/calibration/SIM/fiberflat-b5.fits
2018-09-10 12:14:50 ERROR: Camera b4: File does not exist: /app/spectro/calibration/SIM/fiberflat-b4.fits
2018-09-10 12:14:49 ERROR: Camera b3: File does not exist: /app/spectro/calibration/SIM/fiberflat-b3.fits
2018-09-10 12:14:47 ERROR: Camera b2: File does not exist: /app/spectro/calibration/SIM/fiberflat-b2.fits
2018-09-10 12:14:46 ERROR: Camera b1: File does not exist: /app/spectro/calibration/SIM/fiberflat-b1.fits
2018-09-10 12:14:44 ERROR: Camera b0: File does not exist: /app/spectro/calibration/SIM/fiberflat-b0.fits
2018-09-10 12:14:37 Exposure 3905 started.
```

Before `fiberflat` files were at `/app/spectro/calibration/` and now this `SIM` was added. I couldn't find the change that made this happen do you have any clue?

**Comment by felipelm** [comment]
One more thing could you revert this change so we can stop generating a `.lock` file every time we run ql:

https://github.com/desihub/desispec/commit/570b2e54946f3f4edcba7e19a88e784a16ce20d8#diff-3620b755182defb2a1bb8033b6d9e1b5

This was a change we made during mockobs trying to solve the problem that for each run we couldn't read the config file for one or two cameras. Maybe @rstaten remembers it.

This problem is still not fixed at `desi-1` I think

**Comment by Srheft** [comment]
@felipelm see qlconfig.py for the changes... note the commented section above the added lines as I saw you did not have them.

As for calibration file location in the system, this is the current status of where QL finds them:

The env. var  **DESI_CCD_CALIBRATION_DATA**  points to **$HOME/desi/ccd_calibration_data**
it could point to **$HOME/desi/ccd_calibration_data/SIM** so that the rest of the address [i.e. the SIM subdirectory] wouldn't need to be hardcoded; nevertheless, the calibration files were put in SIM directory and were pointed to us to use.  

As QL has no preference for the location, I'm adding @julienguy and @sbailey here for further comments if this was not helpful.

**Comment by sbailey** [comment]
QL should use code like this to determine which fiberflat and psf to use:

```python
    from desispec.preproc import read_ccd_calibration
    calibration_data = read_ccd_calibration(raw_data_ccd_header, raw_data_primary_header)
    psffilename = os.path.join(os.environ["DESI_CCD_CALIBRATION_DATA"],calibration_data["PSF"])
```

Under the hood, `read_ccd_calibration` uses `ccd_calibration.yaml` to determine which fiberflat / psf should be used for that exposure given the header keywords.  When we update the calibration files, we update `ccd_calibration.yaml` and then the code will automagically use the new calibrations without requiring a new code tag.  e.g. simulated data will be directed to simulated PSFs, and real data will be pointed to PSFs derived from real data.

i.e. QL should *not* reference anything about a `SIM/` directory or even `ccd_calibration.yaml` itself.  As long as the svn repo `ccd_calibration_data` is checked out into a directory that the QLF docker container can mount and set `$DESI_CCD_CALIBRATION_DATA` to that location, the above recipe should work for both sim data and eventually real data (if not, let me know and we'll sort out what the correct instructions should be).

**Comment by Srheft** [comment]
@sbailey : Thanks for yet another reminder. QL does not include any hardcoded address. There was one quick debugging fix few hours ago that is now in accord with the general rule of not hardcoding any address.

**Comment by felipelm** [comment]
@Srheft I'm still getting the same error using the latest changes and maybe you need to send me a new `ccd_calibration.yaml` file according to what @sbailey said. The one I have here contains the path `SIM` for fiberflats.

```yaml
...
b1:
  V1:
   AMPLIFIERS: ABCD
...
  SIM:
      AMPLIFIERS: '1234'      
      DATE-OBS-BEGIN: '19000101'
      DATE-OBS-END: None  
      DOSVER: SIM
      FEEVER: SIM
      DETECTOR: SIM 
      PSF: SIM/psf-b1.fits
      FIBERFLAT: SIM/fiberflat-b1.fits <<<<<<<<<<<<<<<<<<<<<<<<<<<
...
```

**Comment by felipelm** [comment]
@Srheft ql ran now but got an error

Command:
```
desi_quicklook -i /app/desispec/py/desispec/data/quicklook/qlconfig_graysurvey.yaml -n 20191017 -c b0 -e 3905 --rawdata_dir /app/spectro/data --specprod_dir /app/spectro/redux
```
Error:
```
Failed to run PA SkySub_QL
cholesky failed, trying svd in iteration 0
iter 0 solving
iter 0 fiber 40
iter 0 fiber 30
iter 0 fiber 20
iter 0 fiber 10
iter 0 fiber 0
numpy.linalg.linalg.LinAlgError: Arrays cannot be empty
    raise LinAlgError("Arrays cannot be empty")
  File "/conda/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 225, in _assertNoEmpty2d
    _assertNoEmpty2d(a, b)  # TODO: relax this constraint
  File "/conda/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1978, in lstsq
    skyflux[w]=np.linalg.lstsq(A_pos_def,B[w])[0]
  File "/app/desispec/py/desispec/quicklook/quicksky.py", line 87, in compute_sky
    skymodel=compute_sky(input_frame,fibermap,apply_resolution=apply_resolution)
  File "/app/desispec/py/desispec/quicklook/procalgs.py", line 756, in run
    return self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/quicklook/pas.py", line 18, in __call__
    inp=pa(inp,**pargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 285, in runpipeline
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

_flapack.error: (shape(c,0)==shape(b,0)) failed for 2nd argument b
    x, info = potrs(c, b1, lower=lower, overwrite_b=overwrite_b)
  File "/conda/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 187, in cho_solve
    X = scipy.linalg.cho_solve((UorL,lower),B)
  File "/app/desispec/py/desispec/linalg.py", line 28, in cholesky_solve
    skyflux[w]=cholesky_solve(A_pos_def,B[w])
  File "/app/desispec/py/desispec/quicklook/quicksky.py", line 84, in compute_sky
Traceback (most recent call last):
2018-09-11 17:53:12,714 QuickLook CRITICAL : Failed to run PA SkySub_QL error was Arrays cannot be empty
  w = A.diagonal()>0
/app/desispec/py/desispec/quicklook/quicksky.py:79: RuntimeWarning: invalid value encountered in greater
2018-09-11 17:53:12,015 QuickLook INFO : Running SkySub_QL
```

**Comment by Srheft** [comment]
@felipelm:
* Could you please give us the equivalent exposure number in the night 20191001 so that we run on the same exact exposure? 
* If you have had successful run on flat and arc exposures, could you please include a screen shot of the interface for documentation and public view here?
* I heard that the exposure generator in qlf changes the exposure number for qlf such that although the only night that contains new format fits file and fibermaps is called 20191001,  QLF has it as 20191017. Is this correct?

**Comment by felipelm** [comment]
@Srheft 

> Could you please give us the equivalent exposure number in the night 20191001 so that we run on the same exact exposure?

Ran exposure 3578 night 20191001 same error.
```
desi_quicklook -i /app/desispec/py/desispec/data/quicklook//qlconfig_darksurvey.yaml -n 20191001 -c b0 -e 3578 --rawdata_dir /app/spectro/data --specprod_dir /app/spectro/redux
```

> If you have had successful run on flat and arc exposures, could you please include a screen shot of the interface for documentation and public view here?

image

> I heard that the exposure generator in qlf changes the exposure number for qlf such that although the only night that contains new format fits file and fibermaps is called 20191001, QLF has it as 20191017. Is this correct?

We removed the exposure generator so the values appearing are the correct ones.

I'm coordinating with @daqiii to make a deployment on desi-1 so we debug more productively. I'll let you know when is ready.

**Comment by felipelm** [comment]
@Srheft qlf is online now on `desi-1`

http://desi-1.kpno.noao.edu:9001/

If can please test on `/software/qlf/master/backend/desispec`, inside the container using `docker exec -it backend_qlf_1 bash` and send me your tests and results would be great.

I'm going to try your tests later today.

**Comment by felipelm** [comment]
@Srheft about the summary pages is the file called `QL_SummaryPages`?

If it is can you please explain the tables?

**Comment by Srheft** [comment]
Hi @felipelm:  Finally gained access to desi-1 again. Taking the steps below, I see the same view as the snapshot you included. SkuSub_QL is failing for all cameras in QLF. Will try to debug from within QLF. Is is OK to do that? I won't be committing the changes obviously. Thanks for the new colouring and the table that explains them.  For documentation, here are the steps I took:

1- login to desi-1
2- cd /software/qlf/master/backend/desispec
3- docker exec -it backend_qlf_1 bash
4- ./run.sh
5- in web browser go to  http://desi-1.kpno.noao.edu:9001/
6- ln -s /data/quicklook/staging/raw/20191001/0003574 00003574
7- observed that /software/qlf/master/backend/docker-compose.yml lists all cams 
8- reset the monitor and start processing the flat exposure 00003574. 

Here is screenshot of what I see. only one petal is done. It's nice that the log says what step is done but 

 * how does user know that it is done?
* is the a step I'm missing above? why the rest of the petals are not showing up?

**Comment by sbailey** [comment]
Providing a more high level commentary to summarize the details that @Srheft listed:

One of my QLF feedback requests after mock observing ([July 13 2018 to desi-data, "QLF WebApp Feedback"](https://desi.lbl.gov/trac/tracmailman/browser/private/desi-data/2018-July/003655.html)) was:

> * Group pie charts by what is being tested instead of what pipeline step produced the QA result.
>   * **Sarah**: can you provide the mapping of which QAs shoudl be grouped into Check CCDs / Check Fibers / Check Spectra?  I'd include the 0th order "Check HDUs" as part of Check CCDs.

Sarah's spreadsheet provided that mapping of what QA metrics should go with each of those CCDs/Fibers/Spectra groups.  i.e. I'd like to see this QLF view updated so that instead of being grouped by 4 pipeline steps, it is grouped sets of physical things that are being checked (CCDs, fibers, spectra):

screen shot 2018-09-14 at 10 08 32 am

@felipem does that make sense?  If not, let's arrange a phone call to try to describe this.

**Comment by felipem** [comment]
Looks like you meant to notify @felipelm instead of me

**Comment by felipelm** [comment]
@Srheft the log bellow the steps from your screenshot shows errors on all the cameras and if you click on the stage lines where a tool tip (ex. `Camera r3`) appears you can see the complete error from desispec output.

I finally understood the table. Thanks for the explanation! 

This will be a pretty big change for us so I'll discuss with the rest of the team the best way to approach it.

The coloring was a problem on our master that I just fixed but unfortunately I deployed yesterday. I tried to login to desi-1 but my vpn is not working today. 

I'll try again on monday but feel free to use desi-1 to debug ql looking at the complete camera logs like I described above.

**Comment by Srheft** [comment]
@felipelm OK thank you for the tip and I understand that the suggested changes impose a workload that needs to be discussed. 

Would I be interrupting your work on desi-1 if I start or stop and change exposures on desi-1?  I typically connect to desi-1 after midnight [your local time]. 
 For cam b0 of flat exposure 3574, one issue was no colouring of the first pi-chart [the QAs for step1 allcame out as Normal for b0 but the step1 pi-chart wasn't coloured].

Also would be great if you have qlf to look for **qlconfig_arc.yaml** in /software/qlf/master/backend/desispec/data/quicklook so that I could verify the process of that exposure as well. Thanks.

**Comment by Srheft** [comment]
@sbailey does the screenshot you shared refer to a recent run on this PR? master?

**Comment by sbailey** [comment]
@Srheft that screenshot was taken from QLF running on desi-1 this morning.  I don't know what version of QLF or desispec/QL that corresponds to.

**Comment by Srheft** [comment]
@sbailey could you confirm that these are all the steps you took?

1- login to desi-1
2- cd /software/qlf/master/backend/desispec
3- docker exec -it backend_qlf_1 bash
4- ./run.sh
5- in web browser go to http://desi-1.kpno.noao.edu:9001/
6- ln -s /data/quicklook/staging/raw/20191001/0003574 00003578
7- checked that /software/qlf/master/backend/docker-compose.yml lists all cams
8- reset the monitor and start processing the science exposure 00003578.

**Comment by sbailey** [comment]
@Srheft no, I just went to http://desi-1.kpno.noao.edu:9001/ and took a screenshot of what I found there thinking it was the latest available.  I didn't run QLF myself or restart any processing etc.

**Comment by Srheft** [comment]
@felipelm 
The errors you were referring to in the screen shot I included are referreing to the failures of the science frame 3578. What I tried was the exposure 3574 that is a flat exposure. Clicking on b0 log. Shows that the merged Json file for exposure 3574  was successfully created. All QAs showed as NORMAL. See the log below:



* Could you help me understand this:
@sbailey took his screenshot of desi-1 host this morning while my screenshot if for 12 hours before this morning and at that time I had removed the exposure 00003578 and replaced 0003574 in the staging area of desi-1. So how come the bowser was still showing the result of 00003578 this morning?

**Comment by felipelm** [comment]
@Srheft the cameras were processed but it didn't update the stages. This was that issue I commented before.

I emailed Sue Hayes and Bob Marshall today to verify the VPN connection because it's still not working for me.

@sbailey yes we understood now this layout change and will discuss the best approach today with the team.

**Comment by sbailey** [comment]
@Srheft I currently see exposures 3571 (arc), 3574 (flat), and 3577 and 3578 (science) in the QLF observing history on desi-1.  All of them raised QL alarms.  When people are actively using desi-1 for debugging QL/F, I wouldn't be surprised to see individual exposures coming and going so it shouldn't matter which exposure I chose as the screen shot to make the point about regrouping the pie charts, which I believe is unrelated to this PR itself (please move that discussion to a new issue when it continues).

What is the status of getting QLF working with this branch?  It is concerning that this is taking many days, and it is unclear to me what the blocking factor is.

**Comment by felipelm** [comment]
@Srheft you can use desi-1 to debug ql however you are going to see a lot of errors due to the changes desispec had. For instance, you are going to see QAs not showing inside the petals because of the key name changes made in the logs.

All of our implementation was made considering `science` flavor exposures.

**Comment by Srheft** [comment]
@sbailey 
Yes. It could be only surprising if I was the only person having vpn connection to change the existing exposures in the staging area.  That was my impression for the last 2-3 days. 
Please copy the log section for arc[3571] and flat [3574] run where you see a process failure. 
For arc processing, it says that qlfconfig_arcs.yaml doesn't exist which is correct because it should look for qlconfig_arc.yaml. for flat processing. I don't see the failure so please copy that here. For science processing, I make a commit that should take care of it.

**Comment by Srheft** [comment]
@felipelm 
OK. Thanks. All I like to verify is that this PR is not creating a major problem for qlf [the new naming grouping and step changes aside]. 

* The name of configuration file for arc is now **qlconfig_arc.yaml** but before it was **qlconfig_arcs.yaml**.  Could you make that change in the name of the code so that qlf looks for the correct name?

*  There were mismatching names for QAs and their status key that you mentioned in an email a while ago. That is fixed in this PR too. I wanted qlf to verify that that issue no longer exists. 

* The REF keys are being given in the configuration files. So we no longer look at the JSON file of the first exposure of the night to compare the measurements. Now petals could/should get green from the beginning [if the alarm issue]. 

These are the most prominent changes that could cause confusion for the interface. As soon as you can remotely see that  these chanes are digestible, we can go on and merge this PR. Ofcourse making all the changes take some time. I just wanted QLF to be informed about all the changes that QL makes and when finds necessary, have QL to take a pause before merging further developments.

**Comment by Srheft** [comment]
@felipelm 

Please test a science exposure in qlf with all the recent changes applied at your earliest convenience and report the problems here.  Please note my last comment as well. Thanks.

**Comment by sbailey** [comment]
@srheft please succinctly re-summarize all changes needed in QLF for it to work with this branch — e.g. changed config file names, config file formats, environment variables, which output keys changed name.  The information may be in the above thread or other emails and slack conversations, but it is hard to disentangle what is required *now* vs. what was a description for future updates (e.g. regrouping how the QAs map into the pie charts).

Please do not merge this PR until there is a matching working version of QLF that has been run with this for arc + flat + several science exposures.  If you can make the QLF changes and submit a PR for that, great.  Thanks.

**Comment by Srheft** [comment]
See [PR#225](https://github.com/desihub/qlf/pull/225).

**Comment by sbailey** [comment]
Travis test failures were for reasons unrelated to this PR, though I'm surprised we haven't seen them before.  It appears that we are getting a random ordering of `ndarray.dtype.names`, similar to how the order of `dict.keys()` is undefined.  I updated the tests to compare `assertEqual(sorted(table1.dtype.names), sorted(table2.dtype.names))` instead of the unsorted names.

**Comment by felipelm** [comment]
@Srheft @sbailey I'm not sure where should I reply because there are three pull requests, one here and two in qlf, about this change. Also there is a new issue on qlf and messages coming from slack and emails. Can we agree in one place to communicate?

This week is being pretty hectic for me so I will only be 100% on qlf next week but I manage to fix the permission problem on desi-1 with this branch latest changes. All in the directory `/software/qlf/master`.

If you want to enter the container now you have to run this command:

```
docker exec -it master_app_1 bash
```

**Comment by Srheft** [comment]
Thank you for the fix on desi-1 @felipelm. I understand the difficulties and appreciate squeezing this into your busy schedule of this week. desi-1 permission issues are rather general and irrelevant to this PR and that's why I communicated the permission errors on slack.  If you prefer to only look at one place, then github is the one to go. I have no preference on where to look and will check all the outlets but in the case of of multiple PRs, keeping comments to specific PRs in their own comment areas and referencing them if needed, probably serves us best for documentation. Thanks again.

**Comment by felipelm** [comment]
There is one problem I just noticed. The merged_qa output does not match the doc https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/QuicklookQAOutputs/Science

For instance, Calc_XWSigma was supposed to be in Check CCDs but is in Check Fibers. Also XYSHIFTS has its own task FLEXURE and following the same document should be in Check Fibers.

I'm not sure how to proceed here.

**Comment by Srheft** [comment]
Hi @felipelm 
I see that the wiki says that XWSigma is in check CCDs.  and XYSHIFTS has to be in check fibers. I'll make a commit to merger.py to have that there. Please proceed with the wiki. Thanks.

**Comment by felipelm** [comment]
@Srheft Here is a list of missing params that we detected:

**Science**

CHECK_CCDs
- CHECKHDUS_STATUS
- XWSIGMA_STATUS

CHECK_FIBERS
- XYSHIFTS_STATUS

**Arc**

CHECK_CCDs
- CHECKHDUS_STATUS

CHECK_FIBERS
- XYSHIFTS_STATUS

CHECK_ARC (Not found. Seems to be RESOLUTIONFIT correct?)
- CHECKARC_STATUS

**Flat**

CHECK_CCDs
- CHECKHDUS_STATUS

CHECK_FIBERS
- XYSHIFTS_STATUS

CHECK_FIBERFLAT (Not found. Seems to be COMPUTEFIBERFLAT_QL correct?)
- CHECKFLAT_STATUS

**Comment by Srheft** [comment]
@felipelm 
You are only talking about the merged json. 
* The individual jsons for arcs and flats and sciences do not have a missing key.
 Also the status key of all the keys that you mentioned are being written in screen log upon QL execution and they exist in the individual josns. 
* QLF was using individual jsons and continues to need the individual josns, correct?

**Comment by felipelm** [comment]
@Srheft no we are not using individual jsons just the mergedQa

**Comment by Srheft** [comment]
@felipelm 

> no we are not using individual jsons just the mergedQa

So shall QL drop creation of single JSONs or there are still some reservations/considerations on this?

**Comment by felipelm** [comment]
> So shall QL drop creation of single JSONs or there are still some reservations/considerations on this?

Feel free to do it we are not using them anymore.

**Comment by felipelm** [comment]
@Srheft arc and flat are ok after your change just XWSIGMA is still in CHECK_FIBERS on science

**Comment by felipelm** [comment]
All good now 👍

**Comment by Srheft** [comment]
Can you checkout the permission issue for creating the links in the attic on desi-1. i used to be able to do it but now I get permission error.

**Comment by felipelm** [comment]
Permission issue in the attic? 

I'm not sure what you are trying to do but if you want to trigger an exposure process you should create a link from `/data/quicklook/staging/raw/` to `/data/quicklook/exposures/raw/`

**Comment by rkehoe** [comment]
@srheft. I have gone back through all the changes and comments.  This PR now accomplishes several things in addition to your Sep. 2 comments.  It is worth noting that the improvements to both XWSigma and SNR QAs now effectively remove the problems with ALARM status due to somewhat less-than robust algorithms or fits.  That satisfies an important post-Mock Observing goal, and should enable users to more usefully familiarize themselves with QuickLook when they use it.

My comments on this PR are much like on Sep. 2.  It looks like it is ready to merge, particularly now that QL and QLF are in-synchronized again.  The additional work on the two QAs is important to get in.  Thanks also to @rstaten for his contributions here.  There is further simplification, and it would be good to see further migration to a common ‘science’ configuration, instead of still having three separate ones.  But that isn’t a priority for this PR and I hope you can merge this soon to get included into the intended desispec 18.9 tag.

Travis tests completed successfully.  I have some comments or questions remaining for future branches, and I would appreciate not deleting the branch after merge, at least for the near-term.   But I would encourage merging this PR once all QL/F testing is done.

**Comment by Srheft** [comment]
@rkehoe 
PRs would benefit from timely reviews. Hope the comments won't come much after the fact in the future. XWSigma will go through another update and also will be added to arcs. 

Merged.

**Comment by rkehoe** [comment]
@srheft. Glad you merged.  For records sake, my comment yesterday had a typo — I was referring to ‘my’ comments Sep. 2nd, when I had initially responded to the PR promptly.  I agree such prompt comments like that are important.  Sorry my comment yesterday mistakenly suggested they were late.

**Pull request merged**
