### PR TITLE
bootstrap: Unit tests

### PR DESCRIPTION
**Pull request by profxj**
Added a set of unit tests.

These pull two ~6Mb files from NERSC with urllib2

The test is failing on Travis, but I believe that is due to 
a stale desiutils integration.  
Works fine on my laptop.

### CODE REVIEW

**Comment by weaverba137** [comment]
Looks like you are basing your tests on a non-tagged version of desiutil.

```
ImportError: cannot import name funcfits
```

**Comment by profxj** [comment]
I’m sure you are correct.  

How is this properly rectified?

X

> On Dec 9, 2015, at 10:57 AM, Benjamin Alan Weaver <notifications@github.com> wrote:
> 
> Looks like you are basing your tests on a non-tagged version of desiutil.
> 
> ImportError: cannot import name funcfits
> —
> Reply to this email directly or view it on GitHub <https://github.com/desihub/desispec/pull/103#issuecomment-163357221>.
> 
> !DSPAM:826,566879a225219243494547!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/xastropy/xastropy
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by weaverba137** [comment]
Whoever is responsible for the addition of the funcfits module to desiutil needs to sign off on it and cut a tag.

**Comment by profxj** [comment]
merging (with SB's approval).

**Pull request merged**
