### PR TITLE
QL SNR Fitting and Evaluation at Fiducial Magnitude

### PR DESCRIPTION
**Pull request by rkehoe**
@kdawson and @afausti   This PR incorporates several changes, primarily centered around the 
SNR calculation at fiducial magnitudes, and the evaluation of scalar metrics.  Specifically:

- added SNRFit method simplifying SingalVsNoise and fitting SNR vs. Mag.
- evaluate SNR fit function and configured fiducial magnitudes per target type
- evaluate ELG fiducial SNR scalar metric based on configured settings
- reimplement SNR errors
- add LRG fibers to unit test
- change SNR vs. Mag. fit to polynomial

Additional updates outside of the SNR QA include:

- add RA/Dec to metrics for all QAs
- add rms per row in overscan region for full frame (not just in per amp metrics)
- add WARN/ALARM scalar metric check for all QAs
- several fixes, particularly to XWSigma QA

Please take a look and indicate if it can be merged.

### CODE REVIEW

**Comment by afausti** [comment]
Hi @rkehoe I have tested this branch with QLF using the 20190101 data set and configuration file pointed by @rstaten. It processed a couple of cameras with success.

In the `ql-snr-b0-00000003.yaml` QA output I see the fit results, for example:

```
ELG_FIDMAG_SNR: 0.8052432917473807
  ELG_FITRESULTS:
  - [23.160011166086893, -1.7345164992000806, 0.03079603085090494]
  - - [19.479857234735896, -1.7535452348455984, 0.03942744942380513]
    - [-1.7535452348457106, 0.15788130779474002, -0.0035505425461742203]
    - [0.03942744942381015, -0.003550542546174447, 7.986215885726216e-05]
```

My understanting is that the `ELG_FIDMAG_SNR` is the actual measurement I have to compare against the specifications. Fine.


Then in the QL configuration file I see the SNR specifications:

```
Calculate_SNR:
                PARAMS: {FIDSNR_WARN_RANGE: [6.5, 7.5], FIDSNR_ALARM_RANGE: [6.0, 8.0], FIDMAG: 22.} 
```

which are also passed to the QA ouput.

```
PARAMS:
  FIDMAG: 22.0
  FIDSNR_ALARM_RANGE: [6.0, 8.0]
  FIDSNR_WARN_RANGE: [6.5, 7.5]
```

Fine. I can use that to test the SNR metric. 

I don't have much sense of the SNR values for each target type. Currently, in the outputs we have:

```
ELG_FIDMAG_SNR: 0.8052432917473807
LRG_FIDMAG_SNR: 0.14291024673744201
QSO_FIDMAG_SNR: 1.1337593647276047
STAR_FIDMAG_SNR: 1.2350664804055764
```

which seems preatty close, but perhaps in the future we'll need a different SNR specification for each target type. Let @kdawson comment on that. 

Now looking at the outputs 
````
 ELG_FITRESULTS:
  - [23.160011166086893, -1.7345164992000806, 0.03079603085090494]
  - - [19.479857234735896, -1.7535452348455984, 0.03942744942380513]
    - [-1.7535452348457106, 0.15788130779474002, -0.0035505425461742203]
    - [0.03942744942381015, -0.003550542546174447, 7.986215885726216e-05]
```

I imagine those are the parameters of the fit.  I tried to understand their meaning looking at the code, but I couldn't. Is this documented somewhere else? could we use a dictionary to make this more evident?

I ask that because QLF will need the fit parameters to draw the fit curve in the SNR vs. Mag plots.

**Comment by rkehoe** [comment]
Thank you @afausti for your comments.  Your understanding of the XXX_FIDMAG_SNR and XXX_FIDSNR_WARN_RANGE are correct.  The XXX_FIDSNR_ALARM_RANGE is the corresponding range for alarm settings.  Application of these settings to this scalar are reflected on the XXX_FIDSNR_WARN flag, but of course you will reapply the specification for the QLF display.

The value of the specification was set some time ago arbitrarily to the SNR~7 for the fiducial ELG case.  But we did this knowing that it would need to be adjusted for the fact that we calculate the average SNR per pixel for the whole band in each arm -- we do not know redshift in QL and so cannot localize the O II doublet, which is where the SNR should rise to about 7.  We will be doing a short study soon (and more extensive one later), giving a rough mapping of appropriate SNR range for a given fiducial magnitude.  For now, we just leave the values as they are.

The XXX_FITRESULTS arrays give the fitted coefficients to the polynomial fit to logSNR vs. magnitude.  Our documentation is lagging the code a bit here, sorry.  I'll follow up with you on that.  
We went in detail over these outputs with @kdawson yesterday.  You will need to plot these functions in QLF, and we still need to add them to the static plots.  Let's complete this before I merge this branch.  There is one other item to commit before this is merged.

**Comment by rstaten** [comment]
@afausti: As @rkehoe mentioned, the XXX_FITRESULTS are the fitted coefficients. More specifically, the first list containing three values in the XXX_FITRESULTS output represents the fit parameters of a+b*x+c*x**2, in that order. The second list containing nine values is the covariance matrix of the fit.

**Comment by rstaten** [comment]
@rkehoe, the test that was failing due to a potential memory issue with travis is now passing. Ok to merge.

**Comment by rkehoe** [comment]
I'll merge this now.

**Pull request merged**
