### PR TITLE
Major cleanup of pipeline documentation

### PR DESCRIPTION
**Pull request by tskisner**
Major cleanup of pipeline documentation:

 - Update install instructions with examples for Linux and OS X

 - Expand pipeline use section to include examples of desi_pipe_status

 - Add new section on pipeline internals which covers details about
   the processing and how to add new workers

### CODE REVIEW

**Comment by sbailey** [comment]
Travis claims the tests pass, but the build_sphinx test actually blew up due to a missing yaml dependency.  Please add that to the travis install.

Documentation updates themselves look good.

**Comment by tskisner** [comment]
Interesting.  So the sphinx_build test runs using the system python?  I see pyyaml is already in the conda dependencies.  I'll try adding python-yaml to the APT list then.

**Comment by weaverba137** [comment]
You should not add python-yaml, because the Travis test system uses conda, not the system Python install.

**Comment by tskisner** [comment]
ok, I see that it didn't help.  But pyyaml is already in the list of conda packages.  So why can't sphinx "import yaml" ?

**Comment by weaverba137** [comment]
That remains to be seen.

**Comment by tskisner** [comment]
Ok, I'll keep poking at this, apologies for lots of test pushes :-)

**Comment by tskisner** [comment]
I think I just need to add CONDA_DEPENDENCIES to the build_sphinx entry in the matrix.

**Comment by weaverba137** [comment]
See if astropy is reporting any problems today.

**Comment by weaverba137** [comment]
Yes, that should help.

**Comment by tskisner** [comment]
That worked, just cleaning up some warnings now.

**Comment by sbailey** [comment]
Reading these in more detail in their pretty readthedocs form, I noticed that "Installing Dependencies on an OS X System" is based on homebrew whereas elsewhere we recommend using conda.  Would it be possible to use conda for the python side and homebrew for the MPI/boost side?

**Comment by tskisner** [comment]
Conda's openmpi seems broken for me, and you can't force conda mpi4py to
use non-conda openmpi.  I know you love conda, but it has some drawbacks.

**Pull request merged**
