### PR TITLE
add update_survey_keywords to standardize early FA headers

### PR DESCRIPTION
**Pull request by sbailey**
This PR implements #1723 by having assemble_fibermap standardize any missing SURVEY, FAPRGRM, FAFLAVOR keywords from early fiberassign files.  The added utility function `update_survey_keywords` could also be used to update fiberassign files in svn if/when we're ready to do that.

Unit tests cover the known cases; example `assemble_fibermap` outputs in `/global/cfs/cdirs/desi/users/sjbailey/dev/faprogram/test/update` (this PR) and `main/` (current main branch).

Current main, with missing keywords:
```
[login34 test] fitsheader -e FIBERMAP -k TILEID -k SURVEY -k FAPRGRM -k FAFLAVOR main/fibermap*.fits
WARNING: main/fibermap-00050988.fits (HDU FIBERMAP): Keyword SURVEY not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00050988.fits (HDU FIBERMAP): Keyword FAPRGRM not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00050988.fits (HDU FIBERMAP): Keyword FAFLAVOR not found. [astropy.io.fits.scripts.fitsheader]
# HDU FIBERMAP in main/fibermap-00050988.fits:
TILEID  =                70004                                                  
WARNING: main/fibermap-00067710.fits (HDU FIBERMAP): Keyword SURVEY not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00067710.fits (HDU FIBERMAP): Keyword FAPRGRM not found. [astropy.io.fits.scripts.fitsheader]
# HDU FIBERMAP in main/fibermap-00067710.fits:
TILEID  =                80605                                                  
FAFLAVOR= 'cmxlrgqso'                                                           
WARNING: main/fibermap-00067733.fits (HDU FIBERMAP): Keyword SURVEY not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00067733.fits (HDU FIBERMAP): Keyword FAPRGRM not found. [astropy.io.fits.scripts.fitsheader]
# HDU FIBERMAP in main/fibermap-00067733.fits:
TILEID  =                80606                                                  
FAFLAVOR= 'cmxelg  '                                                            
WARNING: main/fibermap-00069031.fits (HDU FIBERMAP): Keyword SURVEY not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00069031.fits (HDU FIBERMAP): Keyword FAPRGRM not found. [astropy.io.fits.scripts.fitsheader]
# HDU FIBERMAP in main/fibermap-00069031.fits:
TILEID  =                80611                                                  
FAFLAVOR= 'sv1bgsmws'                                                           
WARNING: main/fibermap-00069062.fits (HDU FIBERMAP): Keyword SURVEY not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00069062.fits (HDU FIBERMAP): Keyword FAPRGRM not found. [astropy.io.fits.scripts.fitsheader]
# HDU FIBERMAP in main/fibermap-00069062.fits:
TILEID  =                80220                                                  
FAFLAVOR= 'dithlost'                                                            
WARNING: main/fibermap-00083162.fits (HDU FIBERMAP): Keyword FAPRGRM not found. [astropy.io.fits.scripts.fitsheader]
# HDU FIBERMAP in main/fibermap-00083162.fits:
TILEID  =                81000                                                  
SURVEY  = 'sv2     '                                                            
FAFLAVOR= 'sv2dark '                                                            
# HDU FIBERMAP in main/fibermap-00083714.fits:
TILEID  =                    1                                                  
SURVEY  = 'sv3     '                                                            
FAPRGRM = 'DARK    '                                                            
FAFLAVOR= 'sv3dark '                                                            
```

This PR, filling in missing keywords:
```
[login34 test] fitsheader -e FIBERMAP -k TILEID -k SURVEY -k FAPRGRM -k FAFLAVOR update/fibermap*.fits
# HDU FIBERMAP in update/fibermap-00050988.fits:
TILEID  =                70004                                                  
SURVEY  = 'cmx     '                                                            
FAPRGRM = 'unknown '                                                            
FAFLAVOR= 'cmxunknown'                                                          
# HDU FIBERMAP in update/fibermap-00067710.fits:
TILEID  =                80605                                                  
SURVEY  = 'sv1     '                                                            
FAPRGRM = 'lrgqso  '                                                            
FAFLAVOR= 'cmxlrgqso'                                                           
# HDU FIBERMAP in update/fibermap-00067733.fits:
TILEID  =                80606                                                  
SURVEY  = 'sv1     '                                                            
FAPRGRM = 'elg     '                                                            
FAFLAVOR= 'cmxelg  '                                                            
# HDU FIBERMAP in update/fibermap-00069031.fits:
TILEID  =                80611                                                  
SURVEY  = 'sv1     '                                                            
FAPRGRM = 'bgsmws  '                                                            
FAFLAVOR= 'sv1bgsmws'                                                           
# HDU FIBERMAP in update/fibermap-00069062.fits:
TILEID  =                80220                                                  
SURVEY  = 'cmx     '                                                            
FAPRGRM = 'dithlost'                                                            
FAFLAVOR= 'dithlost'                                                            
# HDU FIBERMAP in update/fibermap-00083162.fits:
TILEID  =                81000                                                  
SURVEY  = 'sv2     '                                                            
FAPRGRM = 'dark    '                                                            
FAFLAVOR= 'sv2dark '                                                            
# HDU FIBERMAP in update/fibermap-00083714.fits:
TILEID  =                    1                                                  
SURVEY  = 'sv3     '                                                            
FAPRGRM = 'DARK    '                                                            
FAFLAVOR= 'sv3dark '                                                            
```

@araichoor please double check, thanks.

### CODE REVIEW

**Comment by araichoor** [comment]
@sbailey, thanks a lot for that work!

it looks good to me, it handles all cases as of today.

I would just maybe suggests few additional safety nets, in the very unlikely event that new problematic tiles appear.
I let it up to you to add those or not.

and I also add at the end two remarks on that topic.


**Suggestion 1:**
https://github.com/desihub/desispec/blob/96b7567b23af4010146b109dcfecaaf19b03f450/py/desispec/io/fibermap.py#L438-L440
here I am a little nervous of this "else" with no check.
if I m correct, the following `FAFLAVOR`s should fall in that case:
```
['cmxm33', 'cmxposmapping', 'sv1backup1', 'sv1bgsmws', 'sv1elg', 'sv1elgqso', 'sv1lrgqso', 'sv1lrgqso2', 'sv1m31', 'sv1mwclusgaldeep', 'sv1orion', 'sv1praesepe', 'sv1rosette', 'sv1scndcosmos', 'sv1scndhetdex', 'sv1ssv', 'sv1umaii', 'sv1unwisebluebright', 'sv1unwisebluefaint', 'sv1unwisegreen']
```
so maybe add an `assert` command with that the `FLAVOR` is in this list?
or maybe simply `assert(FAFLAVOR[:3] in ['cmx', 'sv1'])`?


**Suggestion 2:**
for all `$DESI_TARGET/fiberassign/tiles/trunk/???/fiberassign-??????.fits*` files except 063501-063505, the 0-extension header has a `FA_SURV` keyword (which likely comes from a call to desitarget.targets.main_cmx_or_sv() in fiberassign), which I think is what SURVEY is kind of duplicating.
so I suggest that, if we updated `SURVEY`, we add a check that it is equal to `FA_SURV`.
i.e. add in after the "else" statement here:
https://github.com/desihub/desispec/blob/96b7567b23af4010146b109dcfecaaf19b03f450/py/desispec/io/fibermap.py#L461-L464
something like:
```
if ("SURVEY" in updates) & ("FA_SURV" in hdr):
    assert(updates["SURVEY"] == hdr["FA_SURV"]
```


**Remark 1:**
I notice that the dithered tiles designed with `fiberassign/bin/fba_cmx` do not have `FAPRGRM`, `SURVEY` (even if designed recently, see e.g. 82695 designed in May 2022).
I ll update that in `fiberassign/bin/fba_cmx`.


**Remark 2:**
in case we are brave enough in some future to recover the identification of the early tiles (`59026 <= tileid <= 78013`), I drop here few places where there are partial infos about those:
- https://desi.lbl.gov/trac/wiki/SurveyPlanning/early_field_centers
- https://desi.lbl.gov/trac/wiki/Pipeline/Commissioning/guidealignment
- [desi-commiss 4234] minisv0c spectra from 20200127
- [desi-commiss 3858] Tiles for mini-SV
- https://desisurvey.slack.com/archives/C011JS5GW5U/p1661553722964549?thread_ts=1661274455.900399&cid=C011JS5GW5U

**Comment by sbailey** [comment]
These are good suggestions, thanks.  Implementing them highlighted the case of /global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/059/fiberassign-059026.fits which has FA_SURV='main' but none of the other keywords, and this PR was deriving SURVEY=cmx, FAPRGRM=unknown, FAFLAVOR=cmxunknown, i.e. inconsistent with FA_SURV.

That might be "correct", albeit confusing, if it was a commissioning test of fiber assignment of main survey targets.  i.e. does FA_SURV refer to the input targets and columns generated, while SURVEY refers to the DESI survey under which this tile should be grouped?

@araichoor please investigate and let us know how this tile should be assigned.  I suspect that there are others in this case; this is just the first I tripped on.

**Comment by araichoor** [comment]
my suggestion 2 was actually a kind of dummy one, sorry; just forget it.

as you found out there are some non-main tiles which have been run with main targets (ie FA_SURV="main"):
- the 059xxx serie you found, which have no SURVEY; those obviously are some commissioning tiles, in the sense they were designed before sv1;
- also some other special tiles (tests, or tertiary, where main standards are used); but those have SURVEY!="main", so perfect
- and I notice that tileid=74048 has FA_SURV="sv1", whereas it s designed before sv1.

for reference, attached is an ascii file listing for each FN the TILEID, FA_VER, FA_SURV, SURVEY, FAPRGRM, FAFLAVOR (with defaulting to -99, "none", "none", "none", "none", "none", respectively, if not present in the header).
[fiberassign-fasurv-faver.txt](https://github.com/desihub/desispec/files/9891563/fiberassign-fasurv-faver.txt)

"_does FA_SURV refer to the input targets and columns generated, while SURVEY refers to the DESI survey under which this tile should be grouped?_"
=>
yes; FA_SURV is automatically computed from the presence of columns like CMX_TARGET in the input target catalogs; SURVEY is something we set, but got implemented later down the road.

**Comment by araichoor** [comment]
for completeness: this svn commit on Feb. 27, 2020 adds 87 "observed tiles from three other CMX programs": https://desi.lbl.gov/trac/changeset/115/data
84/87 are in $DESI_TARGET/fiberassign, and currently have no SURVEY, etc.; those can safely be set as commissioning tiles.

(about the 3/87 "missing" ones: those have removed from svn on Nov 23, 2020: https://desi.lbl.gov/trac/changeset/162/data)

**Comment by sbailey** [comment]
Thanks for the followup; I dropped the FA_SURV vs. SURVEY check.

**Pull request merged**
