### PR TITLE
QL refactor

### PR DESCRIPTION
**Pull request by julienguy**
Some quicklook refactoring to get a better interface with offline calib. data, and fast processing tools for commissioning.

 - fix duplicated I/O for x,y, and sigmas between online and offline pipelines: desispec/psf.py moved to desispec/quicklook/qlpsf.py, now uses desispec/xytraceset.py to be consistent. we could remove totally qlpsf in a future PR.
 - quicklook now uses DESI_CCD_CALIBRATION_DATA as default calibration set, and the preproc mecanism to select a calib. data set from the raw data header keywords.
 - add QFrame object and its I/Os in desispec/qproc
 - add faster boxcar,fiberflat,sky sub in desispec/qproc
 - allow quicklook to use those with the introduction of Extract_QP, ApplyFiberFlat_QP and SkySub_QP in QL framework (see desispec/quicklook/ qlconfig.py and procalgs.py )
 - add a script desi_qproc that can preproc,extraction,fiberflat,skysub and display in 30sec a frame 
ex:
```
desi_qproc -i /global/project/projectdirs/desi/spectro/data/20191001/00003586/desi-00003586.fits.fz --fibermap /global/project/projectdirs/desi/spectro/data/20191001/00003586/fibermap-00003586.fits --apply-fiberflat --skysub --camera b1 -o bframe-b1-00003586.fits
```

As an example of the same algorithms ran within the quicklook ecosystem, with the following config, preproc,extraction,fiberflat,skysub and associated QA run in 1min on a single edison core.
The equivalent with the current QL algorithms takes 5min (on a single edison core).

```
Program: dark                                                                                                                           
Flavor: science                                                                                                                         
#- Writeout intermediate files                                                                                                          
WritePreprocfile: True                                                                                                                  
WriteSkyModelfile: False                                                                                                                
WriteIntermediatefiles: False                                                                                                           
WriteStaticPlots: True                                                                                                                  
#- Debuglevel                                                                                                                           
Debuglevel: 20                                                                                                                          
#- Apply x or w resolution to frame file                                                                                                
UseResolution: True                                                                                                                     
#- Generate modified PSF file                                                                                                           
Flexure: False                                                                                                                          
#- Heartbeat Period in seconds                                                                                                          
Period: 5.0                                                                                                                             
#- Time out in seconds                                                                                                                  
Timeout: 120.0                                                                                                                          
# Pipeline algorithm: PAs and QAs for each PA                                                                                           
Pipeline: [Initialize, Preproc, Extract_QP, ApplyFiberFlat_QP, SkySub_QP]                                                               
Algorithms:                                                                                                                             
    Initialize:
        QA:
            Check_HDUs:
                PARAMS: {}
    Preproc:
        QA:
            Get_RMS:
                PARAMS: {PERCENTILES: [68.2,95.4,99.7], NOISE_NORMAL_RANGE: [-1.0, 1.0], NOISE_WARN_RANGE: [-2.0, 2.0]}

    Extract_QP:
        wavelength: {
            b: [3570.0, 5730.0, 0.8],
            r: [5630.0, 7740.0, 0.8],
            z: [7650.0, 9830.0, 0.8]
            }
        QA:
            CountSpectralBins:
                PARAMS: {CUTBINS: 5, N_KNOWN_BROKEN_FIBERS: 0, NGOODFIB_NORMAL_RANGE: [-1, 1], NGOODFIB_WARN_RANGE: [-2, 2]}
    ApplyFiberFlat_QP:
        QA:
            Sky_Continuum:
                PARAMS: {B_CONT: ["4000, 4500", "5250, 5550"],
                         R_CONT: ["5950, 6200", "6990, 7230"],
                         Z_CONT: ["8120, 8270", "9110, 9280"],
                         SKYCONT_NORMAL_RANGE: [-1.0, 1.0],
                         SKYCONT_WARN_RANGE: [-2.0, 2.0]}
            Sky_Peaks:
                PARAMS: {B_PEAKS: [3914.4, 5199.3, 5201.8],
                         R_PEAKS: [6301.9, 6365.4, 7318.2, 7342.8, 7371.3],
                         Z_PEAKS: [8401.5, 8432.4, 8467.5, 9479.4, 9505.6, 9521.8],
                         PEAKCOUNT_NORMAL_RANGE: [-1.0, 1.0],
                         PEAKCOUNT_WARN_RANGE: [-2.0, 2.0]}
    SkySub_QP:
        QA:
            Sky_Rband:
                PARAMS: {B_CONT: ["4000, 4500", "5250, 5550"],
                         R_CONT: ["5950, 6200", "6990, 7230"],
                         Z_CONT: ["8120, 8270", "9110, 9280"],
                         SKYRBAND_NORMAL_RANGE: [-1.0, 1.0],
                         SKYRBAND_WARN_RANGE: [-2.0, 2.0]}
            Sky_Residual:
                PARAMS: {BIN_SZ: 0.1, PCHI_RESID: 0.05, PER_RESID: 95.0, RESID_NORMAL_RANGE: [-5.0, 5.0], RESID_WARN_RANGE: [-10.0, 10.0]}
            Integrate_Spec:
                PARAMS: {DELTAMAG_NORMAL_RANGE: [-2., 2.0], DELTAMAG_WARN_RANGE: [-4., 4.]}
            Calculate_SNR:
                #- First two entries set boundaries for SNR residual values via absolute vales or sigmas
                PARAMS: {RESIDUAL_CUT: 0.2, SIGMA_CUT: 2.0, FIDSNR_TGT_NORMAL_RANGE: [-11., 11.], FIDSNR_TGT_WARN_RANGE: [-12., 12.], FIDMAG: 22.}



```

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks.  Could you point us to an example at NERSC of the same input data passed through the two different algorithm chains with output written to two different directories for comparison?  This is a major update and we'll need to review it by running it and comparing outputs in addition to reading code changes.

Is there any quicklook QA functionality in current master that is currently not working in this branch?  e.g. when quicklook is configured to use the new algorithms, does it still output meaningful values for all the same QA metrics in the same JSON format?

Note some test failures due to the refactored libraries (import failures on `desispec.boxcar` and `desispec.psf`).

**Comment by julienguy** [comment]
Example run at NERSC.
```
export QL_SPEC_DATA=/global/project/projectdirs/desi/spectro/data
export QL_CONFIG_DIR=/global/homes/j/jguy/software/desispec/py/desispec/data/quicklook

export QL_SPEC_REDUX=/project/projectdirs/desi/users/jguy/quicklook-test/quicklook
desi_quicklook -i /project/projectdirs/desi/users/jguy/quicklook-test/quicklook_config.yaml -n 20191001 -c b1 -e 3586 &> quicklook.log

export QL_SPEC_REDUX=/project/projectdirs/desi/users/jguy/quicklook-test/qproc
desi_quicklook -i /project/projectdirs/desi/users/jguy/quicklook-test/qproc_config.yaml -n 20191001 -c b1 -e 3586 &> qproc.log
```
```
/project/projectdirs/desi/users/jguy/quicklook-test/quicklook/exposures/20191001/00003586/ql-snr-b1-00003586.png
```
quicklook-ql-snr-b1-00003586


```
/project/projectdirs/desi/users/jguy/quicklook-test/qproc/exposures/20191001/00003586/ql-snr-b1-00003586.png
```
qproc-ql-snr-b1-00003586

There are some differences in SNR that would be interesting to understand.

**Comment by julienguy** [comment]
Comparison of spectra for a bright star in b
sframe-b1-00003586-fiber100

Comparison of spectra for the faintest target in the petal in r
sframe-r1-00003586-fiber168

**Comment by julienguy** [comment]
the tests fail because there is no DESI_CCD_CALIBRATION_DATA in the environment ...

**Comment by julienguy** [comment]
This PR is ready for review.

**Comment by sbailey** [comment]
Thanks for the PR @julienguy especially for maintaining the ability to still run with the existing QL algorithms, and for the ability to run with the new algorithms within the QL framework but also standalone.

@Srheft @rstaten @rkehoe can you please check that this still maintains the current functionality of QL?  i.e. does it still produce all the same metrics with meaningful values?  A lot has moved under the hood, but if this PR doesn't fundamentally break anything we can proceed with it while still evaluating the algorithms in detail.  I'd like to get this PR evaluated and merged this week prior leaving on vacation.

I looked at the outputs side-by-side and the most noticeable difference is that the new boxcar extractions use the cosmic ray mask while the QL boxcar apparently do not, leaving many spurious spikes in the spectra.  By eye the new algorithms also have less scatter in the fitted S/N vs. magnitude but I haven't studied that in detail.  There are also some systematic offsets in the extracted spectra but I haven't compared to input truth to see which is more correct.

**Comment by Srheft** [comment]
Thank you for this great PR @julienguy:

This is not a full set of comments but for the purpose of verifying that quicklook is not broken and can be run independently, I did run QL on NERSC from this branch:

Arc processing:
time desi_quicklook -i qlconfig_arcs.yaml -n 20191001 -c b0 -e 3571 --> 1m28sec  

Flat processing:  
time desi_quicklook -i qlconfig_flat.yaml -n 20191001 -c b0 -e 3574  --> 3m55sec

Science processing:
time desi_quicklook -i ./config_files/qlconfig_darksurvey.yaml -n 20191001 -c b0 -e 3586  --> 2m20sec

I verify that the output sframe  and merged JSON files are in tact and located at $QL_SPEC_REDUX/exposures/20191001/

Thanks for removing the two "rcond=None" in quicksky.py to prevent a linalg.py block between numpy1.13 and 1.14.

**Comment by sbailey** [comment]
Thanks for the check, @Srheft .  Since this adds new functionality without breaking the old functionality, let's proceed with merging this and then continue with detailed comparisons separately.  I'll wait for tests to finish (I just fixed merge conflict in changes.rst) and then merge.

After this merge, it would be useful to get both using the same boxcar extractions (or both masking cosmics) so that differences in downstream algorithm outputs are due to those algorithms themselves and not just cosmics outliers pulling the results.

**Comment by rkehoe** [comment]
I had been asked to comment on this PR, but cannot do so till tomorrow morning unfortunately.  The tests by @Srheft confirm the functionality and performance of QL is preserved.  I believe this satisfies your goal for this PR.  Please do not delete the branch right away if you merge so I can go over code changes in the morning.  It will be useful to consider these changes carefully as we think of next steps.

**Comment by sbailey** [comment]
Thanks for the comments and checks.  I've merged this PR, but left the branch on github for now.  Comparing current master to tag 0.22.1 should be equivalent, but let me know if there is easier to do with the branch.

When further changes are made, please make a new branch off of master instead of making updates to this branch.

**Pull request merged**
