### PR TITLE
Ql calibration update

### PR DESCRIPTION
**Pull request by rkehoe**
This PR is intended as a necessary update to QL to finish some details related to calibration, either calibration exposures or flux calibration.  As such it will include the following elements:

- complete calculation of Sky Rband based on flux calibrated spectra.
- integration of qproc boxcar as default extraction for arc exposure processing
- update to flat exposure processing for final QA metric
- migration of most remaining plots to plot configuration
- necessary fixes given fall code updates.

This PR will be completed in the next day.  @felipe, there will be some modest changes to the output file in the addition of three or four new metrics.  I’ll send the relevant details when ready to merge.

### CODE REVIEW

**Comment by felipelm** [comment]
@rkehoe is there a new calibration file? I got this error trying to process exposure `3578 20191001`

```
Failed to run PA ApplyFluxCalibration
KeyError: 'FLUXCALIB'
    fluxcalib_filename=os.path.join(os.environ["DESI_CCD_CALIBRATION_DATA"],calibration_data["FLUXCALIB"])
  File "/app/desispec/py/desispec/quicklook/procalgs.py", line 945, in run_pa
    return self.run_pa(input_frame,outputfile=outputfile)
  File "/app/desispec/py/desispec/quicklook/procalgs.py", line 932, in run
    return self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/quicklook/pas.py", line 18, in __call__
    inp=pa(inp,**pargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 125, in runpipeline
Traceback (most recent call last):
2019-01-15 11:31:30,248 QuickLook CRITICAL : Failed to run PA ApplyFluxCalibration error was 'FLUXCALIB'
```

**Comment by rstaten** [comment]
@felipelm You can use the following command to checkout the updated calibration area. I have tested locally and it runs, hopefully you can confirm this. Thanks!

svn checkout svn+ssh://${username}@dtn01.nersc.gov/global/project/projectdirs/desi/spectro/calib/svn/ccd_calibration_data/trunk ccd_calibration_data

**Comment by felipelm** [comment]
There is a issue with object types lists

ql-mergedQA-b7-00003578.json (**OLD VERSION**)
```
...
"GENERAL_INFO": {
...
        "STAR_FIBERID": [
            30,
            46,
            63,
            177,
            191,
            262,
            290,
            312,
            398,
            472
        ],
...
```

This PR mergedQA
ql-mergedQA-b7-00003578.json (**This PR**)

```
...
"GENERAL_INFO": {
...
        "STAR_FIBERID": [
            3530,
            3546,
            3563,
            3677,
            3691,
            3762,
            3790,
            3812,
            3898,
            3972
        ],
...
```

We use this mapping to get a position in the array of 500 (number of fibers in a petal). What happened now? Do we need to do a `%500` to get the relative position?

@felipeaoli @rstaten

**Comment by felipelm** [comment]
@rkehoe @rstaten now `GENERAL_INFO->FIBER_MAGS` is an array containing 3 arrays size 500. Is there a reason for this change? 

Before it was a simple float array size 500

**Comment by rkehoe** [comment]
Given that the QLF comments are outside this PR, and that Travis tests are working, this PR looks ready to merge.  

@felipelm there were modest changes to three scalar metrics in the mergedQA output, one for science exposures and two for calibrations.  These are connected to Issues #709, #710 and #711 and I will elaborate on them further in those tickets, and on the QL wiki.  But for now, they are:

- SKYRBAND: average of sky fiber spectral R band calculations (previously placeholder)
- CHECKARC(1): number of fibers with converging PSF fit (previously a different calculation, and now 
 has 1 member rather than 3)
- CHECKFLAT(1): average of the mean fiberflat values among fibers (previously placeholder)

QLF ran fine with these changes, presumably because they were placeholder in fall.  I do not think there is a need to implement them in QLF in a rush.  

I’ll merge in a minute.

**Comment by felipelm** [comment]
OK @rkehoe I'll flatten the array so it will appear that there are 1500 fibers instead of 500 on deltamag qa plot until we figure this out.

@felipeaoli @sbailey any idea on what made this change?

**Comment by rkehoe** [comment]
@felipelm. The change occurred in QL when we adopted the new fibermap.  I should have conveyed this to you when we did the update, in the PR merge request.  It may have occurred near when people were leaving for holiday, and sorry if I was not clear then.  

It isn’t clear from your description that you are using the array properly - @rstaten can you comment?  Actually, it would be best to carry this forward on an open PR for QLF now that this one is closed.
@felipelm, @rstaten would QLF PR #302 work?

**Comment by felipelm** [comment]
Sure https://github.com/desihub/qlf/pull/302 will work

**Pull request merged**
