### PR TITLE
Desi spectro calib

### PR DESCRIPTION
**Pull request by julienguy**
New structure for DESI calibration data.

 * new code 
    * desispec/calibfinder.py : new class CalibFinder replaces the function read_ccd_calibration_data in desispec/preproc.py. The init function has a list of headers as argument to find the matching calibration data (as in read_ccd_calibration_data). The class has three functions findfile(key) , haskey(key) , value(key). There is nothing clever here but it gives more flexibility for possible future changes.
    * changes to preproc , desi_qproc , add unit test.
    * see example use here https://github.com/desihub/desispec/blob/c4a9a4ae9a72314bc33642bd6c03f3b6a736c171/bin/desi_qproc#L86
 * new SVN repository in DESI trac (backed-up) environment.
    * see https://desi.lbl.gov/trac/browser/calib/desi_spectro_calib/trunk
    * new directory structure
```
desi_spectro_calib/spec/sp*/{b,r,z}*.yaml,psf-{brz}*-YYYYMMDD.fits,...
desi_spectro_calib/ccd/{bias,dark,...}-{b,r,z}-{DETECTOR}-YYYYMMDD.fits
desi_spectro_calib/sim/spec/sp*/...
 ```

Users running on simulations only need to check out desi_spectro_calib/sim. Users analysing 1D spectra without going back to CCD images only need to checkout  desi_spectro_calib/spec.

 * new environnment variable DESI_SPECTRO_CALIB instead of DESI_CCD_CALIBRATION_DATA.
    It's arguably a bit annoying to change this, but this name is more consistent with the other DESI variables, and the calibration repo contains more calibration data than just the CCD parameters.
    
 **I have not modified quicklook functions. So this PR has to be merged only after quicklook PRs are merged and the QL code has been adapted to this new scheme.**

### CODE REVIEW

**Comment by rkehoe** [comment]
@julienguy. The last QL PR was merged earlier this evening, but tests are still ongoing with QLF.  There might be another tweak, depending on those tests.  Would It be appropriate to comment here when tests are ‘done’? Please advise.

**Comment by julienguy** [comment]
Yes please. I will implement in the branch the modifications needed for QL but I will only be able to run the unit tests.

**Comment by rkehoe** [comment]
@julienguy I should have sent this earlier, but coding and testing on QL are ‘done’ for the moment, as of two weeks ago.  So please feel free to update quicklook for these changes in this branch.  Sorry for the delay in responding.

There are some other updates to pursue relatively soon, but they can come after you are done I think.

**Comment by julienguy** [comment]
I will let Stephen merge this because the change of environment variable will perturb several integration tests.

**Comment by sbailey** [comment]
Code looks good.  I added a change to support simulated data files even if $DESI_SPECTRO_CALIB was set for real data.  Tests failed on Travis, I will dig into that.

I'm also having integration test failures related to QA, so I'd like to get that sorted out before merging.

**Comment by sbailey** [comment]
I'm unable to reproduce the integration test failures that I was having on Friday (which are different from the unit tests failures that @julienguy fixed; thanks).  Let's go ahead and merge.

**Pull request merged**
