### PR TITLE
updated docstrings

### PR DESCRIPTION
**Pull request by sbailey**
This PR addresses issue #17 to update the docstrings (again).  They aren't perfect, but they are fairly complete.  This also corrects a number of docstrings that were simply wrong about inputs and outputs (usually due to interfaces which changes but the docstring wasn't updated).

### CODE REVIEW

**Comment by moustakas** [comment]
These look great.

**Comment by weaverba137** [comment]
The sphinx build throws this warning:

desispec/py/desispec/fiberflat.py:docstring of desispec.fiberflat.compute_fiberflat:16: ERROR: Unexpected indentation.

So you might as well fix that in this PR.  Otherwise, everything looks fine.

**Comment by sbailey** [comment]
I thought the Travis tests include the sphinx build, but the Travis tests are currently passing, though I don't see a push that fixed this.  Can you clarify:
* do the Travis tests *not* check the sphinx build?
* or did you (or someone) fix this already?
* or something else?

**Comment by weaverba137** [comment]
1. The Travis tests *do* include a sphinx build.
2. When I read the logs of the sphinx build I found that warning message.
3. Technically this is a *warning* message, not an error message, so the build succeeds despite the warning.
4. I have not fixed it yet.

**Comment by sbailey** [comment]
I just pushed the fix to the sphinx warning.  It took me a minute to figure out what sphinx was unhappy about, so for the record:

    Notes:
    - we first iteratively :
       - compute a deconvolved mean spectrum
       - compute a fiber flat using the resolution convolved mean spectrum for each fiber

Should have been:

    Notes:
    - we first iteratively :

       - compute a deconvolved mean spectrum
       - compute a fiber flat using the resolution convolved mean spectrum for each fiber

i.e. the sub-bullet list needs to have a blank line between it and the previous bullet; the increased indentation alone is not sufficient.

**Comment by weaverba137** [comment]
Sphinx looks happy now!  Yes, that blank line thing is a common problem in reStructuredText.

**Pull request merged**
