### PR TITLE
support both new and old format fibermaps

### PR DESCRIPTION
**Pull request by sbailey**
@Srheft and @rstaten this is a PR into your ql_TagUpdates_0.21.0 branch (not master) to support using both new-format and old-format fibermaps.  It does this by detecting and auto-converting the new format back into the old format in `desispec.io.read_fibermap`.  If quicklook is not using this function to read the fibermap, then please convert it to use this function (which was written to facilitate exactly this kind of issue by isolating algorithm code from the underlying I/O details).

Please test this with quicklook using new format data at KPNO in `/data/quicklook/staging/raw/20191001/*/*`.  Note that these directories also use the EXPID subdirectories; please also update quicklook to use that.  Hopefully this is as easy as just updating `desispec.io.findfile` without having to modify any of quicklook itself.

**Context**: the "new format" fibermaps are a work in progress to bring consistency to columns names between the fibermap, fiber assignment, target selection, and the instrument control system.  e.g. tracking fluxes instead of magnitudes, and including proper motions.  The downstream code is not yet ready for the new format, but by converting back to the old format on-the-fly we should be able to proceed.

### CODE REVIEW

**Comment by Srheft** [comment]
@sbailey 
Thanks for the PR. I do not have access to kp machines. Any other place the new format data exist?

**Comment by sbailey** [comment]
@Srheft I put a copy at NERSC in `/project/projectdirs/desi/datachallenge/mockobs-18.6/staging/`.

If needed, we should get NOAO and SMU sysadmins to debug your connection so that you can have stable reliable remote access to KPNO (you need the stable connection; I don't know if we need NOAO and SMU sysadmins to help debug the problem and solution).

**Comment by rstaten** [comment]
@sbailey My recent commit updates the paths for raw and fibermap files so that QL can find the inputs  in the right place. We do use read_fibermap to read in this file, so no changes should be required there.  A couple Travis tests fail, but this will not cause an issue with running QL. I have verified that QL runs and also this test passes locally, so this could just be a Travis environment issue. This PR seems fine to be merged into ql_TagUpdates_0.21.0

**Comment by Srheft** [comment]
@rstaten : could you back track from your changes here and use direct commit to TagUpdate? just to get the tests straight.

**Comment by sbailey** [comment]
It should be ok to get the tests working in this branch and then merge, but do whatever is most efficient.  It does appear to be a genuine QL test failure related to the new file locations, but perhaps it is just that the test needs to be updated to put the input files in the new structure too.
```
(desi) [new-fibermap-format*] desispec $ python py/desispec/test/test_ql.py 
INFO:util.py:73:runcmd: Mon Jun 25 11:26:07 2018
INFO:util.py:74:runcmd: RUNNING: /Users/sbailey/anaconda/envs/desi/bin/python /Users/sbailey/desi/git/desispec/bin/desi_quicklook -i /Users/sbailey/ql_test_io/test_config.yaml -n 20150105 -c r0 -e 314 --rawdata_dir /Users/sbailey/ql_test_io --specprod_dir /Users/sbailey/ql_test_io 
2018-06-25 11:26:09,017 QLConfig WARNING : WARNING, can't open template file /Users/sbailey/ql_test_io/exposures/20150105/00000311/ql-mergedQA-r0-00000311.json
2018-06-25 11:26:09,025 QLConfig INFO : Checking if all the necessary files exist.
File does not exist: /Users/sbailey/ql_test_io/20150105/00000314/desi-00000314.fits.fz
INFO:util.py:97:runcmd: Mon Jun 25 11:26:09 2018
CRITICAL:util.py:99:runcmd: FAILED /Users/sbailey/anaconda/envs/desi/bin/python /Users/sbailey/desi/git/desispec/bin/desi_quicklook -i /Users/sbailey/ql_test_io/test_config.yaml -n 20150105 -c r0 -e 314 --rawdata_dir /Users/sbailey/ql_test_io --specprod_dir /Users/sbailey/ql_test_io 
E
======================================================================
ERROR: test_QA (__main__.TestQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "py/desispec/test/test_ql.py", line 185, in test_QA
    raise RuntimeError('quicklook pipeline failed')
RuntimeError: quicklook pipeline failed

----------------------------------------------------------------------
Ran 1 test in 2.217s

FAILED (errors=1)
```

**Comment by Srheft** [comment]
Merged. I'll take care of the test. Thank you.

**Pull request merged**
