### PR TITLE
Improve fiberflat vs humidity

### PR DESCRIPTION
**Pull request by julienguy**
Improve fiberflat vs humidity correction
 - used all daily fiberflats from 2020,2021,2022
 - change binning fiberflats : use the wavelength shift of the fiberflat in b0 instead of the humidity value from the metrology (in other words, we use b0 as a humidity probe)
 - use one template for each step of 2A in the wavelength shift
 - interpolate between bins using the template index rather than the humidity values of each template.

Example for the b0 fiber flat humidity correction template:
templates-for-b0

The following figure shows that the wavelength shift is not a monotonous function of the humidity from the telemetry at very low humidities (could be due to a time constant for the collimator mirror variations). This justifies using directly the wavelength shift as the index instead of the humidity.

variation-from-cross-correlation-b0

Improvement on the sky residuals for tile 4003 expid 118524 (blue=daily orange=this PR). It's not perfect because there is no equivalent for the wavelength shift of this particular exposure in the flat field data.

sky-res-118524

With this correction the QA of tile 4403 is improved. The accumulation of sky fibers at redshifts 2.6 has disappeared:  
see https://data.desi.lbl.gov/desi/spectro/redux/jguy/tiles/cumulative/4403/20220113/tile-qa-4403-thru20220113.png
compared to https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/4403/20220113/tile-qa-4403-thru20220113.png

The new code can be tested with the new template when setting
```
export DESI_SPECTRO_CALIB=/global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib
```

### CODE REVIEW

**Comment by julienguy** [comment]
I am waiting for a review of this PR before committing to SVN the new humidity correction templates.
This PR solves issue https://github.com/desihub/desisurveyops/issues/9 .

**Comment by sbailey** [comment]
Looks good; I think I understand and agree with the change in indexing.

Please also test with the sample of nights/exposures from previous PRs on this topic:
  * PR #1565: nights 20211215 and 20211220 with known variable humidity, and 20210515 with stable humidity
  * PR #1642: night 20210709 exposures 98061, 98064, 98067 near high limit of humidity range
  * PR #1589: night 20220112 exp 118339 at low limit of humidity range

**Comment by akremin** [comment]
Trying to understand the note "we use b0 as a humidity probe". I looked through the code to answer it for myself, but I couldn't easily find where that bit was implemented.

What does the code do if b0 wasn't present for an exposure? What happens if the raw data exists, but b0 is excluded (i.e. flagged and unprocessed)?

**Comment by julienguy** [comment]
The wavelength shift of the b0 fiberflat dip has been measured to sort the fiber flats and define the bins to generate the templates. This is given by the column 'DIPWAVE' of the input table (`desi_compute_fiberflat_vs_humidity --intable ...`). This wavelength has been obtained with calls to the function `fiberflat_vs_humidity.fit_wave_of_dip`. I should document this better.

The wavelength shift is only used to generate the templates. It is not used afterwards. So the flat field corrections do not require the b0 data.

**Comment by julienguy** [comment]
Improvement for night 20220112 exp 118339 (low humidity):
sframe-20220112-00118339

Same results for 20210709 exp 98061 98064 98067  (high humidity ~< 50% ):
sframe-20210709-00098061

Jobs for full nights 20211215 20211220 20210515 are in the queue.

**Comment by julienguy** [comment]
Result on test nights

compare-z-20211215

20211215 n(z>0.05, daily)     = 42483
20211215 n(z>0.05, new)      = 42435, -0.1% change
20211215 n(|dz|/(1+z)>0.0033) = 94, 0.2%

compare-z-20211220

20211220 n(z>0.05, daily)     = 16931
20211220 n(z>0.05, new)      = 16889, -0.2% change
20211220 n(|dz|/(1+z)>0.0033) = 66, 0.4%
 
compare-z-20210515

20210515 n(z>0.05, daily)     = 35140
20210515 n(z>0.05, new)       e= 35039, -0.3% change
20210515 n(|dz|/(1+z)>0.0033) = 124, 0.4%

**Comment by julienguy** [comment]
I checked the outstanding differences in redshifts for 20211220 where we get z~0 in the new prod and z>>0 in daily for some targets: the incorrect redshifts are in the daily prod and are due to an incorrect spectro-photometric calibration (not related to this PR).
I also did a visual inspection of a few cases for 20210515 where we now get z~0 and I also find that the redshifts were incorrect in the daily prod (offsets between cameras, or OII on edge of camera). I think the differences are not related to this PR.

**Comment by julienguy** [comment]
I think this PR is ready. I addressed the comment from @akremin  (about using flats from a single camera, b0, to index the changes with humidity) by refactoring the script desi_compute_fiberflat_vs_humidity in a recent commit.

**Comment by sbailey** [comment]
Looks good; thanks for the extra checks.  Please proceed with updating desi_spectro_calib svn and we'll coordinate with updating the desispec code at NERSC prior to tonight's processing.

**Pull request merged**
