### PR TITLE
[WIP] Update desispec.io.download for data.desi.lbl.gov

### PR DESCRIPTION
**Pull request by weaverba137**
Creating a PR to make it easier to track this work.  Do not merge yet.

To Do

- [x] Update `findfile()` with release 20.4-era file paths and support tile-based spectra (*v*. HEALPix).
- [x] Better logging in general and warnings about missing environment variables (and thus directory structure).
- [x] Operational "real world" tests (current unit tests mock the download).

### CODE REVIEW

**Comment by weaverba137** [comment]
@sbailey, I'm running into problems where simply removing the qa files from `findfile()` is causing other portions of the test suite to fail.  Is it time to gut-renovate, as it were, and remove all qa code entirely?

**Comment by sbailey** [comment]
@weaverba137 for now let's leave the qa files in `io.findfile` so that the qa/quicklook tests continue to work, and deal with refactoring those separately (i.e. keep this focused on `io.download` itself).

**Comment by weaverba137** [comment]
@sbailey, while updating the paths in `findfile()` I found a few anomalies:
```python
# fibermap = '{specprod_dir}/preproc/{night}/{expid:08d}/fibermap-{expid:08d}.fits',  # found in andes but not 20.4, shadows raw data
calib = '{specprod_dir}/exposures/{night}/{expid:08d}/calib-{camera}-{expid:08d}.fits',  # found in 20.4 but not andes
# fframe = '{specprod_dir}/exposures/{night}/{expid:08d}/fframe-{camera}-{expid:08d}.fits',  # not found in recent reductions
# qframe = '{specprod_dir}/exposures/{night}/{expid:08d}/qframe-{camera}-{expid:08d}.fits',  # not found in recent reductions
# psfboot = '{specprod_dir}/exposures/{night}/{expid:08d}/psfboot-{camera}-{expid:08d}.fits',  # not found in recent reductions
psfnight = '{specprod_dir}/calibnight/{night}/psfnight-{camera}-{night}.fits',  # found in andes but not 20.4
coadd = '{specprod_dir}/spectra-{nside:d}/{hpixdir}/coadd-{nside:d}-{groupname}.fits',  # not found in 20.4
```
Are any of these obsolete?

**Comment by weaverba137** [comment]
@sbailey, I think the *code* is now ready for review while I'm working on operational testing.

**Comment by weaverba137** [comment]
@sbailey another question on how to proceed.  I'm having trouble with `desispec.io.download.filepath2url()`.  Although I've done some minor reformatting, I haven't done anything significant to modify the code.  Right now it can't handle anything that does not conform to `DESI_SPECTRO_REDUX=${DESI_ROOT}/spectro/redux`, in part because `findfile()` and `download()` do not call it with any options.  Thus, I can download files from `/desi/spectro/redux/andes`, but not from `/desi/datachallenge/reference_runs/20.4/spectro/redux/mini`, even with `DESI_SPECTRO_REDUX=/desi/datachallenge/reference_runs/20.4/spectro/redux`.

Can you think of any reason not to completely rewrite that function, including the API?

**Comment by weaverba137** [comment]
Re: `filepath2url()`

I decided to remove that function entirely. The only remaining question is whether and how to choose an alternate download URL when using `findfile(..., download=True)`?

**Comment by weaverba137** [comment]
I've completed operational tests.  Ready to merge after review.

**Pull request merged**
