### PR TITLE
DB sync

### PR DESCRIPTION
**Pull request by julienguy**
Improved sync. DB based a prod on disk.
This is useful for simulation runs where frames or cframes are simulated directly.
Tested on an instance of the mini test.

### CODE REVIEW

**Comment by julienguy** [comment]
And this solves issue #530

**Comment by tskisner** [comment]
Hell @julienguy , I thought by definition the "sync" command only updated the DB task states based on the filesystem (as opposed to the "update" command, which actually adds tasks to the DB).  What is the intention of the "force" option?

**Comment by tskisner** [comment]
In other words, if the production does not exist, then running "sync" is an error.

**Comment by tskisner** [comment]
Alternatively- running "sync" on a production with zero tasks is basically a non-operation (does nothing), since there are no tasks to check the state of.

**Comment by julienguy** [comment]
The --force is to force the db creation on an existing redux prod. This is needed for simulations where frames or cframes are generated by the sims. If you think of a better approach to this don't hesistate to modify this branch.
As an example I have done,
```
desi_pipe create --data /global/cscratch1/sd/jguy/sim2017/mini7/spectro/sim/mini --redux /global/cscratch1/sd/jguy/sim2017/mini7/spectro/redux --prod mini --db-sqlite

source /global/cscratch1/sd/jguy/sim2017/mini7/spectro/redux/mini/setup.sh

desi_pipe sync

```

**Comment by julienguy** [comment]
I forgot the --force in the desi_pipe create command.

**Comment by tskisner** [comment]
I talked to @julienguy offline, and I had misunderstood what was going on.  This PR looks fine to me- sorry for the noise.

**Pull request merged**
