### PR TITLE
Retrieve etc efftime from json

### PR DESCRIPTION
**Pull request by michaelJwilson**
Retrieve etc efftime from json if ACTTEFF not in frame headers (as true of early main survey data). 

Aside: do not add missing prod exposures if args.expids is not None.

### CODE REVIEW

**Comment by michaelJwilson** [comment]
Note: rewrites EFFTIME_ETC=-99 if not present in frame header and json does not exist (not expected).  Previous behaviour was EFFTIME_ETC=0.0 in such a case.

Tested with:
export SPECPROD=daily # denali                                                                                                                                                                                                                  
export DESI_SPECTRO_CALIB=/global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/
export DESIMODEL=/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desimodel/master

desi_tsnr_afterburner --outfile /global/cscratch1/sd/mjwilson/tsnr-ensemble-updates/tsnr-summary.fits --expids 88359,88360,89881 --recompute --nproc 12 --cameras b0

Yielding:

EXPID EFFTIME_ETC
int32   float32  
----- -----------
88359   181.04936
88360   185.40895
89881   184.74846

for exposures previously marked as EFFTIME_ETC in daily tsnr_exposures.fits.

**Comment by dkirkby** [comment]
Have you compared the FITS header and json values when both are available?  If they disagree, I would use the json value, not the header value.

**Comment by michaelJwilson** [comment]
I had not, here's a comparison for all exposures where etc 'expinfo' was definded (excludes some early exps. in daily tsnrs) and I found ACTTEFF in the corresponding cframe for petal 0 or 1; 

image

One of the worst offenders:
EXPID   JSON_EFFTIME  ACTTEFF     DIFF
84654  1414.137329      1406.3414   7.795928999999887

Although far from ideal, I think we have bigger problems than ~10s and there seems a hesitancy to avoid the jsons where possible, so I'll make the change immediately to defaulting to jsons.

**Comment by julienguy** [comment]
merging after successful test. thanks.

**Pull request merged**
