### PR TITLE
Quicklook qas

### PR DESCRIPTION
**Pull request by rkehoe**
@afausti  Please review this PR.  It contains the following updates for QuickLook:

- RA and Dec in METRICS block of each QA dictionary that deals with fibers
     - this should be eventually placed in 1 QA that is always executed (eg. GetRMS) so that we do not duplicate these arrays several times
     - this will need to move to a general header area for merged dictionaries
- specifications that are indicated by <ScalarName>_RANGE augmented to have double ranges to accommodate two levels of severity, warnings and alarms as per June Hack Day discussion.  
    - updated for all QA dictionaries and in qlconfig for dark science, and arc processing
    - Inner range specifies a warning condition, failing the outer range indicates a more serious alarm
-  values updated data quality assessment (i.e. application of specification range) so that <ScalarName>_WARN flags have values of 'GOOD', 'WARN' or 'ALARM' 
- implementation of final scalars and specs as discussed at June Hack Day for Get_RMS and Bias_from_Overscan
    - next update will propagate to further QAs
- Calculation of RMS per row in GetRMS
- normalize all occurrences where counts provided to give counts/second
- cleanup

These modifications go a significant distance toward accommodating changes discussed at the Collaboration meeting, and in Utah in May.

### CODE REVIEW

**Comment by afausti** [comment]
@rkehoe @rstaten yes, I tend to agree that we should avoid replicating `RA`, `Dec` for each QA output... but I liked this solution because it is very handy to have this information in place. As far as I understand the targets are not the same from one QA to another, and if we don't have that QLF would have to load the fibermap and match the `fiber_id`s to obtain the `RA` and `Dec`... and I think QL is the right place for that... 

I have tested this branch with QLF the processing time for one camera is 2min27s, so no penalties due to recent changes.

Here is QLF output:
```
2017-08-01 18:30:08 [INFO]: Starting QLF daemon pid 25234...
2017-08-01 18:30:08 [INFO]: Is Quick Look running? True
2017-08-01 18:30:08 [INFO]: Started Quick Look ...
2017-08-01 18:30:08 [INFO]: Night: 20170428
2017-08-01 18:30:08 [INFO]: Exposure ID: 3
2017-08-01 18:30:08 [INFO]: Process ID: 1 started ...
2017-08-01 18:30:08 [INFO]: Output dir: exposures/20170428/00000003
2017-08-01 18:30:08 [INFO]: Output log for camera b0: exposures/20170428/00000003/run-b0.log
2017-08-01 18:30:08 [INFO]: Started job 1 on exposure 3 and camera b0 ...
2017-08-01 18:32:35 [INFO]: Finished job 1 in 0:02:27
2017-08-01 18:32:35 [INFO]: Process finished in 0:02:27.
2017-08-01 18:32:35 [INFO]: Begin ingestion of results...
2017-08-01 18:32:36 [INFO]: Ingesting ql-countbins-b0-00000003.yaml
2017-08-01 18:32:36 [INFO]: Ingesting ql-countpix-b0-00000003.yaml
2017-08-01 18:32:36 [INFO]: Ingesting ql-getrms-b0-00000003.yaml
2017-08-01 18:32:38 [INFO]: Ingesting ql-integ-b0-00000003.yaml
2017-08-01 18:32:39 [INFO]: Ingesting ql-skycont-b0-00000003.yaml
2017-08-01 18:32:40 [INFO]: Ingesting ql-skypeak-b0-00000003.yaml
2017-08-01 18:32:42 [INFO]: Ingesting ql-skyresid-b0-00000003.yaml
2017-08-01 18:32:42 [INFO]: Ingesting ql-snr-b0-00000003.yaml
2017-08-01 18:32:42 [INFO]: Finished ingestion of pipeline results for camera b0.
2017-08-01 18:32:42 [INFO]: Ingestion finished in 0:00:07.```

And here an screenshot from the QLF API showing that the coordinates are being ingested as part of the QA outputs:

<img width="1162" alt="screen shot 2017-08-01 at 11 37 50 am" src="https://user-images.githubusercontent.com/13968086/28841885-7e4415ae-76b0-11e7-866b-31e6fc256ffa.png">

**Comment by afausti** [comment]
@rkehoe @rstaten @sbailey  I think that specification ranges like ` RMS_RANGE=[-2.0, -1.0, 1.0, 2.0]`
 with 4 values are very confusing. If we need more levels of severity please consider having a  specification range for each one,  like a warning range `RMS_WARNING_RANGE = [-2.0, -1.0] and a critical range `RMS_CRITICAL_RANGE = [1.0, 1.0]`. 

I would avoid using `alert` or `alarm` to indicate a severity level I think NORMAL, WARNING and CRITICAL is better.

**Comment by rkehoe** [comment]
@afausti  Thanks for the comments.   For now, we can leave RA and Dec in each QA.  However, the best way to accommodate the scenario of different objects being probed in different QAs is to have the whole set of RA, Dec and Target type listed in one place, and then have each QA record the Fiber IDs they looked at.  A couple of the QAs have these arrays for this purpose, but it is not done uniformly.  Another consideration is that when we have revisited the issue of merged dictionaries, it would make sense to put this information, and other such meta information such as positioner offsets, into a 'header' of the merged dictionary.  Once we have the current round of updates done, I'll want to review this issue, but for now we'll leave them in each QA.

Glad to see you are getting the information into QLF!

Concerning the ranges terminology and arrangement, I was considering two arrays before we implemented, but thought one might feel similar.  Thanks for the clear feedback.  @rstaten will update accordingly.  'GOOD' is also being changed to 'NORMAL'.  For ALARM, however, I would leave this as is.  CRITICAL has an unclear meaning in this context, while ALARM directly indicates that things are bad enough that further action, such as a closer look at least, is required.  ALARM is the term used in BOSS, and in other projects I'm familiar with and I'd prefer to keep this unchanged.

**Comment by rkehoe** [comment]
@afausti. This PR addresses your prior comments.  If no further comments arise, I'll merge later today.

**Comment by afausti** [comment]
@rkehoe @rstaten fine with me.

**Comment by rkehoe** [comment]
Thanks.

**Pull request merged**
