### PR TITLE
Refactor io objects

### PR DESCRIPTION
**Pull request by sbailey**
This PR addresses issue #16 to refactor I/O to return lightweight objects, e.g.

    frame = io.read_frame(filename)

instead of

    wave, flux, ivar, mask, resolution, header = io.read_frame(filename)

This has convenience and greater future flexibility since additional parameters can be added to the frame object without having to change any of the code using it.  It has the downside of somewhat obfuscating what is returned by the I/O functions — you have to go look it up in an object rather than directly seeing the 6 elements.

This touched a lot of files, since those lightweight objects also get passed around for the various algorithm code.  Multiple tests were added as part of this PR.  It passes both the unit tests and the integration test.

### CODE REVIEW

**Comment by sbailey** [comment]
Update: the tests pass on my laptop but the Travis tests failed.  I'll look into that and fix it and update the pull request.  The basic changes can still be reviewed in the meantime.

**Comment by weaverba137** [comment]
There are a few problems here.

1. The Python package needs to internally set up and know the paths to these scripts at compile/test time.
1. Once *executed*, the scripts need to be able to import the desispec package.
1. One can't assume that the same version of Python will execute the scripts, *i.e.* if any non-standard Python needs to be used to execute these scripts, that executable needs to be written into the test.

These are solvable problems, but it would be much easier if the tests simply tested the *components* of the scripts, or imported the `main()` function and executed that.

**Comment by weaverba137** [comment]
I dealt with the internal package paths and environment variables, but in a very fragile way.  I advocate moving away from running scripts and just testing the internal components.

**Comment by sbailey** [comment]
Previously all unit tests were just for components, but I found problems where scripts were failing because component interfaces and their tests had changed but the scripts hadn't been updated, and thus the problems weren't found until later integration tests.  The test_binscripts unit test was an attempt to verify that the scripts themselves worked.  This test works when you already have the git clone configured via PATH and PYTHONPATH, but it was failing the Travis tests because of difficulty bootstrapping itself.

Our previous script guidance was that it was ok for a script to:
  * parse command line arguments
  * perform I/O using desispec.io.* functions
  * call algorithms using the data received from the I/O

but scripts should not include algorithms themselves.

Wrappering all that into a single main() slightly obfuscates the script structure, but could be ok if that would cleanly solve the Travis configuration bootstrapping.

**Comment by weaverba137** [comment]
Those guidelines are fair enough, but when I actually look inside `desi_compute_fiberflat.py` and `desi_compute_sky.py`, I see those are *already* wrappered in `main()` functions.  So why not just put those main functions in the package hierarchy, where they can be easily found by the package tests, and as a bonus, those functions will be found by automated documentation processing?

**Comment by sbailey** [comment]
Forgot to add in the merge comments: this addresses issue #16 .  Apologies for the extra email, but I do want to maintain PR vs. issue linkages in the comments.

**Pull request merged**
