### PR TITLE
show log file for science exposure if reduction failed. Add std star …

### PR DESCRIPTION
**Pull request by zkdtc**
show log file for science exposure if reduction failed. Add std star column.

### CODE REVIEW

**Comment by akremin** [comment]
It looks like this has trouble when a night in the range doesn't exist.

When I try running on the daily directory I get an error:
`desi_proc_dashboard --output-dir=/global/cfs/cdirs/desi/spectro/redux/daily/dashboard/ --output-name=dashboard.html --start-night=20201214 --end-night=20210304`

This runs well for a while and processes some nights successfully but then it fails with the following error message:
```
Traceback (most recent call last):
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 391, in calculate_one_night_use_file
    d_exp =  ascii.read(file_exptable, data_start=2, delimiter=',')
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/ascii/ui.py", line 287, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/ascii/ui.py", line 447, in _guess
    dat = reader.read(table)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/ascii/core.py", line 1165, in read
    self.lines = self.inputter.get_lines(table)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/ascii/core.py", line 304, in get_lines
    with get_readable_fileobj(table,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/utils/data.py", line 237, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202102/exposure_table_20210209.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/k/kremin/workspace/testdesispec/desispec//bin/desi_proc_dashboard", line 17, in <module>
    main(args)
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 264, in main
    nightly_tables.append(nightly_table(night,skipd_expids,show_null=args.show_null,use_short_sci=args.include_short_scis))
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 310, in nightly_table
    night_info = calculate_one_night_use_file(night,use_short_sci)
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 395, in calculate_one_night_use_file
    return calculate_one_night(night, use_short_sci=use_short_sci)
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/py/desispec/desi_proc_dashboard.py", line 726, in calculate_one_night
    _str_frac( nstdstar,            nstdstar_expected), \
UnboundLocalError: local variable 'nstdstar_expected' referenced before assignment
```

**Comment by zkdtc** [comment]
Oops, a tiny bug. Fixed now

**Comment by akremin** [comment]
Thanks for your update over the weekend. Some pros and cons as outlined below:

The stdstar column now exists and the coloring scheme appears to work, which is great. 10/10 was blue, 9/10 yellow, 0/10 red, etc. 

Two outstanding issues:
1) stdstar should go to the left of the cframes column (between "sky" and "cframes").
2) The links for obstype==science still don't work. It's trying to generate links to scripts names science*slurm and logs with science*log. But the names are now prestdstar*slurm OR poststdstar*slurm  depending on the step where we failed.

The fact that I'm seeing a lot of warning messages related to that means you solved the underlying issue that kept it from trying to create these links, but it doesn't yet get the finally result of generating them via linking to the proper script/log names.

**Comment by akremin** [comment]
Unfortunately, I think we've gone backwards a bit. Now I don't see that standard star column at all. Many exposures are now incorrectly flagged as unprocessed even though they have been processed. I also see a lot of warnings about "setfacl" not finding slurm/log files with the old science\*slurm and science\*log filenames. Those are remnants from the old apache web server. We don't need to run that command anymore. I verified that I can view a log file without it.

The stdstar column being missing is new to this commit, I can't guarantee that the missing "processed" rows is new as I could have missed it in the last run. It certainly used to work prior to this PR though.

**Comment by zkdtc** [comment]
Very weird. My version works totally fine and I have fixed the 'setfacl' error. I start a new branch desi_proc_dashboard3 and a new PR to make sure it has the correct version.

**Comment by zkdtc** [comment]
Transfer to PR#1183.

**Pull request closed without merging**
