### PR TITLE
moving py/desispec/data/ccd/ccd_calibration.yaml to /project/projectd…

### PR DESCRIPTION
**Pull request by julienguy**
Moving the ccd_calibration.yaml file from github to the svn repository where the calibration data is.

### CODE REVIEW

**Comment by julienguy** [comment]
I think the calibration data access test is done by the integration test.

**Comment by weaverba137** [comment]
OK. Has the integration test been run on this branch?

**Comment by julienguy** [comment]
yes. the integration test is working at NERSC on this branch.
but, I see it is not checking for the env variable DESI_CCD_CALIBRATION_DATA. I am editing the script to
add a message if this variable does not exist

**Comment by weaverba137** [comment]
That sounds fine.  Merge when ready.

**Comment by moustakas** [comment]
Do the software installation instructions need to be updated?
  https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#SimulatingDESIdata

**Comment by julienguy** [comment]
Good point. I just checked that the installation procedure contains the svn checkout instructions + DESI_CCD_CALIBRATION_DATA variable setup. So it's all good, and +1 for the one that wrote this.
```
...
svn checkout  svn+ssh://${username}@dtn01.nersc.gov/global/project/projectdirs/desi/spectro/calib/svn/ccd_calibration_data/trunk ccd_calibration_data
...
```

**Pull request merged**
