### PR TITLE
default min number of bias lowered to 15

### PR DESCRIPTION
**Pull request by julienguy**
Trivial PR: default min number of bias lowered to 15 instead of 20.
Related to issue #1661 .

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks; I'll add the code to optionally use non-calib zeros, so please don't merge yet.

**Comment by sbailey** [comment]
I added an option `desi_compute_nightlybias --anyzeros` to allow it to use any ZEROs taken during the night, not just those taken as part of the calibration ZEROs sequence (e.g. for night 20210629 without calib zeros, but with zeros taken as part of darks later).

I also replaced the hardcoded skip 2 ZEROs at the start of the night with an option `--skipzeros`, default 2.

tested with a 2 node interactive job and:
```
srun -n 15 -c 8 desi_compute_nightly_bias --mpi -n 20210629 --anyzeros
srun -n 15 -c 8 desi_compute_nightly_bias --mpi -n 20210331 --nskip 0
```
outputs in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/f9

Extra checks on this are welcome, but I'll merge+tag when needed to proceed with Fuji processing.

**Comment by sbailey** [comment]
sphinx docs pass at NERSC, and are failing here due to
```
WARNING: failed to reach any of the inventories with the following issues:
[17](https://github.com/desihub/desispec/runs/5100582587?check_suite_focus=true#step:5:17)
intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
```
let's debug that later and move on with Fuji.

**Comment by weaverba137** [comment]
I think missing scipy docs are a known issue right now.  See *e.g.*, https://github.com/scipy/scipy/issues/15545.  I'd give it another day to stabilize.

**Pull request merged**
