### PR TITLE
QL under-the-hood updates/cleanup

### PR DESCRIPTION
**Pull request by rkehoe**
This PR follows on PR #720 to implement qproc-related updates.  These will include:

- use qframe in flux_calibration step — i.e. Sample calibration vector to individual fiber native grids
- complete process of propagating new fibermap input names to QAs and, where relevant, to QA outputs.

There are several code cleanups also.  When this PR is ready, I will itemize the differences that will be evident to the user (eg. QLF).

### CODE REVIEW

**Comment by rstaten** [comment]
@sbailey As of mock observing, we have not used bootcalib.py for arc processing. However, we have retained this capability in case it would be needed in the future. Is it ok to remove this code for cleanup purposes?

**Comment by sbailey** [comment]
@rstaten yes, go ahead and remove the usage of bootcalib.

**Comment by rkehoe** [comment]
This PR contains the following updates:

- flux calibration now outputs cframe as a qframe file.  This involved resampling the input average flux calibration vector to each fiber’s native grid to accomodate the qframe usage.
- Finished migration of QAs to new fibermap file.  This impacts primarily the naming of two specific members that show up in the output files.  Where before we had IMAGING_MAGS, now the parameter is named FIBER_MAGS.  This refers to the magnitudes calculated from observed imaging survey fluxes, adjusted for the DESI fiber aperture.  Where before there was FIBER_MAGS, now it is named SPEC_MAGS to clearly distinguish it as originating from the integration over the DESI spectral readout.
- Remove obsolete capability of grouping of QA outputs into JSON files per pipeline step
- Remove obsolete code specifying algorithm lists outside of qlconfig inputs
- Remove obsolete bootcalib pipeline algorithm from procalgs

There will also be an update to the XWSigma calculation, which will not impact the output naming or arrangement.

For the user of QL, the changes that will be observed are the following:

- in the GENERAL_INFO block of the JSON, IMAGING_MAGS is replaced with FIBER_MAGS.  While the quantity is calculated a bit differently, it has the analogous signiticance as the original parameter and should be used in its place everywhere.
- In the CHECK_SPECTRA portion of the JSON, the FIBER_MAGS metric is replaced by the SPEC_MAGS member.  It is calculated the same and should be used in the older metrics place everywhere.  So one QA plot is now FIBER_MAGS vs SPEC_MAGS, rather than the old IMAGING_MAGS vs FIBER_MAGS.  
- this PR is different than the prior version used in QLF tests in that it also takes the new fibermap file format as input and that will need to be used going forward.

@felipelm This PR is ready for testing with QLF.  We have removed the requirement of an input flux calibration vector file until Issue #718 is completed.  The flux calibration applies a flat calibration vector to get the normalized result in the ballpark of correct when no input file is present.  This hack is a temporary measure to allow QL to run with this missing input, and this is the way to test for now.  So red petals may show up in testing, and we can attempt to minimize that in the meantime.  But QLF should be able to run and utilize QL outputs once the three changes above are accomodated.

**Comment by felipelm** [comment]
Thanks @rkehoe I tested and here are the issues I found:

- Science mergedQA `SKYRBAND` was in `CHECK_SPECTRA` and now is at `APPLYFLUXCALIBRATION`. I didn't see this stage in [trac](https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/QuicklookQAOutputs/Science)
- Science QAs `DELTAMAG TGT` and `SNR` from `CHECK_SPECTRA` are missing in mergedQA
- Flat is working fine
- Arc is working fine

I'm keeping the necessary changes on https://github.com/desihub/qlf/pull/284

**Comment by rkehoe** [comment]
Thanks @felipelm.  That shouldn't be happening.  We'll update you when it's fixed.

**Comment by rstaten** [comment]
@felipelm This should now be fixed, thanks for testing.

**Comment by rkehoe** [comment]
@felipelm, @rstaten. Let’s hold off on QLF testing until the Check_HDUs QA is removed from the qlconfig files, as decided in Issue #708.  So in addition to the differences for QLF to note stated above, they will see an absence of the content under the CHECK_HDUs task in the merged QA output.  QLF will still display it, but will obtain this information directly.  My understanding is that hte exposure # checking done in the QL QA will also be done by DOS.

Since it exists, we will still leave this QA in QL for use in running without QLF/DOS, such as in testing, etc.

**Comment by rkehoe** [comment]
@felipelm  Please feel free to test this PR now.  The only difference from my notes on Friday are that this version will now omit the CHECK_HDUs task from the output merged JSON files.  This includes the metrics in that task, which ultimately will need to be accessed by QLF.  But for this PR, we would like to just make sure that QLF can otherwise process the QL outputs, with the changes from 3 days ago noted.

Travis tests are successful, so since this PR concludes other Issues, I will merge it once we know the QLF tests are done successfully.

**Comment by felipelm** [comment]
@rkehoe Science mergedQA for `exposure 3578 night 20191001 camera z7` is returning `"PROGRAM": "DARK,GRAY,BRIGHT"` in the `GENERAL_INFO` while it should be `DARK`. This breaks most of the plots.
Flat and Arc are ok

**Comment by rkehoe** [comment]
Thanks for the commit @rstaten!  

@felipelm Sorry for the glitches here.  We are working on some solution to ease some of the brittleness that occurs.  But for now, this PR should run okay for you.  Please indicate how it goes at your earlier convenience.  It would be great to clear this PR and the connected tickets elsewhere.

**Comment by rkehoe** [comment]
@felipelm  One item here, too.  When you do run, if successful could you comment on GitHub here on where to find the plots output from the runs?  It would be good to look at those.

**Comment by felipelm** [comment]
@rkehoe 

Ran using `exposure 3578 night 20191001 camera z7` 

- MergedQA `GENERAL_INFO` `RA` and `DEC` are now `null`
- `DELTAMAG` and `SNR` are missing from science mergedQA `CHECK_SPECTRA`

You can see the plots by [running QLF](https://github.com/desihub/qlf/blob/master/README.md) we don't make pngs if that is what you are asking.

**Comment by felipelm** [comment]
@rstaten sure check your email

**Comment by rkehoe** [comment]
Okay, some emails and Slack channel discussion later, and it appears that there are some environment differences causing a difference in what QLF sees.  In this case, to QAs crash (Integ, SNR) as seen in the QL log files.  In the Integ case, @rstaten has identified this as speclite, which is used to obtain the broadband filter response, was not available in the environment.  @felipelm Can you confirm here that the DELTAMAG absence has been rectified?

The other problem was present also in master (thanks @felipelm for testing!) is related to SNR and appears to be related to some changes made recently to the Target list in the fiber map file and how QL accesses it.  This will need to be addressed immediately, but I am going to go ahead and merge this otherwise working branch.  The remaining problem does not show up in standalone running, and there are several other things in this PR that we need to conclude.

@sbailey This PR addresses and completes Issues #685, #706 and #708.  These can be closed.

This PR may address issue #705, and we await feedback on that.  This PR attempted to finish Issue #698, but the remaining glitch, seemingly environment dependent, seen by QLF still needs to be resolved.

Once I check a couple items, I will merge this branch later today.

**Comment by felipelm** [comment]
DELTAMAG and SNR are still broken but @rstaten said they are related.

_logs are upsidedown_

```
2018-11-21 18:25:18,978 QuickLook INFO : Step SkySub_QP finished.
KeyError: 'STD_FAINT'
    mask |= self._bits[name].mask
  File "/app/desiutil/py/desiutil/bitmask.py", line 215, in mask
    yes |= (desi_target & desi_mask.mask('STD_WD|STD_FAINT|STD_BRIGHT')) != 0
  File "/app/desispec/py/desispec/fluxcalibration.py", line 39, in isStdStar
    stdfibers = np.where(isStdStar(frame.fibermap['DESI_TARGET']))[0]
  File "/app/desispec/py/desispec/qa/qalib.py", line 691, in SNRFit
    qadict,badfibs,fitsnr = qalib.SNRFit(frame,night,camera,expid,objlist,param,fidboundary=fidboundary)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1815, in run_qa
    return self.run_qa(frame,inputs)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1773, in run
    res=self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/quicklook/qas.py", line 28, in __call__
    res=qa(inp[0],**qargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 140, in runpipeline
Traceback (most recent call last):
2018-11-21 18:25:18,874 QuickLook WARNING : Failed to run QA Calculate_SNR. Got Exception 'STD_FAINT'
```

```
2018-11-21 18:26:56,272 QuickLook INFO : Step ApplyFluxCalibration finished.
KeyError: 'STD_FAINT'
    mask |= self._bits[name].mask
  File "/app/desiutil/py/desiutil/bitmask.py", line 215, in mask
    yes |= (desi_target & desi_mask.mask('STD_WD|STD_FAINT|STD_BRIGHT')) != 0
  File "/app/desispec/py/desispec/fluxcalibration.py", line 39, in isStdStar
    starfibers=np.where(isStdStar(frame.fibermap['DESI_TARGET']))[0]
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1699, in run_qa
    return self.run_qa(frame,inputs)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1583, in run
    res=self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/quicklook/qas.py", line 28, in __call__
    res=qa(inp,**qargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 142, in runpipeline
Traceback (most recent call last):
2018-11-21 18:26:56,213 QuickLook WARNING : Failed to run QA Integrate_Spec. Got Exception 'STD_FAINT'
```

**Comment by rkehoe** [comment]
@felipelm Thanks for the quick test.  This has to be some sort of environment issue.  This will have to be the highest priority of the next PR.

**Comment by sbailey** [comment]
`STD_FAINT` was introduced as a targeting bit in desitarget version 0.23.0.  If QLF is using an earlier version of desitarget then they will get a KeyError.

Overall it would be highly preferable if the QL team can get QLF running locally so that they can test for problems like this before passing off to the QLF team, instead of requiring QL/F integration tests to be performed and debugged via email/github/slack.

**Comment by rkehoe** [comment]
@sbailey  Thanks for the note.  We were aware of when the STD_FAINT had been introduced, but I hadn't thought of the desitarget version.  It is good to know this.  Going forward, I think we will want to encapsulate what versions of all dependent repos we are using, in addition to your suggestion.

We have attempted to run QLF locally but recently this has run into an error.  @felipelm has been helping us with this and we will certainly solve it next.  This, and making sure the above problem are gone conclusively and there are no others lurking, will be the highest priority next.

Since QLF integration was not the primary task of this PR, and travis tests look fine, I will merge now.

**Comment by felipelm** [comment]
Great thanks @sbailey , using desitarget 0.23.0 fixed SNR but Deltamag still got an error:

```
2018-11-21 21:49:18,938 QuickLook INFO : Step ApplyFluxCalibration finished.
OSError: /app/speclite/speclite/data/filters/decam2014-g.ecsv not found.
    raise IOError("%s not found." % path)
  File "/conda/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 616, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/conda/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 260, in open
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    rfile=np.genfromtxt(responsefile)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1646, in run_qa
    return self.run_qa(frame,inputs)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1583, in run
    res=self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/quicklook/qas.py", line 28, in __call__
    res=qa(inp,**qargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 142, in runpipeline
Traceback (most recent call last):
2018-11-21 21:49:18,888 QuickLook WARNING : Failed to run QA Integrate_Spec. Got Exception /app/speclite/speclite/data/filters/decam2014-g.ecsv not found.
```

Seems like this file is missing `/speclite/speclite/data/filters/decam2014-g.ecsv`

**Comment by sbailey** [comment]
`desispec/qa/qa_quicklook.py` line 1641 assumes that speclite is checked out (but not installed) in a very specific location:
```
responsefile=os.path.join(os.environ['DESI_PRODUCT_ROOT'],'speclite','speclite','data','filters','{}.ecsv'.format(responsefilter))
```
That will not work in many cases, including how speclite is installed at NERSC.

Instead, if quicklook should find this file via:
```
# e.g. response_filter = 'decam2014-g'
from pkg_resources import resource_filename
filter_file = resource_filename('speclite', 'data/filters/{}.ecsv'.format(response_filter))
```

It would be even better if QL could use the speclite infrastructure for evaluating filters, e.g.
```python
# e.g. response_filter = 'decam2014-g'
import speclite.filters
filter_response=speclite.filters.load_filter(response_filter)
gmag = filter_response.get_ab_magnitude(flux, wave)
```
However, speclite will complain if your wavelength range doesn't fully cover the wavelengths of the filter (which go beyond the wavelengths covered by DESI spectra), so if you really want to use that filter you'll need to do something like extend the wavelengths and zero-pad fluxes.

**Comment by rkehoe** [comment]
@sbailey  Thanks.  We'll clean this up.

**Pull request merged**
