### PR TITLE
QL config update and fibermap conform

### PR DESCRIPTION
**Pull request by Srheft**
This PR:

* updates arc configuration file
* migrates to science config for all three science programs [dark,gray,bright]
* moderate edits to XWSigma and SNR, calculation algorithm and few other QA calculations

@sbailey please see [ticket #698](https://github.com/desihub/desispec/issues/698). 
Keeping with our general rule, this PR will be tested in QLF  [with new format data] before merge.

### CODE REVIEW

**Comment by Srheft** [comment]
@felipelm since I don't have writing privileges there please copy the new redwood data set [night 20200515] that QL/F have to work with, from this address on NERSC: /project/projectdirs/desi/datachallenge/redwood/20200515 onto desi-1. 

This PR only has two changes for QLF:

1. Exactly where it exists in the mapping for the Science exposures, XWSigma should be added to CHECK_CCD step for **arc exposures processing** as well. 

2. instead of having three configuration files for science exposure processing (they were called qlconfig_darksurvey.yaml, qlconfig_brightsurvey.yaml, qlconfig_graysurvey.yaml), there is now only one configuration file called **qlconfig_science.yaml**.  QLF should just make sure to call this config file for all science processing regardless of the dark/gray/bright programs. The internal changes to this file should not affect QLF.  The merged json file has the same structure and same status key names. 

let me know if it would be helpful to create a PR for the changes on the qlf side.  Thanks.

**Comment by felipelm** [comment]
@Srheft you have the same permissions as I because we use the same `quicklook` user.

Ok, I'll make a PR on qlf with these changes and reference here.

**Comment by Srheft** [comment]
@felipelm last time I tried to copy data on /data directory it said permission denied. Will you copy the redwood data or I should go ahead and do that?

**Comment by felipelm** [comment]
@Srheft I think @sbailey protected the exposures directory to avoid changing or deleting the files.

I also don't have the permissions to change the raw exposures directory.

**Comment by Srheft** [comment]
Ok Thanks for letting me know, @felipelm  This week is the Barcelona meeting week so hopefully at some point @sbailey  find some time to copy the data there.  But this PR should be working with 20191001 too so please let me know if the two changes I mentioned above require me to create a PR for qlf.

**Comment by felipelm** [comment]
@Srheft 

Got errors running `20191001` exposure `00003578` camera `b0`:

```
2018-10-16 13:19:24,153 QuickLook INFO : Running Calc_XWSigma
UnboundLocalError: local variable 'refval' referenced before assignment
    reflist=isinstance(refval,(np.ndarray,collections.Sequence))
  File "/app/desispec/py/desispec/quicklook/qas.py", line 200, in __call__
    res=qa(inp,**qargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 302, in runpipeline
Traceback (most recent call last):
2018-10-16 13:19:24,126 QuickLook WARNING : Failed to run QA Count_Pixels. Got Exception local variable 'refval' referenced before assignment
2018-10-16 13:19:24,126 Count_Pixels WARNING : No reference given. Update the configuration file to include reference value for QA: Count_Pixels
2018-10-16 13:19:24,053 QuickLook INFO : Running Count_Pixels
UnboundLocalError: local variable 'refval' referenced before assignment
    reflist=isinstance(refval,(np.ndarray,collections.Sequence))
  File "/app/desispec/py/desispec/quicklook/qas.py", line 200, in __call__
    res=qa(inp,**qargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 302, in runpipeline
Traceback (most recent call last):
2018-10-16 13:19:23,967 QuickLook WARNING : Failed to run QA Get_RMS. Got Exception local variable 'refval' referenced before assignment
2018-10-16 13:19:23,967 Get_RMS WARNING : No reference given. Update the configuration file to include reference value for QA: Get_RMS
2018-10-16 13:19:23,450 QuickLook INFO : Running Get_RMS
UnboundLocalError: local variable 'refval' referenced before assignment
    reflist=isinstance(refval,(np.ndarray,collections.Sequence))
  File "/app/desispec/py/desispec/quicklook/qas.py", line 200, in __call__
    res=qa(inp,**qargs)
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 302, in runpipeline
Traceback (most recent call last):
2018-10-16 13:19:23,394 QuickLook WARNING : Failed to run QA Bias_From_Overscan. Got Exception local variable 'refval' referenced before assignment
2018-10-16 13:19:23,393 Bias_From_Overscan WARNING : No reference given. Update the configuration file to include reference value for QA: Bias_From_Overscan
...
```

**Comment by Srheft** [comment]
Yeah this is one change I had to make because of the redwood data. I'll see how can i make it to work for both. Lack of key 'PROGRAM' made me do some changes. Could you try an arc and make the change I mentioned to arc processing?

**Comment by felipelm** [comment]
Arc ran fine but arc XWsigma plot didn't work so I'm trying to debug it now.

**Comment by Srheft** [comment]
Yeah this PR has added xwsigma in arc. Thanks.

**Comment by felipelm** [comment]
@Srheft seems like `GENERAL_INFO` `ra` and `dec` are `null` values and we expect an `array` size `500` for each.

**Comment by felipelm** [comment]
Running `20191001` exposure `00003571` camera `b0`

**Comment by Srheft** [comment]
calibration frames [flat and arc] are not pointed at any astronomical object so the RA DEC arrays are empty. one would only look for them in a science exposure.

**Comment by felipelm** [comment]
@felipeaoli care to give your input on this plot?

**Comment by Srheft** [comment]
you mean the xwsigma plot for arc?  the xwsigma plot for any flavor is created here: [xsigma plot](https://github.com/desihub/desispec/blob/e1b5f89fdde66b14bacd0dd5f1d0d6a4fda49648/py/desispec/qa/qa_plots_ql.py#L182) 

ql-xwsigma-b0-00000001

**Comment by felipeaoli** [comment]
Thanks @Srheft and @felipelm . I'm doing a large revision on the plots and I'll add this one.

**Comment by Srheft** [comment]
Great, don't hesitate to let me know what you need.

**Comment by Srheft** [comment]
@felipelm please use the latest commit and see if a science exposure gets processed fine now.

**Comment by felipelm** [comment]
Got this error now:

```
2018-10-16 18:32:33,026 Integrate_Spec CRITICAL : QL Integrate_Spec : REFERENCE(2) and RESULT(4) 
2018-10-16 18:32:37,554 Calculate_SNR CRITICAL : QL Calculate_SNR : REFERENCE(2) and RESULT(4) are of different length!
```

Many plots broke because some metric keynames has changed.
```
BIAS_AMP_REF, XWSIGMA_REF, NGOODFIB_REF, PEAKCOUNT_REF, SKYCONT_REF, DELTAMAG_TGT_REF, FIDSNR_TGT_REF
```

Lastly I'm getting `UNKNOWN ` status:

```
"FIDSNR_TGT_STATUS": "UNKNOWN",
"DELTAMAG_TGT_STATUS": "UNKNOWN",
```

Same science exposure above.

**Comment by Srheft** [comment]
@felipelm the 'UNKNOWN' status for SNR and Integshall be expected for now. This comes from the difference between redwood [night 20200515] and Mock obs data [night 20191001] and I am waiting on @sbailey to comment on this [ticket](https://github.com/desihub/desispec/issues/698).  Looking at JSON file, both SNR and Integ have calculated the QAs but the reference values are now conformed to the new OBJECT list in redwood. 

You have nicely added a color [gray and black or another colour if gray is reserved for "not gone- ongoing process"] to the list of colours for petals. One colour has to be assigned to a condition where the pipeline is completed, all the QA s are calculated, but one or few QAs couldn't have any status assigned to them. This is going to happen for some QAs where the references are either not provided or have a typo, or the format of the ref and the calculated QAs don't match because some last minute change in the fibermap wasn't reported to QL/F resulting in a case where a calculation can not be done for a QA  due to some missing keys that the algorithm is looking for.  If a petal stays gray[or purple, etc], that would immediately alert the users that a new format data is being used and some algorithmic changes should happen.  So the 'UNKNOWN' status should have a color and to be considered a possibility just like 'ALARM' or 'WARNING' [at least for now].  

Let me know if this makes sense and/or you have any comment here. Thanks.

**Comment by Srheft** [comment]
@felipelm 

@sbailey says that we should for now work with mock obs data [20191001] so can you please run an example  flat/arc/science from 20191001 and confirm here that this PR doesn't break QLF so that we could go ahead and merge this?
Thanks.

**Comment by felipelm** [comment]
@Srheft 

Many plots are broken because some metric keynames changed.
```
BIAS_AMP_REF, XWSIGMA_REF, NGOODFIB_REF, PEAKCOUNT_REF, SKYCONT_REF, DELTAMAG_TGT_REF, FIDSNR_TGT_REF
```

Seems like `_REF` was removed from all of them.

**Comment by Srheft** [comment]
@felipelm 
OK you mean the bokeh plots, right? in the qlconfirm_science.yaml. Now _REF keys have 'PROGRAM' also as part of their name. For instance, BIAS_AMP_REF for a cience frame that is in PROGRAM=DARK, is called  BIAS_AMP_DARK_REF and so on. However the bokeh plots get the key PROGRAM, then thay have to look for that specific QA_PROGRAM_REF. Please let me know if this is not clear.

**Comment by felipelm** [comment]
@Srheft ok I get it but please explain to me why did you need to make this change.

In my view merging the 3 science files into one and doing what you described will repeat all the references for each program on all science exposures. I don't see the gain and prefer the old one that doesn't repeat unnecessary data.

Sorry, maybe I missed an explanation somewhere...

**Comment by Srheft** [comment]
@felipelm very good question! thanks for asking and please always let QL folks know if things don't make sense. We are making a conscious effort to only make changes that higher ups asked us to do. 
When we were wrapping up the mock obs week, @sbailey asked if we could A: get the reference values for QAs from the configuration files not from the first created json file and B: have only one configuration file for science frames [we had three until this PR: darksurvey, brightsurvey, graysurvey.yaml]. Last PR delivered request A and this PR is delivering request B. I wish Stephen wasn't as busy as he is so he could comment but this is why I made this change. Now regardless of the type of observing program that is happening in the observing night, QLF just uses the **science** config. It was supposed to made things less complicated for QLF. maybe you feel differently about this and please let everyone know if you do.

**Comment by felipelm** [comment]
@Srheft there are two references missing in the mergedQA 

`PEAKCOUNT_{PROGRAM}_REF` and `SKYCONT_{PROGRAM}_REF`

**Comment by Srheft** [comment]
@felipelm could you clarify one point:
I was under the impression that QLF reads in the STATUS from the screen log[or json-but you wanted stats to also be written on screen log] and uses those to colour petals. Why and how bokeh plots need/use REF values?

**Comment by felipelm** [comment]
@Srheft on the monitor screen we use the status from the screen log but we ingest and use the values from the mergedQA to show on the QA screen.

The references are used on a table that comes with the plots:

image

@felipeaoli can explain better but we use the `_REF` values from mergedQA on this tables.

**Comment by Srheft** [comment]
Oh so REF values are not an integrated part of plots but you show them in tables for user info [which is useful to have] 
Please let me know if now you get all you need. Thanks.

**Comment by felipeaoli** [comment]
@Srheft we also use reference values  in color maps for some cases.

**Comment by Srheft** [comment]
@felipeaoli oh no only I did not know that, I also don't know what color map in this context :)

@felipelm is everything ok with the science exposure runs now?

**Comment by felipelm** [comment]
@Srheft just finish testing and everything seems ok now.

**Comment by Srheft** [comment]
@felipelm et al thank you very much!  I'll proceed with the merge after @rkehoe gave his final remarks.

**Comment by Srheft** [comment]
@felipeaoli did you merge this PR?

**Comment by Srheft** [comment]
@felipelm could you let me know why this merge happened?

**Comment by felipeaoli** [comment]
sorry, I was answering another PR and made a mistake

**Comment by Srheft** [comment]
@felipeaoli I don't see this being reverted. I still see this branch merged.

**Comment by felipelm** [comment]
@felipeaoli @Srheft you have to merge the other PR to revert the changes on master and open a new one with this changes

**Comment by Srheft** [comment]
@felipelm i don't know what is going on here.

**Comment by rkehoe** [comment]
@felielm and @felipeaoli Please do not merge QL branches/PRs.  These should only be merged by @srheft or myself (or @sbailey) because we are aware of any internal reviews, tests or edits we are pursuing.  PR #701 unfortunately does not retain the comment history, and I am unclear on the status of master at this point.  @sbailey could you please indicate if master has still the merged code, or has been returned to the pre-merge basis?

Please do no further merge until I can finish examining the final edits.  Assuming master is in a pre-merge state, we will merge the outstanding PR.

**Comment by felipeaoli** [comment]
Sure @rkehoe . This was exclusively my fault, I accidentally merged it. I'm very sorry

**Comment by rkehoe** [comment]
@felipeaoli  I accept your apology, but then why did you create another PR #702?   I have to be clear: do not continue to try to 'fix' this situation in desispec.  

@srheft  This PR (#699) looks good and accomplishes the tasks of converging science configs, evening out calibration exposure processing chains, and further improving fitting QAs like XWSigma and SNR.  There appears to be another PR built to restore this one, so I am further confused as to the status of this code.  I have only one suggestion before signing off on this PR as it was originally before the accidental merge: I think you can go ahead and remove the now obsolete _darksurvey_, _brightsurvey_ and _graysurvey_configs.  We just have _science_ now.  I have some other questions/suggestions, but aside from removing the obsolete configs, these should not hold up a final merge of this code.

If master has been restored to pre-merge status, then this PR (#699) should still be able to be remerged into master.  We can chat about how to proceed offline.  I will contact you this afternoon.

**Comment by Srheft** [comment]
@rkehoe Thanks. given the circumstances, I prefer to withdraw from any further action on this PR until @sbailey  could take a look and do what has to be done. I'll apply your suggestions in the next PR.

**Comment by sbailey** [comment]
@rkehoe once a PR has been merged, it can't be re-merged.  What can be done is open a new PR to undo (revert) the accidental merge changes (which @felipeaoli did with PR #701), and then when ready open a *new* PR to perform the same merge as the original PR when ready (which is what he prepared with PR #702, which correctly references this PR for traceability, but hasn't been merged yet).

@felipelm and @Srheft : please deploy the equivalent of PR #702 and desihub/qlf#253 on http://desi-1.kpno.noao.edu:9090 .  When that is tested and it all works together we can proceed with merging those two PRs.  desi-1 was offline yesterday for cooling system maintenance but it is back today.

**Comment by felipelm** [comment]
@Srheft @sbailey 

I've made the deploy of #702 using https://github.com/desihub/qlf/pull/253 on  http://desi-1.kpno.noao.edu:9090

Ran arc, flat, and three science (dark, gray, bright) exposures and seems to be working fine. All plots are showing with the changes made using the new science config file and xwsigma is now showing on arcs CHECK_CCDs.

Seems like the production database is not up so http://desi-1.kpno.noao.edu:9000/ backend is offline.

**Comment by Srheft** [comment]
@felipelm great, thank you.

**Comment by rkehoe** [comment]
@sbailey. Thanks for the clarification.  I had thought I had seen a different usage, so good to know going forward.  

@srheft Please merge the final PR #702 when any remaining updates tests are done.  If you prefer to hold the original updates to #699 for a subsequent PR, that’s okay for me.

**Comment by sbailey** [comment]
@Srheft @felipelm @rkehoe : let's merge #702 and deishub/qlf#253 and then make new tags.  I have meetings for the next 2 hours, but if you haven't made the merges by then I can do it.  I'll submit tickets for any problems I find on 
http://desi-1.kpno.noao.edu:9090/ so that we don't further delay these PRs.  Thanks.

@rkehoe from `git diff`, #699 and #702 have identical code changes and differ only by #702 having more recent `changes.rst` and `_version.py` updates.  i.e. I don't think there are any "original updates to #699 for a subsequent PR" that are not already included in #702.  If you know of something that is missing from #702, please point that out.  Thanks.

**Comment by rkehoe** [comment]
@sbailey. There were three potential small updates, one of which was mentioned in my comment 5 days ago (eg. Removing the now obsolete dark/gray/bright Survey configuration in favor of the merged config).  Two others I discussed offline w/@Srfheft, one I remember was about choice of arc-lines to look at in the configuration.  None of the three were implemented yet into #699 — they were about to be before the accidental merge.  They are not necessary for this PR or #702, but we agreed to do them.  They can be in a subsequent PR, for sure.

**Comment by sbailey** [comment]
@rkehoe thanks for the info.  +1 for including these changes in separate smaller PRs.  The code from this PR has been merged via #702 and tagged as desispec/0.25.0 .

**Pull request merged**
