### PR TITLE
Ql yaml2json

### PR DESCRIPTION
**Pull request by Srheft**
@rstaten please review this branch and comment. This branch accomplished these tasks:

1-  Creating individual and merged JSON files in addition to the YAML files 
2-  Removing the repeated metrics in the merged JSON due to merging dictionaries with similar passed info like the repeated RA/DEC.
3-  To add a GENERAL_INFO block for the merged JSON files that contains:
 B_PEAKS
 R_PEAKS
 Z_PEAKS
 RA
 DEC
 STAR_FIBERID
 ELG_FIBERID
 SKY_FIBERID
 QSO_FIBERID
 LRG_FIBERID
-----------------------------------------------
Based on the comments we received for the format of the arrays in this block, the RA/DEC arrays are 500 floats [%.5f] to save more bits.  
This general info block will undergo a major change once ql_snr is merged. So far we've ahd 35% size reduction in the merged json/yaml file. The same general info section is added to the merged yaml file as well. 

NOTE DUE TO RECENT CHANGES IN THE MASTER:
I verified that a local merge of this branch with the recently changed master did not have any merge conflict. The QL runs fine as long as before running the pipeline:

1- FIBERFLAT relocation:
mv $QL_SPEC_REDUX/calib2d/night/fiberflat-camera-flatExpID.fits $QL_SPEC_REDUX/**exposure**/night/fiberflat-camera-flatExpID.fits

2- PSFBOOT rename and relocation:
mv $QL_SPEC_REDUX/calib2d/psf/night/psfboot-camera.fits $QL_SPEC_REDUX/exposures/night/**expid**/psfboot-camera-**EXPID**.fits

The only changes would be in our environment variables when installing quicklook so that it matches the changes that are already made in the bootcalib.py and meta.py.

Please challenge my above claim every which way, Ryan! we will add a verification test in test-ql.py so that address and name changes would create an error in the near future. 

@rkehoe, after Ryan verifies my claims, the ball would be in your court for a final review and eventual merge. 

Thanks,
srh

### CODE REVIEW

**Comment by rstaten** [comment]
In terms of the merged file modifications, everything looks great including the reduction in size (one example is a reduction of 1.3M to 732K). Also, in both the merged files and individual QA files, the yaml and json files are equivalent in terms of output. Every task you mention is included appropriately.

Regarding the new updates to master, the comments you mention about changing the file names/locations are correct, but there are some other points. One can leave the QuickLook environment variables as they are, but our configuration will need to be updated. Also, when the current psfboot file is changed to:

$QL_SPEC_REDUX/exposures/night/expid/psfboot-camera-EXPID.fits

as you mention, the exposure id necessary for the file to be found is the science exposure ID and not the arc exposure ID, so the psfboot will not be found if it contains the actual arc exposure ID. This is also assuming that one already has these calibration files. In order to generate these files now, there are a few changes to QuickLook that must be made (fortunately they are not extensive). I have made the necessary changes in a local branch and ensured that there is nothing intrinsically wrong with the pipeline, just several setup issues.

Once this PR is merged, I will pull master to the ql_snr branch and make these necessary changes there.

**Comment by rkehoe** [comment]
@srheft  This update looks ready.  Thanks also for the cleanup of the fiber_mag metric naming, in addition to the common block and json implementations.

I second the effort to conclude this branch now, even with the environment variable and other items.  It will be important to address these right away -- if that can be in the ql_snr branch, that is acceptable.

**Comment by weaverba137** [comment]
Is there any reason not to delete this branch?

**Comment by Srheft** [comment]
It is merged to master so I don't see any reason not to.

**Pull request merged**
