### PR TITLE
Sky Continuum in offline QA

### PR DESCRIPTION
**Pull request by profxj**
This PR has two objectives:

- Implement the Quicklook QA algorithm for sky continuum into offline
- Begin moving QA parameters into desispec_param.yml

The first item required refactoring the main algorithm into qalib.py
The second cleans up the organization of QA.

Travis is giving occasional failures related to downloading speclite (not on 
specific tests related to this repo).

The test_binscripts test tickles all of the new code.

### CODE REVIEW

**Comment by gdhungana** [comment]
@profxj Thanks, internal refactor looks good. For future, we should also move other QL params to the desispec_param.yml as well taking this example. @rstaten Please confirm on the results with an example QL test. Otherwise looks fine.

**Comment by profxj** [comment]
Yes, assuredly; I plan to move all the other QA params there but I wanted
your buy in before doing so.

**Comment by rstaten** [comment]
Everything looks fine by me, QL runs on all channels without a problem.

**Comment by profxj** [comment]
Ready to merge @rkehoe ?

**Comment by sbailey** [comment]
Test failure is due to sphinx version problem that was fixed with PR #439 . This should be OK to merge once you guys are in agreement that the code is ok.

**Comment by profxj** [comment]
Am waiting for @rkehoe to give his input.

**Comment by rkehoe** [comment]
@gdhungana, @profxj The QL params are all included in the QuickLook qlconfig_dark.yaml already, which is needed by QuickLook at startup time.  Down the road we will want to consider whether online and offline can use a common configuration system.  But for now, they accomplish somewhat different tasks and are used very differently in their respective pipelines.

I'm really glad to see this effort to integrate more QA code across the online/offline divide.  I'm taking a look at the modifications and will provide some feedback shortly.

**Comment by profxj** [comment]
Merging.

**Pull request merged**
