### PR TITLE
Teststand

### PR DESCRIPTION
**Pull request by julienguy**
This PR to try and synchronize the teststand branch with master before they diverge.
New features are mostly in preprocessing with some minor changes to bootcalib.
- Preprocessing reads by default a calibration data file that is in the repo in
https://github.com/desihub/desispec/blob/teststand/py/desispec/data/ccd/ccd_calibration.yaml
  This file specifies for each camera, CCD name, for a given range of dates, ICS and FEE version 
  - gains (for the moment=1)
  - saturation levels (need to measure), see issue #307 
  - electronic cross-talks for all amplifiers combinations (now measured), see issue #305 
  - bias subtraction method (choice per amp), see issue #306 
  - bias,dark,mask fits files to be found in directory given by env. variable DESI_CCD_CALIBRATION_DATA

I have put a mirror of it at NERSC in ```/project/projectdirs/desi/users/jguy/teststand/calibration_data```
This will eventually go to a SVN repo.

- New scripts are in the bin directory to produce bias,dark,mask files, see issue #330 
  - desi_compute_bias
  - desi_compute_dark
  - desi_compute_mask
  - desi_compute_crosstalk

- An example run at NERSC is in ```/project/projectdirs/desi/users/jguy/teststand/20161221```
  It would be nice if someone from datasystem test this.

### CODE REVIEW

**Comment by sbailey** [comment]
This is great stuff to have (I especially liked the cross talk correction), but a little cleanup is needed before we can merge:
* @tskisner how close are you to finishing your pipeline scaling changes?  Could you merge and tag that prior to merging this so that we don't break something out from under you?
* preproc changes are causing test failures, e.g.
```
ERROR: test_mask (desispec.test.test_preproc.TestPreProc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desispec/py/desispec/test/test_preproc.py", line 131, in test_mask
    image = preproc(self.rawimage, self.header, mask=False)
TypeError: preproc() takes at least 3 arguments (3 given)
```
* We'll also need placeholders in the ccd_calibration.yaml file for simulation data covering all 30 channels.  Missing these causes other failures:
```
ERROR: test_io (desispec.test.test_preproc.TestPreProc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desispec/py/desispec/test/test_preproc.py", line 157, in test_io
    b0 = io.read_raw(self.rawfile, 'b0')
  File "/home/travis/build/desihub/desispec/py/desispec/io/raw.py", line 49, in read_raw
    img = desispec.preproc.preproc(rawimage, header, primary_header, **kwargs)
  File "/home/travis/build/desihub/desispec/py/desispec/preproc.py", line 342, in preproc
    calibration_data = read_ccd_calibration(header, primary_header, ccd_calibration_filename)
  File "/home/travis/build/desihub/desispec/py/desispec/preproc.py", line 225, in read_ccd_calibration
    raise KeyError("Cannot find  data for camera %s in filename %s"%(cameraid,filename))
KeyError: 'Cannot find  data for camera b0 in filename /home/travis/build/desihub/desispec/py/desispec/data/ccd/ccd_calibration.yaml'
```
I'd suggest handling these as just another set of CCD IDs that we use for simulation.  Speaking of which, I don't see the CCD serial number / ID in the ccd_calibration.yaml file.  Is that not included in the DOS headers yet?

* Could you itemize the new required keywords?  Should we have a fallback if keywords like DOSVER aren't found, or should that be a genuine failure?
```
ERROR: test_preproc_script (desispec.test.test_preproc.TestPreProc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desispec/py/desispec/test/test_preproc.py", line 280, in test_preproc_script
    desispec.scripts.preproc.main(args)
  File "/home/travis/build/desihub/desispec/py/desispec/scripts/preproc.py", line 105, in main
    ccd_calibration_filename=ccd_calibration_filename
  File "/home/travis/build/desihub/desispec/py/desispec/io/raw.py", line 49, in read_raw
    img = desispec.preproc.preproc(rawimage, header, primary_header, **kwargs)
  File "/home/travis/build/desihub/desispec/py/desispec/preproc.py", line 342, in preproc
    calibration_data = read_ccd_calibration(header, primary_header, ccd_calibration_filename)
  File "/home/travis/build/desihub/desispec/py/desispec/preproc.py", line 230, in read_ccd_calibration
    dosver=primary_header["DOSVER"].strip()
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/io/fits/header.py", line 152, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1729, in _cardindex
    raise KeyError("Keyword %r not found." % keyword)
KeyError: "Keyword 'DOSVER' not found."
```

**Comment by tskisner** [comment]
Some thoughts:

1.  We should really squash these commits to one before merging...
2.  I see that some command line options were added to bootcalib and fiberflat.  Are the defaults sufficient for most cases?  If not, we should add these to the default options.yaml file.
3.  The preproc is not currently run as part of the pipeline (it starts at bootcalib).  So assuming that bootcalib and fiberflat still run with the same options (or with default values for new options), then I don't think it will break anything I am working on.  All my major changes are already merged, and I am just tweaking the slurm script generation for use with shifter.

In any case, we should first get the tests working again.

**Comment by dkirkby** [comment]
Why squash?  Those look like useful commit messages and I find it helpful to have a detailed history, especially with `git blame` and `git bisect`.

**Comment by tskisner** [comment]
Many of these commits are small or changes to docstrings.  Squashing them allows one to list the overall changes in a list in a single commit message (you don't have to get rid of useful messages).  This list also includes merge commits.  If you want to revert the changes made by this pull request, you would have to revert those as well.

Usually I squash manually, with interactive rebase, rather than do it through github.  However, I agree that if a pull request has 5 commits and each one does a specific independent thing, then absolutely it is great to preserve that granularity.

DESI repos have no policy on this kind of thing, and the history is already complicated, so I guess it doesn't really matter at this point.  Sorry for the noise...

**Comment by julienguy** [comment]
Travis tests are failing because an environment variable DESI_CCD_CALIBRATION_DATA is needed for the calibration files (bias,dark...)

**Comment by julienguy** [comment]
I will fix this because we don't need calibration data for sims ...

**Comment by sbailey** [comment]
Heads up: this will break pixsim-desi in desisim until we update it to call the new preproc API and make sure it provides the necessary keywords.  I'll merge this now anyway so that it isn't a blocking factor for Julien and we can update desisim soon.

**Pull request merged**
