### PR TITLE
Rewrite of nightly scripts

### PR DESCRIPTION
**Pull request by tskisner**
This is a re-write from scratch of the nightly scripts, and includes a "desi_fake_dts" script to copy data into DESI_SPECTRO_DATA at regular intervals.  Do not merge yet.  I have some some rough tests, but the queue time for full exposures has hampered testing.

As previously discussed with @sbailey , I am going to add "--spectrograph" options to desi_pipe and desi_night.  This will allow processing a much smaller set of data for testing, at least up through calibrated frames.  Hopefully that will enable better testing and finding of small bugs.

### CODE REVIEW

**Comment by tskisner** [comment]
@sbailey and @julienguy , in order to test this, make an empty directory as your location for $DESI_SPECTRO_DATA.  Then create a production from this (I strongly recommend postgres backend).  Load the production setup.sh.  Then run desi_fake_dts and specify the directory of data with the ```--staging``` option.  Due to queue limits, you will likely need to use the regular queue.

I have tested that 2 nights of data were queued with correct dependencies, one exposure at a time.  The ```--spec``` option turned out to not be so useful (and might be broken).  Further testing welcome.  I also fixed some small issues (the getready function now has the night as an option rather than a requirement).

One annoyance:  the desi_night script uses the submitted status of tasks, but there is no way to clear just the submitted flags for a single exposure without using SQL directly.  We should add an expid option to ```desi_pipe cleanup```.

**Comment by tskisner** [comment]
I am going to add the ```desi_pipe cleanup --expid <blah> --submitted``` option to this branch, since it is really, really needed when debugging.  Basically any time you kill a job, ```desi_night``` will refuse to touch those tasks (since they are already submitted).  So you must clear the state somehow (currently with manual SQL commands).  In the next development push, we'll have the job table in the DB, so we will be able to automatically clean up tasks like this.  This option will be a stop-gap.

**Comment by sbailey** [comment]
How do you get `desi_night update` to submit jobs to the queue?  When I run `desi_night update --nersc_queue debug --night 20200501 --expid 4598`, it starts running the commands serially on the login node itself rather than submitting a job to the debug queue to run them in parallel.  For starters I'm running this outside of `desi_fake_dts` because I want to see the impact of what is submitted / run from each `desi_night` call.

**Comment by tskisner** [comment]
@sbailey, just as with desi_pipe, you must specify the ```--nersc``` option to specify the nersc machine.  Otherwise simple bash scripts are used.

**Comment by sbailey** [comment]
Still working on testing this.  At minimum we need to update the preproc job script logic to allocate more cores per rank to not run out of memory.

  Please add docstrings to all the functions in `desispec.scripts.night.Nightly`, including the `_private` functions, as documentation for other developers.

**Comment by sbailey** [comment]
Starting from a blank production, I copied two arc exposures into $DESI_SPECTRO_DATA and ran `desi_night update` on both of them.  Before the jobs started running, I then ran `desi_night arcs ...` on that night and it said:
```
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000000.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000001.fits
INFO:night.py:425:arcs: psfnight for 20200515 already done
```
But psfnight hasn't been done...  The DB seems to be in an odd state with no psfnight queued up:
```
----------------+---------+---------+---------+---------+---------+---------+
   Task Type    | waiting | ready   | running | done    | failed  | submit  |
----------------+---------+---------+---------+---------+---------+---------+
preproc         |        0|       60|        0|        0|        0|       60|
psf             |        0|        0|        0|        0|        0|        0|
psfnight        |        0|        0|        0|        0|        0|        0|
traceshift      |       60|        0|        0|        0|        0|       60|
extract         |       60|        0|        0|        0|        0|       60|
fiberflat       |       60|        0|        0|        0|        0|       60|
fiberflatnight  |       30|        0|        0|        0|        0|        0|
sky             |        0|        0|        0|        0|        0|        0|
starfit         |        0|        0|        0|        0|        0|        0|
fluxcalib       |        0|        0|        0|        0|        0|        0|
cframe          |        0|        0|        0|        0|        0|        0|
spectra         |        0|        0|        0|        0|        0|       NA|
redshift        |        0|        0|        0|        0|        0|       NA|
----------------+---------+---------+---------+---------+---------+---------+
```
Does the psfnight task not appear until after a psf has been run (not just submitted)?

**Comment by sbailey** [comment]
Sorry for the noise; I submitted flats before arcs...  I'll delete that comment to cleanup the github thread and try again...

**Comment by tskisner** [comment]
After my most recent commit, I got an error when submitting a science frame with ```desi_night update``` after the fiberflatnight job had been queued but not yet run.  I'm investigating further.

**Comment by sbailey** [comment]
When I `desi_night update` my first arc, it generated the command in the script
```
srun --cpu_bind=cores -n 304 -N 19 -c 4 /global/cscratch1/sd/sjbailey/desi/code/desispec/bin/desi_pipe_exec_mpi --tasktype preproc --taskfile /global/cscratch1/sd/sjbailey/desi/redwood/spectro/redux/redwood/run/scripts/night/20200515/preproc-psf_20180518-151355/cori-haswell_preproc.tasks
```
Shouldn't that be `srun ... -n 30 -N 2 -c 4 ...` or similar?  There are only 30 tasks in the file and I think preproc is single threaded, so spawning 304 ranks seems odd.

**Comment by sbailey** [comment]
I've been trickling jobs through the debug queue by hand.  arcs and flats worked fine, as did the first science exposure.  The second and third science exposure appear to have launched the correct jobs, but gave a traceback which is perhaps the error that you mentioned.  It is also reading all of the previous fibermaps even though the update was just for a single expid:
```
[cori03 ~] desi_night update --nersc_queue debug --nersc cori-haswell --night 20200515 --expid 12
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000000.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000001.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000005.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000006.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000007.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000010.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000011.fits
INFO:db.py:119:all_tasks: read /global/cscratch1/sd/sjbailey/desi/redwood/spectro/sim/redwood-nightly/20200515/fibermap-00000012.fits

[... a bunch of db insert messages ... ]

INFO:night.py:119:_select_exposures: found unprocessed extract exposure 12
INFO:night.py:204:_run_chain: Running desi_pipe chain --tasktypes preproc,traceshift --pack --nosubmitted --nights 20200515 --outdir night/20200515 --expid 12 --nersc cori-haswell --nersc_queue debug
INFO:night.py:204:_run_chain: Running desi_pipe chain --tasktypes extract --pack --nosubmitted --nights 20200515 --outdir night/20200515 --expid 12 --depjobs 12615113 --nersc cori-haswell --nersc_queue debug
Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/desi/code/desispec/bin/desi_night", line 14, in <module>
    n = Nightly()
  File "/global/cscratch1/sd/sjbailey/desi/code/desispec/py/desispec/scripts/night.py", line 67, in __init__
    getattr(self, args.command)()
  File "/global/cscratch1/sd/sjbailey/desi/code/desispec/py/desispec/scripts/night.py", line 375, in update
    alldeps = list(ntflatdeps)
TypeError: 'NoneType' object is not iterable
```

**Comment by tskisner** [comment]
@sbailey, remember that the preproc job is being packed into the same job as the psf estimation.  So desi_pipe_exec_mpi is being run with many more processes than needed, and most will sit idle during preproc.  During psf estimation they will all be used.

Although this is harmless, it might cause unnecessary startup overhead on the smaller job, so I should probably pass in the total procs needed for each command in the script generation.  Will do that shortly.

**Comment by sbailey** [comment]
Hit fiberflat night timeout problem during testing; increased default fiberflatnight jobtime from 1 minute to 5 minutes.  Otherwise worked end-to-end with trickling jobs through the debug queue.

Request for docstrings on functions in `desispec.night.Nightly` is still outstanding, but will proceed with PR now anyway.  Please add those on a subsequent pipeline documentation pass.

**Comment by tskisner** [comment]
Do you want the more detailed integration tests in a separate branch then?  I had been adding them here but will move them to a new branch in that case.

**Comment by sbailey** [comment]
Yes, let's spin the pipeline integration tests into a new branch instead of dragging this one out.  +1 for smaller more frequent merges.

**Pull request merged**
