### PR TITLE
Quicklook Update

### PR DESCRIPTION
**Pull request by gdhungana**
Still working on the pipeline but sufficient update for this PR. This PR updates the boxcar to be using the bootcalib psf, as well as specter.psf.PSF. A similar psf interface is added. This only works for CCD x/y centroids and the wavelength solution. No resolution accounted yet.

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks.  This PR contains many many changes that come from the merging of master into dhungana:quicklook.  I'm going to try doing a merge of master into desihub:quicklook as a separate operation to see if that simplifies what github shows here so that we can focus on the changes you actually made instead of the hundreds of other changes from that master -> quicklook merge.

**Comment by sbailey** [comment]
do'h!  merging desihub:master into desihub:quicklook generated a conflict with gdhungana:quicklook.  I will seek advice from a git master (@tskisner) before proceeding...

**Comment by tskisner** [comment]
Wait, so there is a fork of desispec under user gdhungana, and it has a 
branch that matches a branch of the same in the desispec repo under 
desihub?

Is there a particular reason for using a fork?  Usually I only do that 
when I want to submit pull requests to repos where I don't have commit 
access...

My general workflow without forking is:

1.  work on local branch.

2.  Continually keep branch up to date with changes in master by 
merging master into my branch, resolving conflicts as needed.  (if the 
branch is purely local, you might rebase instead of merging, but ignore 
that for now)

3.  if multiple people need to work on that branch, then push it.

4.  when branch is ready for integration with master, always merge 
master into the branch first to deal with conflicts (see #2).

5.  push latest version of branch and open pull request.

If you then bring forking into the mix, you must additionally keep 
origin/master up to date with upstream/master:

$> git fetch upstream
$> git fetch
$> git checkout master
$> git rebase upstream/master
$> git push origin master

So it seems unnecessary to do this if you have commit access.

-Ted

**Comment by gdhungana** [comment]
Yes, I always pull the upstream/master to my local repo and then I push the
update to the origin/master or origin/branch, from where I send the
pull-request.  Would pushing to origin/master or origin/branch makes any
difference? Nonetheless, should I make another request or open a new branch
for this case?

**Comment by sbailey** [comment]
Documenting for the record, before closing.  Thanks to @tskisner's git-fu for helping me investigate this.

I made a fresh copy of desihub/desispec and gdhungana/desispec:
```
git clone https://github.com/desihub/desispec
cd desispec
git checkout quicklook

git remote add govinda https://github.com/gdhungana/desispec
git fetch govinda
git branch -a
```
I made a new local branch tracking Govinda's remote quicklook:
```
git checkout -b govinda_quicklook -t govinda/quicklook
```
GitHub claims a conflict between gdhungana:quicklook and desihub:quicklook but with no further details, but I was able to merge without any trouble:
```
git checkout quicklook
git merge govinda_quicklook
```
I pushed this merged version of quicklook to github, and then opened PR #160 to supersede this one.
```
git checkout -b merged_govinda_quicklook
git push origin merged_govinda_quicklook
```
That PR shows just the recent changes from Govinda, and doesn't have a merge conflict.  Closing this one and proceeding with that one.

**Pull request closed without merging**
